package testport

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"slices"
	"strings"
	"unicode"

	"github.com/mavioai/mavio/tools/testport/internal/csharp"
)

// Mapping says where Jellyfin test cases and assets go in Mavio.
type Mapping struct {
	Repository string         `json:"repository"`
	Cases      []CaseMapping  `json:"cases"`
	Assets     []AssetMapping `json:"assets"`
	Constants  []ConstMapping `json:"constants"`
}

// CaseMapping maps C# test files under Source (a directory or file, relative
// to the Jellyfin repository) to JSON case files under Target (relative to
// the Mavio repository). The longest matching Source wins.
type CaseMapping struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

// AssetMapping copies test data files from Source to Target.
type AssetMapping struct {
	Source    string `json:"source"`
	Target    string `json:"target"`
	Include   string `json:"include,omitempty"` // glob on the file name; empty means all
	Recursive bool   `json:"recursive,omitempty"`
}

// ConstMapping extracts the constant fields of the C# file Source into the
// JSON file Target, keyed by "Class.Name", so that case arguments naming them
// as {"$symbol": "Class.Name"} can be resolved.
type ConstMapping struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

// LoadMapping reads a mapping file.
func LoadMapping(file string) (Mapping, error) {
	var m Mapping
	data, err := os.ReadFile(file)
	if err != nil {
		return m, err
	}
	return m, json.Unmarshal(data, &m)
}

// Options configures Port.
type Options struct {
	Jellyfin string // Jellyfin repository root
	Mavio    string // Mavio repository root
	Mapping  Mapping
	// Only restricts porting to targets with one of these prefixes.
	Only   []string
	DryRun bool
}

// Summary counts what Port produced.
type Summary struct {
	Files       int // case files written
	Theories    int
	Cases       int
	Facts       int
	Unsupported int
	Assets      int
	Constants   int
}

// Source identifies where extracted data came from.
type Source struct {
	Repository string `json:"repository"`
	Commit     string `json:"commit,omitempty"`
	File       string `json:"file,omitempty"`
}

// CaseFile is the JSON document written for each test class.
type CaseFile struct {
	Comment string `json:"$comment"`
	Source  Source `json:"source"`
	TestClass
}

const generatedComment = "Generated by tools/testport. Do not edit; record skips in the Go test."

// Port extracts cases and copies assets according to opts.
func Port(ctx context.Context, opts Options) (Summary, error) {
	var sum Summary
	commit := gitCommit(ctx, opts.Jellyfin)
	selected := func(target string) bool {
		return len(opts.Only) == 0 || slices.ContainsFunc(opts.Only, func(p string) bool {
			return target == p || strings.HasPrefix(target, strings.TrimSuffix(p, "/")+"/")
		})
	}

	files, err := csharpFiles(opts.Jellyfin, opts.Mapping.Cases)
	if err != nil {
		return sum, err
	}
	written := map[string]string{}
	for _, rel := range files {
		cm, ok := matchCase(opts.Mapping.Cases, rel)
		if !ok || !selected(cm.Target) {
			continue
		}
		src, err := os.ReadFile(filepath.Join(opts.Jellyfin, filepath.FromSlash(rel)))
		if err != nil {
			return sum, err
		}
		classes, err := Extract(string(src))
		if err != nil {
			return sum, fmt.Errorf("%s: %w", rel, err)
		}
		for _, tc := range classes {
			out := outputPath(cm, rel, tc.Class)
			if prev, dup := written[out]; dup {
				return sum, fmt.Errorf("%s and %s both map to %s", prev, rel, out)
			}
			written[out] = rel
			doc := CaseFile{
				Comment:   generatedComment,
				Source:    Source{Repository: opts.Mapping.Repository, Commit: commit, File: rel},
				TestClass: tc,
			}
			if !opts.DryRun {
				if err := writeJSON(filepath.Join(opts.Mavio, filepath.FromSlash(out)), doc); err != nil {
					return sum, err
				}
			}
			sum.Files++
			sum.Theories += len(tc.Theories)
			for _, th := range tc.Theories {
				sum.Cases += len(th.Cases)
			}
			sum.Facts += len(tc.Facts)
			sum.Unsupported += len(tc.Unsupported)
		}
	}

	for _, am := range opts.Mapping.Assets {
		if !selected(am.Target) {
			continue
		}
		n, err := copyAssets(opts, am, commit)
		if err != nil {
			return sum, err
		}
		sum.Assets += n
	}

	for _, cm := range opts.Mapping.Constants {
		if !selected(cm.Target) {
			continue
		}
		n, err := writeConstants(opts, cm, commit)
		if err != nil {
			return sum, err
		}
		sum.Constants += n
	}
	return sum, nil
}

// ConstFile is the JSON document written for each constant mapping.
type ConstFile struct {
	Comment   string     `json:"$comment"`
	Source    Source     `json:"source"`
	Constants csharp.Map `json:"constants"`
}

func writeConstants(opts Options, cm ConstMapping, commit string) (int, error) {
	src, err := os.ReadFile(filepath.Join(opts.Jellyfin, filepath.FromSlash(cm.Source)))
	if err != nil {
		return 0, err
	}
	consts, err := ExtractConstants(string(src))
	if err != nil {
		return 0, fmt.Errorf("%s: %w", cm.Source, err)
	}
	if len(consts) == 0 {
		return 0, fmt.Errorf("constants %s: none found", cm.Source)
	}
	if !opts.DryRun {
		doc := ConstFile{
			Comment:   generatedComment,
			Source:    Source{Repository: opts.Mapping.Repository, Commit: commit, File: cm.Source},
			Constants: consts,
		}
		if err := writeJSON(filepath.Join(opts.Mavio, filepath.FromSlash(cm.Target)), doc); err != nil {
			return 0, err
		}
	}
	return len(consts), nil
}

// csharpFiles lists the .cs files under every case mapping source, as
// slash-separated paths relative to root.
func csharpFiles(root string, cases []CaseMapping) ([]string, error) {
	set := map[string]bool{}
	for _, cm := range cases {
		base := filepath.Join(root, filepath.FromSlash(cm.Source))
		err := filepath.WalkDir(base, func(p string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() && (d.Name() == "bin" || d.Name() == "obj") {
				return filepath.SkipDir
			}
			if !d.IsDir() && strings.HasSuffix(p, ".cs") {
				rel, err := filepath.Rel(root, p)
				if err != nil {
					return err
				}
				set[filepath.ToSlash(rel)] = true
			}
			return nil
		})
		if err != nil {
			return nil, fmt.Errorf("mapping source %s: %w", cm.Source, err)
		}
	}
	return slices.Sorted(maps.Keys(set)), nil
}

func matchCase(cases []CaseMapping, rel string) (CaseMapping, bool) {
	var best CaseMapping
	found := false
	for _, cm := range cases {
		if (rel == cm.Source || strings.HasPrefix(rel, cm.Source+"/")) && len(cm.Source) > len(best.Source) {
			best, found = cm, true
		}
	}
	return best, found
}

// outputPath returns Target/<subdirs>/<class>.json, with the source's
// subdirectories and the class name converted to snake_case and the
// Test/Tests suffix removed.
func outputPath(cm CaseMapping, rel, class string) string {
	dir := ""
	if rest, ok := strings.CutPrefix(path.Dir(rel), cm.Source); ok {
		for _, seg := range strings.Split(strings.Trim(rest, "/"), "/") {
			if seg != "" {
				dir = path.Join(dir, snake(seg))
			}
		}
	}
	name := strings.ReplaceAll(class, ".", "_")
	for _, suffix := range []string{"Tests", "Test"} {
		if trimmed, ok := strings.CutSuffix(name, suffix); ok && trimmed != "" {
			name = trimmed
			break
		}
	}
	return path.Join(cm.Target, dir, snake(name)+".json")
}

// snake converts an identifier such as "EpisodeNumberTests", "TV" or
// "Format3D" to snake_case ("episode_number_tests", "tv", "format_3d").
func snake(s string) string {
	rs := []rune(s)
	var b strings.Builder
	for i, r := range rs {
		if i > 0 && r != '_' && rs[i-1] != '_' {
			prev := rs[i-1]
			nextLower := i+1 < len(rs) && unicode.IsLower(rs[i+1])
			switch {
			case unicode.IsUpper(r) && (unicode.IsLower(prev) || unicode.IsUpper(prev) && nextLower):
				b.WriteByte('_')
			case unicode.IsDigit(r) && unicode.IsLetter(prev):
				b.WriteByte('_')
			}
		}
		if r == ' ' || r == '-' || r == '.' {
			r = '_'
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// copyAssets copies the files of one asset mapping and writes SOURCES.json
// next to them, recording where each file came from.
func copyAssets(opts Options, am AssetMapping, commit string) (int, error) {
	base := filepath.Join(opts.Jellyfin, filepath.FromSlash(am.Source))
	target := filepath.Join(opts.Mavio, filepath.FromSlash(am.Target))
	sources := map[string]string{}
	err := filepath.WalkDir(base, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if p != base && !am.Recursive {
				return filepath.SkipDir
			}
			return nil
		}
		if am.Include != "" {
			if ok, _ := path.Match(am.Include, d.Name()); !ok {
				return nil
			}
		}
		relToBase, err := filepath.Rel(base, p)
		if err != nil {
			return err
		}
		relToRepo, err := filepath.Rel(opts.Jellyfin, p)
		if err != nil {
			return err
		}
		sources[filepath.ToSlash(relToBase)] = filepath.ToSlash(relToRepo)
		if opts.DryRun {
			return nil
		}
		return copyFile(p, filepath.Join(target, relToBase))
	})
	if err != nil {
		return 0, fmt.Errorf("assets %s: %w", am.Source, err)
	}
	if len(sources) == 0 {
		return 0, fmt.Errorf("assets %s: no files matched", am.Source)
	}
	if !opts.DryRun {
		doc := struct {
			Comment    string            `json:"$comment"`
			Repository string            `json:"repository"`
			Commit     string            `json:"commit,omitempty"`
			Files      map[string]string `json:"files"`
		}{generatedComment, opts.Mapping.Repository, commit, sources}
		if err := writeJSON(filepath.Join(target, "SOURCES.json"), doc); err != nil {
			return 0, err
		}
	}
	return len(sources), nil
}

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0o644)
}

func writeJSON(file string, v any) error {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
		return err
	}
	return os.WriteFile(file, b.Bytes(), 0o644)
}

func gitCommit(ctx context.Context, dir string) string {
	// The commit is informational; a checkout without git metadata yields "".
	out, err := exec.CommandContext(ctx, "git", "-C", dir, "rev-parse", "HEAD").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
