// Code generated by ent, DO NOT EDIT.

package image

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id core.ID) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id core.ID) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id core.ID) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...core.ID) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...core.ID) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id core.ID) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id core.ID) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id core.ID) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id core.ID) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldID, id))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v core.ID) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldItemID, v))
}

// PersonID applies equality check predicate on the "person_id" field. It's identical to PersonIDEQ.
func PersonID(v core.ID) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldPersonID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldKind, v))
}

// Index applies equality check predicate on the "index" field. It's identical to IndexEQ.
func Index(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldIndex, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldPath, v))
}

// RemoteURL applies equality check predicate on the "remote_url" field. It's identical to RemoteURLEQ.
func RemoteURL(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldRemoteURL, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldHeight, v))
}

// Blurhash applies equality check predicate on the "blurhash" field. It's identical to BlurhashEQ.
func Blurhash(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldBlurhash, v))
}

// Thumbhash applies equality check predicate on the "thumbhash" field. It's identical to ThumbhashEQ.
func Thumbhash(v []byte) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldThumbhash, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v core.ID) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v core.ID) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...core.ID) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...core.ID) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDIsNil applies the IsNil predicate on the "item_id" field.
func ItemIDIsNil() predicate.Image {
	return predicate.Image(sql.FieldIsNull(FieldItemID))
}

// ItemIDNotNil applies the NotNil predicate on the "item_id" field.
func ItemIDNotNil() predicate.Image {
	return predicate.Image(sql.FieldNotNull(FieldItemID))
}

// PersonIDEQ applies the EQ predicate on the "person_id" field.
func PersonIDEQ(v core.ID) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldPersonID, v))
}

// PersonIDNEQ applies the NEQ predicate on the "person_id" field.
func PersonIDNEQ(v core.ID) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldPersonID, v))
}

// PersonIDIn applies the In predicate on the "person_id" field.
func PersonIDIn(vs ...core.ID) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldPersonID, vs...))
}

// PersonIDNotIn applies the NotIn predicate on the "person_id" field.
func PersonIDNotIn(vs ...core.ID) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldPersonID, vs...))
}

// PersonIDIsNil applies the IsNil predicate on the "person_id" field.
func PersonIDIsNil() predicate.Image {
	return predicate.Image(sql.FieldIsNull(FieldPersonID))
}

// PersonIDNotNil applies the NotNil predicate on the "person_id" field.
func PersonIDNotNil() predicate.Image {
	return predicate.Image(sql.FieldNotNull(FieldPersonID))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Image {
	return predicate.Image(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Image {
	return predicate.Image(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Image {
	return predicate.Image(sql.FieldContainsFold(FieldKind, v))
}

// IndexEQ applies the EQ predicate on the "index" field.
func IndexEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldIndex, v))
}

// IndexNEQ applies the NEQ predicate on the "index" field.
func IndexNEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldIndex, v))
}

// IndexIn applies the In predicate on the "index" field.
func IndexIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldIndex, vs...))
}

// IndexNotIn applies the NotIn predicate on the "index" field.
func IndexNotIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldIndex, vs...))
}

// IndexGT applies the GT predicate on the "index" field.
func IndexGT(v int) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldIndex, v))
}

// IndexGTE applies the GTE predicate on the "index" field.
func IndexGTE(v int) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldIndex, v))
}

// IndexLT applies the LT predicate on the "index" field.
func IndexLT(v int) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldIndex, v))
}

// IndexLTE applies the LTE predicate on the "index" field.
func IndexLTE(v int) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldIndex, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.Image {
	return predicate.Image(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.Image {
	return predicate.Image(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.Image {
	return predicate.Image(sql.FieldContainsFold(FieldPath, v))
}

// RemoteURLEQ applies the EQ predicate on the "remote_url" field.
func RemoteURLEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldRemoteURL, v))
}

// RemoteURLNEQ applies the NEQ predicate on the "remote_url" field.
func RemoteURLNEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldRemoteURL, v))
}

// RemoteURLIn applies the In predicate on the "remote_url" field.
func RemoteURLIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldRemoteURL, vs...))
}

// RemoteURLNotIn applies the NotIn predicate on the "remote_url" field.
func RemoteURLNotIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldRemoteURL, vs...))
}

// RemoteURLGT applies the GT predicate on the "remote_url" field.
func RemoteURLGT(v string) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldRemoteURL, v))
}

// RemoteURLGTE applies the GTE predicate on the "remote_url" field.
func RemoteURLGTE(v string) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldRemoteURL, v))
}

// RemoteURLLT applies the LT predicate on the "remote_url" field.
func RemoteURLLT(v string) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldRemoteURL, v))
}

// RemoteURLLTE applies the LTE predicate on the "remote_url" field.
func RemoteURLLTE(v string) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldRemoteURL, v))
}

// RemoteURLContains applies the Contains predicate on the "remote_url" field.
func RemoteURLContains(v string) predicate.Image {
	return predicate.Image(sql.FieldContains(FieldRemoteURL, v))
}

// RemoteURLHasPrefix applies the HasPrefix predicate on the "remote_url" field.
func RemoteURLHasPrefix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasPrefix(FieldRemoteURL, v))
}

// RemoteURLHasSuffix applies the HasSuffix predicate on the "remote_url" field.
func RemoteURLHasSuffix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasSuffix(FieldRemoteURL, v))
}

// RemoteURLEqualFold applies the EqualFold predicate on the "remote_url" field.
func RemoteURLEqualFold(v string) predicate.Image {
	return predicate.Image(sql.FieldEqualFold(FieldRemoteURL, v))
}

// RemoteURLContainsFold applies the ContainsFold predicate on the "remote_url" field.
func RemoteURLContainsFold(v string) predicate.Image {
	return predicate.Image(sql.FieldContainsFold(FieldRemoteURL, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldHeight, v))
}

// BlurhashEQ applies the EQ predicate on the "blurhash" field.
func BlurhashEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldBlurhash, v))
}

// BlurhashNEQ applies the NEQ predicate on the "blurhash" field.
func BlurhashNEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldBlurhash, v))
}

// BlurhashIn applies the In predicate on the "blurhash" field.
func BlurhashIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldBlurhash, vs...))
}

// BlurhashNotIn applies the NotIn predicate on the "blurhash" field.
func BlurhashNotIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldBlurhash, vs...))
}

// BlurhashGT applies the GT predicate on the "blurhash" field.
func BlurhashGT(v string) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldBlurhash, v))
}

// BlurhashGTE applies the GTE predicate on the "blurhash" field.
func BlurhashGTE(v string) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldBlurhash, v))
}

// BlurhashLT applies the LT predicate on the "blurhash" field.
func BlurhashLT(v string) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldBlurhash, v))
}

// BlurhashLTE applies the LTE predicate on the "blurhash" field.
func BlurhashLTE(v string) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldBlurhash, v))
}

// BlurhashContains applies the Contains predicate on the "blurhash" field.
func BlurhashContains(v string) predicate.Image {
	return predicate.Image(sql.FieldContains(FieldBlurhash, v))
}

// BlurhashHasPrefix applies the HasPrefix predicate on the "blurhash" field.
func BlurhashHasPrefix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasPrefix(FieldBlurhash, v))
}

// BlurhashHasSuffix applies the HasSuffix predicate on the "blurhash" field.
func BlurhashHasSuffix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasSuffix(FieldBlurhash, v))
}

// BlurhashEqualFold applies the EqualFold predicate on the "blurhash" field.
func BlurhashEqualFold(v string) predicate.Image {
	return predicate.Image(sql.FieldEqualFold(FieldBlurhash, v))
}

// BlurhashContainsFold applies the ContainsFold predicate on the "blurhash" field.
func BlurhashContainsFold(v string) predicate.Image {
	return predicate.Image(sql.FieldContainsFold(FieldBlurhash, v))
}

// ThumbhashEQ applies the EQ predicate on the "thumbhash" field.
func ThumbhashEQ(v []byte) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldThumbhash, v))
}

// ThumbhashNEQ applies the NEQ predicate on the "thumbhash" field.
func ThumbhashNEQ(v []byte) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldThumbhash, v))
}

// ThumbhashIn applies the In predicate on the "thumbhash" field.
func ThumbhashIn(vs ...[]byte) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldThumbhash, vs...))
}

// ThumbhashNotIn applies the NotIn predicate on the "thumbhash" field.
func ThumbhashNotIn(vs ...[]byte) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldThumbhash, vs...))
}

// ThumbhashGT applies the GT predicate on the "thumbhash" field.
func ThumbhashGT(v []byte) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldThumbhash, v))
}

// ThumbhashGTE applies the GTE predicate on the "thumbhash" field.
func ThumbhashGTE(v []byte) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldThumbhash, v))
}

// ThumbhashLT applies the LT predicate on the "thumbhash" field.
func ThumbhashLT(v []byte) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldThumbhash, v))
}

// ThumbhashLTE applies the LTE predicate on the "thumbhash" field.
func ThumbhashLTE(v []byte) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldThumbhash, v))
}

// ThumbhashIsNil applies the IsNil predicate on the "thumbhash" field.
func ThumbhashIsNil() predicate.Image {
	return predicate.Image(sql.FieldIsNull(FieldThumbhash))
}

// ThumbhashNotNil applies the NotNil predicate on the "thumbhash" field.
func ThumbhashNotNil() predicate.Image {
	return predicate.Image(sql.FieldNotNull(FieldThumbhash))
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.Image {
	return predicate.Image(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.Item) predicate.Image {
	return predicate.Image(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPerson applies the HasEdge predicate on the "person" edge.
func HasPerson() predicate.Image {
	return predicate.Image(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PersonTable, PersonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPersonWith applies the HasEdge predicate on the "person" edge with a given conditions (other predicates).
func HasPersonWith(preds ...predicate.Person) predicate.Image {
	return predicate.Image(func(s *sql.Selector) {
		step := newPersonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Image) predicate.Image {
	return predicate.Image(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Image) predicate.Image {
	return predicate.Image(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Image) predicate.Image {
	return predicate.Image(sql.NotPredicates(p))
}
