package store

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

func TestCleanValue(t *testing.T) {
	for in, want := range map[string]string{
		"Amélie":                 "amelie",
		"Ｃａｒｏｌ":                  "carol",
		"  The   Matrix ":        "the matrix",
		"Spider-Man: Homecoming": "spider man homecoming",
		"100% Wolf":              "100 wolf",
		"Ip_Man":                 "ip man",
		"千と千尋の神隠し":               "千と千尋の神隠し",
		"ガンダム":                   "ガンダム", // voicing marks are not diacritics
		"Pokémon: Ｔｈｅ Ｆｉｌｍ":      "pokemon the film",
		"Le cœur a ses raisons":  "le coeur a ses raisons",
		"!!!":                    "",
	} {
		if got := cleanValue(in); got != want {
			t.Errorf("cleanValue(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestSortKeyOrdering(t *testing.T) {
	keys := map[string]string{}
	for _, n := range []string{"Rocky 2", "Rocky 10", "The Shining", "Spider-Man", "Amélie"} {
		keys[n] = sortKey(n)
	}
	if keys["Rocky 2"] >= keys["Rocky 10"] {
		t.Errorf("Rocky 2 (%q) should sort before Rocky 10 (%q)", keys["Rocky 2"], keys["Rocky 10"])
	}
	if keys["The Shining"] >= keys["Spider-Man"] {
		t.Errorf("The Shining (%q) should sort under S, before Spider-Man (%q)", keys["The Shining"], keys["Spider-Man"])
	}
	if keys["Amélie"] != "amelie" {
		t.Errorf("sortKey(Amélie) = %q", keys["Amélie"])
	}
	// Non-ASCII titles are transliterated, so Chinese sorts by pinyin.
	if got := sortKey("千与千寻"); got != "qian yu qian xun" {
		t.Errorf("sortKey(千与千寻) = %q", got)
	}
	if sortKey("阿凡达") >= sortKey("霸王别姬") { // a fan da < ba wang bie ji
		t.Errorf("pinyin order: %q vs %q", sortKey("阿凡达"), sortKey("霸王别姬"))
	}
}

func TestLikeEscape(t *testing.T) {
	if got := likeEscape(`100%_\x`); got != `100\%\_\\x` {
		t.Errorf("likeEscape = %q", got)
	}
	if got := likeRaw(`100%_\x`); got != `100%_\\x` {
		t.Errorf("likeRaw = %q", got)
	}
}

// caseFile is a test case file generated by tools/testport.
type caseFile struct {
	Theories []struct {
		Method string `json:"method"`
		Cases  []struct {
			ID   string                     `json:"id"`
			Skip string                     `json:"skip"`
			Args map[string]json.RawMessage `json:"args"`
		} `json:"cases"`
	} `json:"theories"`
	Facts []struct {
		Method string `json:"method"`
	} `json:"facts"`
}

func readCases(t *testing.T, name string) caseFile {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "cases", name))
	if err != nil {
		t.Fatal(err)
	}
	var f caseFile
	if err := json.Unmarshal(data, &f); err != nil {
		t.Fatal(err)
	}
	return f
}

func arg(t *testing.T, args map[string]json.RawMessage, name string) string {
	t.Helper()
	var s string
	if err := json.Unmarshal(args[name], &s); err != nil {
		t.Fatalf("argument %s: %v", name, err)
	}
	return s
}

// portedCases runs the theories and facts of a ported case file. run maps a
// theory to a check of one case; skip gives the reason a theory, case ID or
// fact does not apply. Every theory and fact must be either run or skipped.
func portedCases(t *testing.T, name string, run map[string]func(t *testing.T, args map[string]json.RawMessage), skip map[string]string) {
	f := readCases(t, name)
	for _, th := range f.Theories {
		check, ok := run[th.Method]
		methodSkip, skipped := skip[th.Method]
		if !ok && !skipped {
			t.Errorf("%s: theory %s is neither run nor skipped", name, th.Method)
			continue
		}
		for _, c := range th.Cases {
			t.Run(c.ID, func(t *testing.T) {
				switch {
				case c.Skip != "":
					t.Skip("skipped in Jellyfin: " + c.Skip)
				case skip[c.ID] != "":
					t.Skip(skip[c.ID])
				case skipped:
					t.Skip(methodSkip)
				}
				check(t, c.Args)
			})
		}
	}
	for _, fact := range f.Facts {
		if _, ok := skip[fact.Method]; !ok {
			t.Errorf("%s: fact %s is neither ported nor skipped", name, fact.Method)
		}
	}
}

const (
	notStore   = "not about search or sort keys; belongs to the library scanner and media versions"
	notMavio   = "covers a .NET string helper Mavio does not have"
	ffmpegArgs = "covers ffmpeg argument quoting; Mavio passes arguments to exec without a shell"
)

// Cases from Jellyfin's BaseItemTests: sort-name derivation.
func TestPortedBaseItem(t *testing.T) {
	portedCases(t, "base_item.json", map[string]func(*testing.T, map[string]json.RawMessage){
		"BaseItem_ModifySortChunks_Valid": func(t *testing.T, args map[string]json.RawMessage) {
			if got, want := sortChunks(arg(t, args, "input")), arg(t, args, "expected"); got != want {
				t.Errorf("sortChunks = %q, want = %q", got, want)
			}
		},
		"GetSortName_AppliesConfiguredCleaning": func(t *testing.T, args map[string]json.RawMessage) {
			if got, want := sortKey(arg(t, args, "input")), arg(t, args, "expected"); got != want {
				t.Errorf("sortKey = %q, want = %q", got, want)
			}
		},
	}, map[string]string{
		"ValidateChildren_FailedEnumeration_DoesNotReconcileOrDeleteChildren": notStore,
		"GetMediaSourceName_Valid":                                                     notStore,
		"GetMediaSourceName_CommonPrefix_Valid":                                        notStore,
		"SupportsOwnedItems_EpisodeWithResolvedVersionOrPart_IsTrue":                   notStore,
		"RefreshedOwnedItems_EpisodeInAContainersOwnFolder_LeavesExtrasToTheContainer": notStore,
		"GetOwnerIdForExtra_AssignsExtraToItsVersion":                                  notStore,
		"SetPrimaryVersionId_Null_RestoresTheItemsOwnPresentationKey":                  notStore,
		"GetItemByNameFolderName_ShortName_IsKeptAsIs":                                 notStore,
		"GetItemByNameFolderName_OverlongName_FitsInAPathComponent":                    notStore,
		"GetItemByNameFolderName_OverlongNamesSharingAPrefix_StayApart":                notStore,
		"GetItemByNameFolderName_OverlongName_IsStable":                                notStore,
		"GetSortName_WithoutAlphaNumericSorting_ReturnsTrimmedInput":                   "Mavio always sorts alphanumerically; there is no switch to turn it off",
		"SortName_ForcedSortName_IsCleanedLikeAutoSortName":                            "ported as TestForcedSortNameIsCleaned",
		"GetCommonVersionPrefix_NumericLabels_KeepsWholeNumber":                        notStore,
		"GetAlternateVersion_ReturnsMatchingLocalVersion":                              notStore,
		"GetAllVersions_FromAnyVersion_ReturnsEveryVersionOnce":                        notStore,
		"PropagatePlayedState_MarksAlternateVersions_AndResetsPositionByDefault":       notStore,
		"PropagatePlayedState_WithoutReset_LeavesPositionUntouched":                    notStore,
		"PropagatePlayedState_Unwatched_ClearsAllWatchedStateOnVersions":               notStore,
		"PropagatePlayedState_SingleVersion_DoesNothing":                               notStore,
		"GetMediaSources_DefaultsToTheQueriedVersionsOwnSource":                        notStore,
		"GetAllItemsForMediaSources_FromAnyVersion_HasNoDuplicates":                    notStore,
		"InheritDatesFromOwner_OwnerHasDates_OverwritesOwnedItemDates":                 notStore,
		"InheritDatesFromOwner_OwnerHasNoDates_KeepsOwnedItemDates":                    notStore,
		"InheritDatesFromOwner_DatesAlreadyMatch_ReportsNoChange":                      notStore,
		"InheritDatesFromOwner_OwnedItemHasNoDates_TakesOwnerDates":                    notStore,
		"GetExtraOwnerIds_FromAnyVersion_CoversEveryVersion":                           notStore,
		"GetOwnedVersionIds_CoversEveryLocalVersion":                                   notStore,
	})
}

// TestForcedSortNameIsCleaned ports Jellyfin's
// SortName_ForcedSortName_IsCleanedLikeAutoSortName: an explicit sort name
// is cleaned like a name.
func TestForcedSortNameIsCleaned(t *testing.T) {
	const raw = "The Spider-Man: Homecoming"
	if got := sortKey(raw); got != "spiderman: homecoming" {
		t.Errorf("sortKey(%q) = %q, want = %q", raw, got, "spiderman: homecoming")
	}
}

// Cases from Jellyfin's StringExtensionsTests: diacritics removal.
func TestPortedStringExtensions(t *testing.T) {
	portedCases(t, "string_extensions.json", map[string]func(*testing.T, map[string]json.RawMessage){
		"RemoveDiacritics_ValidInput_Corrects": func(t *testing.T, args map[string]json.RawMessage) {
			if got, want := removeDiacritics(arg(t, args, "input")), arg(t, args, "expectedResult"); got != want {
				t.Errorf("removeDiacritics = %q, want = %q", got, want)
			}
		},
	}, map[string]string{
		"RemoveDiacritics_ValidInput_Corrects/3":                    "strips a lone UTF-16 surrogate, which a Go string cannot hold",
		"HasDiacritics_ValidInput_Corrects":                         notMavio,
		"ReadOnlySpan_Count_Success":                                notMavio,
		"LeftPart_ValidArgsCharNeedle_Correct":                      notMavio,
		"RightPart_ValidArgsCharNeedle_Correct":                     notMavio,
		"EscapeProcessArgument_ValidInput_Corrects":                 ffmpegArgs,
		"EscapeProcessArgument_NothingToEscape_ReturnsSameInstance": ffmpegArgs,
	})
}
