// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/mavioai/mavio/libs/store/internal/ent"
	"github.com/mavioai/mavio/libs/store/internal/ent/activity"
	"github.com/mavioai/mavio/libs/store/internal/ent/apikey"
	"github.com/mavioai/mavio/libs/store/internal/ent/authsession"
	"github.com/mavioai/mavio/libs/store/internal/ent/credit"
	"github.com/mavioai/mavio/libs/store/internal/ent/displaypreferences"
	"github.com/mavioai/mavio/libs/store/internal/ent/folderstate"
	"github.com/mavioai/mavio/libs/store/internal/ent/image"
	"github.com/mavioai/mavio/libs/store/internal/ent/item"
	"github.com/mavioai/mavio/libs/store/internal/ent/itemlink"
	"github.com/mavioai/mavio/libs/store/internal/ent/itemvalue"
	"github.com/mavioai/mavio/libs/store/internal/ent/job"
	"github.com/mavioai/mavio/libs/store/internal/ent/library"
	"github.com/mavioai/mavio/libs/store/internal/ent/mediasegment"
	"github.com/mavioai/mavio/libs/store/internal/ent/mediasource"
	"github.com/mavioai/mavio/libs/store/internal/ent/person"
	"github.com/mavioai/mavio/libs/store/internal/ent/pluginconfig"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
	"github.com/mavioai/mavio/libs/store/internal/ent/setting"
	"github.com/mavioai/mavio/libs/store/internal/ent/trickplay"
	"github.com/mavioai/mavio/libs/store/internal/ent/user"
	"github.com/mavioai/mavio/libs/store/internal/ent/userdata"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The APIKeyFunc type is an adapter to allow the use of ordinary function as a Querier.
type APIKeyFunc func(context.Context, *ent.APIKeyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f APIKeyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.APIKeyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.APIKeyQuery", q)
}

// The TraverseAPIKey type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAPIKey func(context.Context, *ent.APIKeyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAPIKey) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAPIKey) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.APIKeyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.APIKeyQuery", q)
}

// The ActivityFunc type is an adapter to allow the use of ordinary function as a Querier.
type ActivityFunc func(context.Context, *ent.ActivityQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ActivityFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ActivityQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ActivityQuery", q)
}

// The TraverseActivity type is an adapter to allow the use of ordinary function as Traverser.
type TraverseActivity func(context.Context, *ent.ActivityQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseActivity) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseActivity) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ActivityQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ActivityQuery", q)
}

// The AuthSessionFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuthSessionFunc func(context.Context, *ent.AuthSessionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AuthSessionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AuthSessionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AuthSessionQuery", q)
}

// The TraverseAuthSession type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAuthSession func(context.Context, *ent.AuthSessionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAuthSession) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAuthSession) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuthSessionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AuthSessionQuery", q)
}

// The CreditFunc type is an adapter to allow the use of ordinary function as a Querier.
type CreditFunc func(context.Context, *ent.CreditQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CreditFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CreditQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CreditQuery", q)
}

// The TraverseCredit type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCredit func(context.Context, *ent.CreditQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCredit) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCredit) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CreditQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CreditQuery", q)
}

// The DisplayPreferencesFunc type is an adapter to allow the use of ordinary function as a Querier.
type DisplayPreferencesFunc func(context.Context, *ent.DisplayPreferencesQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f DisplayPreferencesFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.DisplayPreferencesQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DisplayPreferencesQuery", q)
}

// The TraverseDisplayPreferences type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDisplayPreferences func(context.Context, *ent.DisplayPreferencesQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDisplayPreferences) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDisplayPreferences) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.DisplayPreferencesQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DisplayPreferencesQuery", q)
}

// The FolderStateFunc type is an adapter to allow the use of ordinary function as a Querier.
type FolderStateFunc func(context.Context, *ent.FolderStateQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f FolderStateFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.FolderStateQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.FolderStateQuery", q)
}

// The TraverseFolderState type is an adapter to allow the use of ordinary function as Traverser.
type TraverseFolderState func(context.Context, *ent.FolderStateQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFolderState) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFolderState) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.FolderStateQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.FolderStateQuery", q)
}

// The ImageFunc type is an adapter to allow the use of ordinary function as a Querier.
type ImageFunc func(context.Context, *ent.ImageQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ImageFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ImageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ImageQuery", q)
}

// The TraverseImage type is an adapter to allow the use of ordinary function as Traverser.
type TraverseImage func(context.Context, *ent.ImageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseImage) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseImage) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ImageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ImageQuery", q)
}

// The ItemFunc type is an adapter to allow the use of ordinary function as a Querier.
type ItemFunc func(context.Context, *ent.ItemQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ItemFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ItemQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ItemQuery", q)
}

// The TraverseItem type is an adapter to allow the use of ordinary function as Traverser.
type TraverseItem func(context.Context, *ent.ItemQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseItem) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseItem) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ItemQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ItemQuery", q)
}

// The ItemLinkFunc type is an adapter to allow the use of ordinary function as a Querier.
type ItemLinkFunc func(context.Context, *ent.ItemLinkQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ItemLinkFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ItemLinkQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ItemLinkQuery", q)
}

// The TraverseItemLink type is an adapter to allow the use of ordinary function as Traverser.
type TraverseItemLink func(context.Context, *ent.ItemLinkQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseItemLink) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseItemLink) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ItemLinkQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ItemLinkQuery", q)
}

// The ItemValueFunc type is an adapter to allow the use of ordinary function as a Querier.
type ItemValueFunc func(context.Context, *ent.ItemValueQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ItemValueFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ItemValueQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ItemValueQuery", q)
}

// The TraverseItemValue type is an adapter to allow the use of ordinary function as Traverser.
type TraverseItemValue func(context.Context, *ent.ItemValueQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseItemValue) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseItemValue) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ItemValueQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ItemValueQuery", q)
}

// The JobFunc type is an adapter to allow the use of ordinary function as a Querier.
type JobFunc func(context.Context, *ent.JobQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f JobFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.JobQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.JobQuery", q)
}

// The TraverseJob type is an adapter to allow the use of ordinary function as Traverser.
type TraverseJob func(context.Context, *ent.JobQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseJob) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseJob) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.JobQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.JobQuery", q)
}

// The LibraryFunc type is an adapter to allow the use of ordinary function as a Querier.
type LibraryFunc func(context.Context, *ent.LibraryQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f LibraryFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.LibraryQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.LibraryQuery", q)
}

// The TraverseLibrary type is an adapter to allow the use of ordinary function as Traverser.
type TraverseLibrary func(context.Context, *ent.LibraryQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseLibrary) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseLibrary) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.LibraryQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.LibraryQuery", q)
}

// The MediaSegmentFunc type is an adapter to allow the use of ordinary function as a Querier.
type MediaSegmentFunc func(context.Context, *ent.MediaSegmentQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f MediaSegmentFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.MediaSegmentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.MediaSegmentQuery", q)
}

// The TraverseMediaSegment type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMediaSegment func(context.Context, *ent.MediaSegmentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMediaSegment) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMediaSegment) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MediaSegmentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.MediaSegmentQuery", q)
}

// The MediaSourceFunc type is an adapter to allow the use of ordinary function as a Querier.
type MediaSourceFunc func(context.Context, *ent.MediaSourceQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f MediaSourceFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.MediaSourceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.MediaSourceQuery", q)
}

// The TraverseMediaSource type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMediaSource func(context.Context, *ent.MediaSourceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMediaSource) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMediaSource) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MediaSourceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.MediaSourceQuery", q)
}

// The PersonFunc type is an adapter to allow the use of ordinary function as a Querier.
type PersonFunc func(context.Context, *ent.PersonQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PersonFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PersonQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PersonQuery", q)
}

// The TraversePerson type is an adapter to allow the use of ordinary function as Traverser.
type TraversePerson func(context.Context, *ent.PersonQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePerson) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePerson) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PersonQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PersonQuery", q)
}

// The PluginConfigFunc type is an adapter to allow the use of ordinary function as a Querier.
type PluginConfigFunc func(context.Context, *ent.PluginConfigQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PluginConfigFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PluginConfigQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PluginConfigQuery", q)
}

// The TraversePluginConfig type is an adapter to allow the use of ordinary function as Traverser.
type TraversePluginConfig func(context.Context, *ent.PluginConfigQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePluginConfig) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePluginConfig) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PluginConfigQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PluginConfigQuery", q)
}

// The SettingFunc type is an adapter to allow the use of ordinary function as a Querier.
type SettingFunc func(context.Context, *ent.SettingQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SettingFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SettingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SettingQuery", q)
}

// The TraverseSetting type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSetting func(context.Context, *ent.SettingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSetting) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSetting) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SettingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SettingQuery", q)
}

// The TrickplayFunc type is an adapter to allow the use of ordinary function as a Querier.
type TrickplayFunc func(context.Context, *ent.TrickplayQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f TrickplayFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.TrickplayQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.TrickplayQuery", q)
}

// The TraverseTrickplay type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTrickplay func(context.Context, *ent.TrickplayQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTrickplay) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTrickplay) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TrickplayQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.TrickplayQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ent.UserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ent.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The UserDataFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserDataFunc func(context.Context, *ent.UserDataQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserDataFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserDataQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserDataQuery", q)
}

// The TraverseUserData type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserData func(context.Context, *ent.UserDataQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserData) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserData) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserDataQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserDataQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.APIKeyQuery:
		return &query[*ent.APIKeyQuery, predicate.APIKey, apikey.OrderOption]{typ: ent.TypeAPIKey, tq: q}, nil
	case *ent.ActivityQuery:
		return &query[*ent.ActivityQuery, predicate.Activity, activity.OrderOption]{typ: ent.TypeActivity, tq: q}, nil
	case *ent.AuthSessionQuery:
		return &query[*ent.AuthSessionQuery, predicate.AuthSession, authsession.OrderOption]{typ: ent.TypeAuthSession, tq: q}, nil
	case *ent.CreditQuery:
		return &query[*ent.CreditQuery, predicate.Credit, credit.OrderOption]{typ: ent.TypeCredit, tq: q}, nil
	case *ent.DisplayPreferencesQuery:
		return &query[*ent.DisplayPreferencesQuery, predicate.DisplayPreferences, displaypreferences.OrderOption]{typ: ent.TypeDisplayPreferences, tq: q}, nil
	case *ent.FolderStateQuery:
		return &query[*ent.FolderStateQuery, predicate.FolderState, folderstate.OrderOption]{typ: ent.TypeFolderState, tq: q}, nil
	case *ent.ImageQuery:
		return &query[*ent.ImageQuery, predicate.Image, image.OrderOption]{typ: ent.TypeImage, tq: q}, nil
	case *ent.ItemQuery:
		return &query[*ent.ItemQuery, predicate.Item, item.OrderOption]{typ: ent.TypeItem, tq: q}, nil
	case *ent.ItemLinkQuery:
		return &query[*ent.ItemLinkQuery, predicate.ItemLink, itemlink.OrderOption]{typ: ent.TypeItemLink, tq: q}, nil
	case *ent.ItemValueQuery:
		return &query[*ent.ItemValueQuery, predicate.ItemValue, itemvalue.OrderOption]{typ: ent.TypeItemValue, tq: q}, nil
	case *ent.JobQuery:
		return &query[*ent.JobQuery, predicate.Job, job.OrderOption]{typ: ent.TypeJob, tq: q}, nil
	case *ent.LibraryQuery:
		return &query[*ent.LibraryQuery, predicate.Library, library.OrderOption]{typ: ent.TypeLibrary, tq: q}, nil
	case *ent.MediaSegmentQuery:
		return &query[*ent.MediaSegmentQuery, predicate.MediaSegment, mediasegment.OrderOption]{typ: ent.TypeMediaSegment, tq: q}, nil
	case *ent.MediaSourceQuery:
		return &query[*ent.MediaSourceQuery, predicate.MediaSource, mediasource.OrderOption]{typ: ent.TypeMediaSource, tq: q}, nil
	case *ent.PersonQuery:
		return &query[*ent.PersonQuery, predicate.Person, person.OrderOption]{typ: ent.TypePerson, tq: q}, nil
	case *ent.PluginConfigQuery:
		return &query[*ent.PluginConfigQuery, predicate.PluginConfig, pluginconfig.OrderOption]{typ: ent.TypePluginConfig, tq: q}, nil
	case *ent.SettingQuery:
		return &query[*ent.SettingQuery, predicate.Setting, setting.OrderOption]{typ: ent.TypeSetting, tq: q}, nil
	case *ent.TrickplayQuery:
		return &query[*ent.TrickplayQuery, predicate.Trickplay, trickplay.OrderOption]{typ: ent.TypeTrickplay, tq: q}, nil
	case *ent.UserQuery:
		return &query[*ent.UserQuery, predicate.User, user.OrderOption]{typ: ent.TypeUser, tq: q}, nil
	case *ent.UserDataQuery:
		return &query[*ent.UserDataQuery, predicate.UserData, userdata.OrderOption]{typ: ent.TypeUserData, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
