// Code generated by ent, DO NOT EDIT.

package mediasegment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldLTE(FieldID, id))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEQ(FieldItemID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEQ(FieldKind, v))
}

// Start applies equality check predicate on the "start" field. It's identical to StartEQ.
func Start(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldEQ(FieldStart, vc))
}

// End applies equality check predicate on the "end" field. It's identical to EndEQ.
func End(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldEQ(FieldEnd, vc))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEQ(FieldProvider, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...core.ID) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldNotIn(FieldItemID, vs...))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldContainsFold(FieldKind, v))
}

// StartEQ applies the EQ predicate on the "start" field.
func StartEQ(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldEQ(FieldStart, vc))
}

// StartNEQ applies the NEQ predicate on the "start" field.
func StartNEQ(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldNEQ(FieldStart, vc))
}

// StartIn applies the In predicate on the "start" field.
func StartIn(vs ...time.Duration) predicate.MediaSegment {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.MediaSegment(sql.FieldIn(FieldStart, v...))
}

// StartNotIn applies the NotIn predicate on the "start" field.
func StartNotIn(vs ...time.Duration) predicate.MediaSegment {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.MediaSegment(sql.FieldNotIn(FieldStart, v...))
}

// StartGT applies the GT predicate on the "start" field.
func StartGT(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldGT(FieldStart, vc))
}

// StartGTE applies the GTE predicate on the "start" field.
func StartGTE(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldGTE(FieldStart, vc))
}

// StartLT applies the LT predicate on the "start" field.
func StartLT(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldLT(FieldStart, vc))
}

// StartLTE applies the LTE predicate on the "start" field.
func StartLTE(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldLTE(FieldStart, vc))
}

// EndEQ applies the EQ predicate on the "end" field.
func EndEQ(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldEQ(FieldEnd, vc))
}

// EndNEQ applies the NEQ predicate on the "end" field.
func EndNEQ(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldNEQ(FieldEnd, vc))
}

// EndIn applies the In predicate on the "end" field.
func EndIn(vs ...time.Duration) predicate.MediaSegment {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.MediaSegment(sql.FieldIn(FieldEnd, v...))
}

// EndNotIn applies the NotIn predicate on the "end" field.
func EndNotIn(vs ...time.Duration) predicate.MediaSegment {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.MediaSegment(sql.FieldNotIn(FieldEnd, v...))
}

// EndGT applies the GT predicate on the "end" field.
func EndGT(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldGT(FieldEnd, vc))
}

// EndGTE applies the GTE predicate on the "end" field.
func EndGTE(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldGTE(FieldEnd, vc))
}

// EndLT applies the LT predicate on the "end" field.
func EndLT(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldLT(FieldEnd, vc))
}

// EndLTE applies the LTE predicate on the "end" field.
func EndLTE(v time.Duration) predicate.MediaSegment {
	vc := int64(v)
	return predicate.MediaSegment(sql.FieldLTE(FieldEnd, vc))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.MediaSegment {
	return predicate.MediaSegment(sql.FieldContainsFold(FieldProvider, v))
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.MediaSegment {
	return predicate.MediaSegment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.Item) predicate.MediaSegment {
	return predicate.MediaSegment(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaSegment) predicate.MediaSegment {
	return predicate.MediaSegment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaSegment) predicate.MediaSegment {
	return predicate.MediaSegment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaSegment) predicate.MediaSegment {
	return predicate.MediaSegment(sql.NotPredicates(p))
}
