// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/credit"
	"github.com/mavioai/mavio/libs/store/internal/ent/item"
	"github.com/mavioai/mavio/libs/store/internal/ent/person"
)

// CreditCreate is the builder for creating a Credit entity.
type CreditCreate struct {
	config
	mutation *CreditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetItemID sets the "item_id" field.
func (_c *CreditCreate) SetItemID(v core.ID) *CreditCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetPersonID sets the "person_id" field.
func (_c *CreditCreate) SetPersonID(v core.ID) *CreditCreate {
	_c.mutation.SetPersonID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *CreditCreate) SetKind(v string) *CreditCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *CreditCreate) SetRole(v string) *CreditCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *CreditCreate) SetNillableRole(v *string) *CreditCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetOrd sets the "ord" field.
func (_c *CreditCreate) SetOrd(v int) *CreditCreate {
	_c.mutation.SetOrd(v)
	return _c
}

// SetNillableOrd sets the "ord" field if the given value is not nil.
func (_c *CreditCreate) SetNillableOrd(v *int) *CreditCreate {
	if v != nil {
		_c.SetOrd(*v)
	}
	return _c
}

// SetItem sets the "item" edge to the Item entity.
func (_c *CreditCreate) SetItem(v *Item) *CreditCreate {
	return _c.SetItemID(v.ID)
}

// SetPerson sets the "person" edge to the Person entity.
func (_c *CreditCreate) SetPerson(v *Person) *CreditCreate {
	return _c.SetPersonID(v.ID)
}

// Mutation returns the CreditMutation object of the builder.
func (_c *CreditCreate) Mutation() *CreditMutation {
	return _c.mutation
}

// Save creates the Credit in the database.
func (_c *CreditCreate) Save(ctx context.Context) (*Credit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreditCreate) SaveX(ctx context.Context) *Credit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreditCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := credit.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Ord(); !ok {
		v := credit.DefaultOrd
		_c.mutation.SetOrd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreditCreate) check() error {
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "Credit.item_id"`)}
	}
	if _, ok := _c.mutation.PersonID(); !ok {
		return &ValidationError{Name: "person_id", err: errors.New(`ent: missing required field "Credit.person_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Credit.kind"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Credit.role"`)}
	}
	if _, ok := _c.mutation.Ord(); !ok {
		return &ValidationError{Name: "ord", err: errors.New(`ent: missing required field "Credit.ord"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "Credit.item"`)}
	}
	if len(_c.mutation.PersonIDs()) == 0 {
		return &ValidationError{Name: "person", err: errors.New(`ent: missing required edge "Credit.person"`)}
	}
	return nil
}

func (_c *CreditCreate) sqlSave(ctx context.Context) (*Credit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreditCreate) createSpec() (*Credit, *sqlgraph.CreateSpec) {
	var (
		_node = &Credit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(credit.Table, sqlgraph.NewFieldSpec(credit.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(credit.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(credit.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Ord(); ok {
		_spec.SetField(credit.FieldOrd, field.TypeInt, value)
		_node.Ord = value
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credit.ItemTable,
			Columns: []string{credit.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   credit.PersonTable,
			Columns: []string{credit.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PersonID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Credit.Create().
//		SetItemID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditCreate) OnConflict(opts ...sql.ConflictOption) *CreditUpsertOne {
	_c.conflict = opts
	return &CreditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Credit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditCreate) OnConflictColumns(columns ...string) *CreditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditUpsertOne{
		create: _c,
	}
}

type (
	// CreditUpsertOne is the builder for "upsert"-ing
	//  one Credit node.
	CreditUpsertOne struct {
		create *CreditCreate
	}

	// CreditUpsert is the "OnConflict" setter.
	CreditUpsert struct {
		*sql.UpdateSet
	}
)

// SetItemID sets the "item_id" field.
func (u *CreditUpsert) SetItemID(v core.ID) *CreditUpsert {
	u.Set(credit.FieldItemID, v)
	return u
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *CreditUpsert) UpdateItemID() *CreditUpsert {
	u.SetExcluded(credit.FieldItemID)
	return u
}

// SetPersonID sets the "person_id" field.
func (u *CreditUpsert) SetPersonID(v core.ID) *CreditUpsert {
	u.Set(credit.FieldPersonID, v)
	return u
}

// UpdatePersonID sets the "person_id" field to the value that was provided on create.
func (u *CreditUpsert) UpdatePersonID() *CreditUpsert {
	u.SetExcluded(credit.FieldPersonID)
	return u
}

// SetKind sets the "kind" field.
func (u *CreditUpsert) SetKind(v string) *CreditUpsert {
	u.Set(credit.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *CreditUpsert) UpdateKind() *CreditUpsert {
	u.SetExcluded(credit.FieldKind)
	return u
}

// SetRole sets the "role" field.
func (u *CreditUpsert) SetRole(v string) *CreditUpsert {
	u.Set(credit.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *CreditUpsert) UpdateRole() *CreditUpsert {
	u.SetExcluded(credit.FieldRole)
	return u
}

// SetOrd sets the "ord" field.
func (u *CreditUpsert) SetOrd(v int) *CreditUpsert {
	u.Set(credit.FieldOrd, v)
	return u
}

// UpdateOrd sets the "ord" field to the value that was provided on create.
func (u *CreditUpsert) UpdateOrd() *CreditUpsert {
	u.SetExcluded(credit.FieldOrd)
	return u
}

// AddOrd adds v to the "ord" field.
func (u *CreditUpsert) AddOrd(v int) *CreditUpsert {
	u.Add(credit.FieldOrd, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Credit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreditUpsertOne) UpdateNewValues() *CreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Credit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreditUpsertOne) Ignore() *CreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditUpsertOne) DoNothing() *CreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditCreate.OnConflict
// documentation for more info.
func (u *CreditUpsertOne) Update(set func(*CreditUpsert)) *CreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *CreditUpsertOne) SetItemID(v core.ID) *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *CreditUpsertOne) UpdateItemID() *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.UpdateItemID()
	})
}

// SetPersonID sets the "person_id" field.
func (u *CreditUpsertOne) SetPersonID(v core.ID) *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.SetPersonID(v)
	})
}

// UpdatePersonID sets the "person_id" field to the value that was provided on create.
func (u *CreditUpsertOne) UpdatePersonID() *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.UpdatePersonID()
	})
}

// SetKind sets the "kind" field.
func (u *CreditUpsertOne) SetKind(v string) *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *CreditUpsertOne) UpdateKind() *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.UpdateKind()
	})
}

// SetRole sets the "role" field.
func (u *CreditUpsertOne) SetRole(v string) *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *CreditUpsertOne) UpdateRole() *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.UpdateRole()
	})
}

// SetOrd sets the "ord" field.
func (u *CreditUpsertOne) SetOrd(v int) *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.SetOrd(v)
	})
}

// AddOrd adds v to the "ord" field.
func (u *CreditUpsertOne) AddOrd(v int) *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.AddOrd(v)
	})
}

// UpdateOrd sets the "ord" field to the value that was provided on create.
func (u *CreditUpsertOne) UpdateOrd() *CreditUpsertOne {
	return u.Update(func(s *CreditUpsert) {
		s.UpdateOrd()
	})
}

// Exec executes the query.
func (u *CreditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreditUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreditUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreditCreateBulk is the builder for creating many Credit entities in bulk.
type CreditCreateBulk struct {
	config
	err      error
	builders []*CreditCreate
	conflict []sql.ConflictOption
}

// Save creates the Credit entities in the database.
func (_c *CreditCreateBulk) Save(ctx context.Context) ([]*Credit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Credit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreditCreateBulk) SaveX(ctx context.Context) []*Credit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Credit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreditUpsertBulk {
	_c.conflict = opts
	return &CreditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Credit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditCreateBulk) OnConflictColumns(columns ...string) *CreditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditUpsertBulk{
		create: _c,
	}
}

// CreditUpsertBulk is the builder for "upsert"-ing
// a bulk of Credit nodes.
type CreditUpsertBulk struct {
	create *CreditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Credit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreditUpsertBulk) UpdateNewValues() *CreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Credit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreditUpsertBulk) Ignore() *CreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditUpsertBulk) DoNothing() *CreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditCreateBulk.OnConflict
// documentation for more info.
func (u *CreditUpsertBulk) Update(set func(*CreditUpsert)) *CreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *CreditUpsertBulk) SetItemID(v core.ID) *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *CreditUpsertBulk) UpdateItemID() *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.UpdateItemID()
	})
}

// SetPersonID sets the "person_id" field.
func (u *CreditUpsertBulk) SetPersonID(v core.ID) *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.SetPersonID(v)
	})
}

// UpdatePersonID sets the "person_id" field to the value that was provided on create.
func (u *CreditUpsertBulk) UpdatePersonID() *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.UpdatePersonID()
	})
}

// SetKind sets the "kind" field.
func (u *CreditUpsertBulk) SetKind(v string) *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *CreditUpsertBulk) UpdateKind() *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.UpdateKind()
	})
}

// SetRole sets the "role" field.
func (u *CreditUpsertBulk) SetRole(v string) *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *CreditUpsertBulk) UpdateRole() *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.UpdateRole()
	})
}

// SetOrd sets the "ord" field.
func (u *CreditUpsertBulk) SetOrd(v int) *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.SetOrd(v)
	})
}

// AddOrd adds v to the "ord" field.
func (u *CreditUpsertBulk) AddOrd(v int) *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.AddOrd(v)
	})
}

// UpdateOrd sets the "ord" field to the value that was provided on create.
func (u *CreditUpsertBulk) UpdateOrd() *CreditUpsertBulk {
	return u.Update(func(s *CreditUpsert) {
		s.UpdateOrd()
	})
}

// Exec executes the query.
func (u *CreditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CreditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
