// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/displaypreferences"
	"github.com/mavioai/mavio/libs/store/internal/ent/user"
)

// DisplayPreferencesCreate is the builder for creating a DisplayPreferences entity.
type DisplayPreferencesCreate struct {
	config
	mutation *DisplayPreferencesMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *DisplayPreferencesCreate) SetUserID(v core.ID) *DisplayPreferencesCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetClient sets the "client" field.
func (_c *DisplayPreferencesCreate) SetClient(v string) *DisplayPreferencesCreate {
	_c.mutation.SetClient(v)
	return _c
}

// SetView sets the "view" field.
func (_c *DisplayPreferencesCreate) SetView(v string) *DisplayPreferencesCreate {
	_c.mutation.SetView(v)
	return _c
}

// SetValues sets the "values" field.
func (_c *DisplayPreferencesCreate) SetValues(v map[string]string) *DisplayPreferencesCreate {
	_c.mutation.SetValues(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DisplayPreferencesCreate) SetUpdatedAt(v time.Time) *DisplayPreferencesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DisplayPreferencesCreate) SetNillableUpdatedAt(v *time.Time) *DisplayPreferencesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DisplayPreferencesCreate) SetID(v core.ID) *DisplayPreferencesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DisplayPreferencesCreate) SetNillableID(v *core.ID) *DisplayPreferencesCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *DisplayPreferencesCreate) SetUser(v *User) *DisplayPreferencesCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the DisplayPreferencesMutation object of the builder.
func (_c *DisplayPreferencesCreate) Mutation() *DisplayPreferencesMutation {
	return _c.mutation
}

// Save creates the DisplayPreferences in the database.
func (_c *DisplayPreferencesCreate) Save(ctx context.Context) (*DisplayPreferences, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DisplayPreferencesCreate) SaveX(ctx context.Context) *DisplayPreferences {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DisplayPreferencesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DisplayPreferencesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DisplayPreferencesCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := displaypreferences.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := displaypreferences.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DisplayPreferencesCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DisplayPreferences.user_id"`)}
	}
	if _, ok := _c.mutation.GetClient(); !ok {
		return &ValidationError{Name: "client", err: errors.New(`ent: missing required field "DisplayPreferences.client"`)}
	}
	if _, ok := _c.mutation.View(); !ok {
		return &ValidationError{Name: "view", err: errors.New(`ent: missing required field "DisplayPreferences.view"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DisplayPreferences.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DisplayPreferences.user"`)}
	}
	return nil
}

func (_c *DisplayPreferencesCreate) sqlSave(ctx context.Context) (*DisplayPreferences, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*core.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DisplayPreferencesCreate) createSpec() (*DisplayPreferences, *sqlgraph.CreateSpec) {
	var (
		_node = &DisplayPreferences{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(displaypreferences.Table, sqlgraph.NewFieldSpec(displaypreferences.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetClient(); ok {
		_spec.SetField(displaypreferences.FieldClient, field.TypeString, value)
		_node.Client = value
	}
	if value, ok := _c.mutation.View(); ok {
		_spec.SetField(displaypreferences.FieldView, field.TypeString, value)
		_node.View = value
	}
	if value, ok := _c.mutation.Values(); ok {
		_spec.SetField(displaypreferences.FieldValues, field.TypeJSON, value)
		_node.Values = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(displaypreferences.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   displaypreferences.UserTable,
			Columns: []string{displaypreferences.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DisplayPreferences.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DisplayPreferencesUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *DisplayPreferencesCreate) OnConflict(opts ...sql.ConflictOption) *DisplayPreferencesUpsertOne {
	_c.conflict = opts
	return &DisplayPreferencesUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DisplayPreferences.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DisplayPreferencesCreate) OnConflictColumns(columns ...string) *DisplayPreferencesUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DisplayPreferencesUpsertOne{
		create: _c,
	}
}

type (
	// DisplayPreferencesUpsertOne is the builder for "upsert"-ing
	//  one DisplayPreferences node.
	DisplayPreferencesUpsertOne struct {
		create *DisplayPreferencesCreate
	}

	// DisplayPreferencesUpsert is the "OnConflict" setter.
	DisplayPreferencesUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *DisplayPreferencesUpsert) SetUserID(v core.ID) *DisplayPreferencesUpsert {
	u.Set(displaypreferences.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DisplayPreferencesUpsert) UpdateUserID() *DisplayPreferencesUpsert {
	u.SetExcluded(displaypreferences.FieldUserID)
	return u
}

// SetClient sets the "client" field.
func (u *DisplayPreferencesUpsert) SetClient(v string) *DisplayPreferencesUpsert {
	u.Set(displaypreferences.FieldClient, v)
	return u
}

// UpdateClient sets the "client" field to the value that was provided on create.
func (u *DisplayPreferencesUpsert) UpdateClient() *DisplayPreferencesUpsert {
	u.SetExcluded(displaypreferences.FieldClient)
	return u
}

// SetView sets the "view" field.
func (u *DisplayPreferencesUpsert) SetView(v string) *DisplayPreferencesUpsert {
	u.Set(displaypreferences.FieldView, v)
	return u
}

// UpdateView sets the "view" field to the value that was provided on create.
func (u *DisplayPreferencesUpsert) UpdateView() *DisplayPreferencesUpsert {
	u.SetExcluded(displaypreferences.FieldView)
	return u
}

// SetValues sets the "values" field.
func (u *DisplayPreferencesUpsert) SetValues(v map[string]string) *DisplayPreferencesUpsert {
	u.Set(displaypreferences.FieldValues, v)
	return u
}

// UpdateValues sets the "values" field to the value that was provided on create.
func (u *DisplayPreferencesUpsert) UpdateValues() *DisplayPreferencesUpsert {
	u.SetExcluded(displaypreferences.FieldValues)
	return u
}

// ClearValues clears the value of the "values" field.
func (u *DisplayPreferencesUpsert) ClearValues() *DisplayPreferencesUpsert {
	u.SetNull(displaypreferences.FieldValues)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DisplayPreferencesUpsert) SetUpdatedAt(v time.Time) *DisplayPreferencesUpsert {
	u.Set(displaypreferences.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DisplayPreferencesUpsert) UpdateUpdatedAt() *DisplayPreferencesUpsert {
	u.SetExcluded(displaypreferences.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DisplayPreferences.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(displaypreferences.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DisplayPreferencesUpsertOne) UpdateNewValues() *DisplayPreferencesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(displaypreferences.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DisplayPreferences.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DisplayPreferencesUpsertOne) Ignore() *DisplayPreferencesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DisplayPreferencesUpsertOne) DoNothing() *DisplayPreferencesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DisplayPreferencesCreate.OnConflict
// documentation for more info.
func (u *DisplayPreferencesUpsertOne) Update(set func(*DisplayPreferencesUpsert)) *DisplayPreferencesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DisplayPreferencesUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *DisplayPreferencesUpsertOne) SetUserID(v core.ID) *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertOne) UpdateUserID() *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateUserID()
	})
}

// SetClient sets the "client" field.
func (u *DisplayPreferencesUpsertOne) SetClient(v string) *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetClient(v)
	})
}

// UpdateClient sets the "client" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertOne) UpdateClient() *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateClient()
	})
}

// SetView sets the "view" field.
func (u *DisplayPreferencesUpsertOne) SetView(v string) *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetView(v)
	})
}

// UpdateView sets the "view" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertOne) UpdateView() *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateView()
	})
}

// SetValues sets the "values" field.
func (u *DisplayPreferencesUpsertOne) SetValues(v map[string]string) *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetValues(v)
	})
}

// UpdateValues sets the "values" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertOne) UpdateValues() *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateValues()
	})
}

// ClearValues clears the value of the "values" field.
func (u *DisplayPreferencesUpsertOne) ClearValues() *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.ClearValues()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DisplayPreferencesUpsertOne) SetUpdatedAt(v time.Time) *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertOne) UpdateUpdatedAt() *DisplayPreferencesUpsertOne {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DisplayPreferencesUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DisplayPreferencesCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DisplayPreferencesUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DisplayPreferencesUpsertOne) ID(ctx context.Context) (id core.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DisplayPreferencesUpsertOne.ID is not supported by MySQL driver. Use DisplayPreferencesUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DisplayPreferencesUpsertOne) IDX(ctx context.Context) core.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DisplayPreferencesCreateBulk is the builder for creating many DisplayPreferences entities in bulk.
type DisplayPreferencesCreateBulk struct {
	config
	err      error
	builders []*DisplayPreferencesCreate
	conflict []sql.ConflictOption
}

// Save creates the DisplayPreferences entities in the database.
func (_c *DisplayPreferencesCreateBulk) Save(ctx context.Context) ([]*DisplayPreferences, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DisplayPreferences, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DisplayPreferencesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DisplayPreferencesCreateBulk) SaveX(ctx context.Context) []*DisplayPreferences {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DisplayPreferencesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DisplayPreferencesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DisplayPreferences.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DisplayPreferencesUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *DisplayPreferencesCreateBulk) OnConflict(opts ...sql.ConflictOption) *DisplayPreferencesUpsertBulk {
	_c.conflict = opts
	return &DisplayPreferencesUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DisplayPreferences.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DisplayPreferencesCreateBulk) OnConflictColumns(columns ...string) *DisplayPreferencesUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DisplayPreferencesUpsertBulk{
		create: _c,
	}
}

// DisplayPreferencesUpsertBulk is the builder for "upsert"-ing
// a bulk of DisplayPreferences nodes.
type DisplayPreferencesUpsertBulk struct {
	create *DisplayPreferencesCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DisplayPreferences.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(displaypreferences.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DisplayPreferencesUpsertBulk) UpdateNewValues() *DisplayPreferencesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(displaypreferences.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DisplayPreferences.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DisplayPreferencesUpsertBulk) Ignore() *DisplayPreferencesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DisplayPreferencesUpsertBulk) DoNothing() *DisplayPreferencesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DisplayPreferencesCreateBulk.OnConflict
// documentation for more info.
func (u *DisplayPreferencesUpsertBulk) Update(set func(*DisplayPreferencesUpsert)) *DisplayPreferencesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DisplayPreferencesUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *DisplayPreferencesUpsertBulk) SetUserID(v core.ID) *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertBulk) UpdateUserID() *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateUserID()
	})
}

// SetClient sets the "client" field.
func (u *DisplayPreferencesUpsertBulk) SetClient(v string) *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetClient(v)
	})
}

// UpdateClient sets the "client" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertBulk) UpdateClient() *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateClient()
	})
}

// SetView sets the "view" field.
func (u *DisplayPreferencesUpsertBulk) SetView(v string) *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetView(v)
	})
}

// UpdateView sets the "view" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertBulk) UpdateView() *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateView()
	})
}

// SetValues sets the "values" field.
func (u *DisplayPreferencesUpsertBulk) SetValues(v map[string]string) *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetValues(v)
	})
}

// UpdateValues sets the "values" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertBulk) UpdateValues() *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateValues()
	})
}

// ClearValues clears the value of the "values" field.
func (u *DisplayPreferencesUpsertBulk) ClearValues() *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.ClearValues()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DisplayPreferencesUpsertBulk) SetUpdatedAt(v time.Time) *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DisplayPreferencesUpsertBulk) UpdateUpdatedAt() *DisplayPreferencesUpsertBulk {
	return u.Update(func(s *DisplayPreferencesUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DisplayPreferencesUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DisplayPreferencesCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DisplayPreferencesCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DisplayPreferencesUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
