// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/folderstate"
	"github.com/mavioai/mavio/libs/store/internal/ent/library"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
)

// FolderStateQuery is the builder for querying FolderState entities.
type FolderStateQuery struct {
	config
	ctx         *QueryContext
	order       []folderstate.OrderOption
	inters      []Interceptor
	predicates  []predicate.FolderState
	withLibrary *LibraryQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FolderStateQuery builder.
func (_q *FolderStateQuery) Where(ps ...predicate.FolderState) *FolderStateQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FolderStateQuery) Limit(limit int) *FolderStateQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FolderStateQuery) Offset(offset int) *FolderStateQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FolderStateQuery) Unique(unique bool) *FolderStateQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FolderStateQuery) Order(o ...folderstate.OrderOption) *FolderStateQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLibrary chains the current query on the "library" edge.
func (_q *FolderStateQuery) QueryLibrary() *LibraryQuery {
	query := (&LibraryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(folderstate.Table, folderstate.FieldID, selector),
			sqlgraph.To(library.Table, library.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, folderstate.LibraryTable, folderstate.LibraryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FolderState entity from the query.
// Returns a *NotFoundError when no FolderState was found.
func (_q *FolderStateQuery) First(ctx context.Context) (*FolderState, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{folderstate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FolderStateQuery) FirstX(ctx context.Context) *FolderState {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FolderState ID from the query.
// Returns a *NotFoundError when no FolderState ID was found.
func (_q *FolderStateQuery) FirstID(ctx context.Context) (id core.ID, err error) {
	var ids []core.ID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{folderstate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FolderStateQuery) FirstIDX(ctx context.Context) core.ID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FolderState entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FolderState entity is found.
// Returns a *NotFoundError when no FolderState entities are found.
func (_q *FolderStateQuery) Only(ctx context.Context) (*FolderState, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{folderstate.Label}
	default:
		return nil, &NotSingularError{folderstate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FolderStateQuery) OnlyX(ctx context.Context) *FolderState {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FolderState ID in the query.
// Returns a *NotSingularError when more than one FolderState ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FolderStateQuery) OnlyID(ctx context.Context) (id core.ID, err error) {
	var ids []core.ID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{folderstate.Label}
	default:
		err = &NotSingularError{folderstate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FolderStateQuery) OnlyIDX(ctx context.Context) core.ID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FolderStates.
func (_q *FolderStateQuery) All(ctx context.Context) ([]*FolderState, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FolderState, *FolderStateQuery]()
	return withInterceptors[[]*FolderState](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FolderStateQuery) AllX(ctx context.Context) []*FolderState {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FolderState IDs.
func (_q *FolderStateQuery) IDs(ctx context.Context) (ids []core.ID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(folderstate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FolderStateQuery) IDsX(ctx context.Context) []core.ID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FolderStateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FolderStateQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FolderStateQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FolderStateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FolderStateQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FolderStateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FolderStateQuery) Clone() *FolderStateQuery {
	if _q == nil {
		return nil
	}
	return &FolderStateQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]folderstate.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.FolderState{}, _q.predicates...),
		withLibrary: _q.withLibrary.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithLibrary tells the query-builder to eager-load the nodes that are connected to
// the "library" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FolderStateQuery) WithLibrary(opts ...func(*LibraryQuery)) *FolderStateQuery {
	query := (&LibraryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLibrary = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LibraryID core.ID `json:"library_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FolderState.Query().
//		GroupBy(folderstate.FieldLibraryID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FolderStateQuery) GroupBy(field string, fields ...string) *FolderStateGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FolderStateGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = folderstate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LibraryID core.ID `json:"library_id,omitempty"`
//	}
//
//	client.FolderState.Query().
//		Select(folderstate.FieldLibraryID).
//		Scan(ctx, &v)
func (_q *FolderStateQuery) Select(fields ...string) *FolderStateSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FolderStateSelect{FolderStateQuery: _q}
	sbuild.label = folderstate.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FolderStateSelect configured with the given aggregations.
func (_q *FolderStateQuery) Aggregate(fns ...AggregateFunc) *FolderStateSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FolderStateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !folderstate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FolderStateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FolderState, error) {
	var (
		nodes       = []*FolderState{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withLibrary != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FolderState).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FolderState{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLibrary; query != nil {
		if err := _q.loadLibrary(ctx, query, nodes, nil,
			func(n *FolderState, e *Library) { n.Edges.Library = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FolderStateQuery) loadLibrary(ctx context.Context, query *LibraryQuery, nodes []*FolderState, init func(*FolderState), assign func(*FolderState, *Library)) error {
	ids := make([]core.ID, 0, len(nodes))
	nodeids := make(map[core.ID][]*FolderState)
	for i := range nodes {
		fk := nodes[i].LibraryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(library.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "library_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *FolderStateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FolderStateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(folderstate.Table, folderstate.Columns, sqlgraph.NewFieldSpec(folderstate.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, folderstate.FieldID)
		for i := range fields {
			if fields[i] != folderstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withLibrary != nil {
			_spec.Node.AddColumnOnce(folderstate.FieldLibraryID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FolderStateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(folderstate.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = folderstate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *FolderStateQuery) Modify(modifiers ...func(s *sql.Selector)) *FolderStateSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// FolderStateGroupBy is the group-by builder for FolderState entities.
type FolderStateGroupBy struct {
	selector
	build *FolderStateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FolderStateGroupBy) Aggregate(fns ...AggregateFunc) *FolderStateGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FolderStateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FolderStateQuery, *FolderStateGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FolderStateGroupBy) sqlScan(ctx context.Context, root *FolderStateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FolderStateSelect is the builder for selecting fields of FolderState entities.
type FolderStateSelect struct {
	*FolderStateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FolderStateSelect) Aggregate(fns ...AggregateFunc) *FolderStateSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FolderStateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FolderStateQuery, *FolderStateSelect](ctx, _s.FolderStateQuery, _s, _s.inters, v)
}

func (_s *FolderStateSelect) sqlScan(ctx context.Context, root *FolderStateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *FolderStateSelect) Modify(modifiers ...func(s *sql.Selector)) *FolderStateSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
