// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/image"
	"github.com/mavioai/mavio/libs/store/internal/ent/item"
	"github.com/mavioai/mavio/libs/store/internal/ent/person"
)

// ImageCreate is the builder for creating a Image entity.
type ImageCreate struct {
	config
	mutation *ImageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetItemID sets the "item_id" field.
func (_c *ImageCreate) SetItemID(v core.ID) *ImageCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_c *ImageCreate) SetNillableItemID(v *core.ID) *ImageCreate {
	if v != nil {
		_c.SetItemID(*v)
	}
	return _c
}

// SetPersonID sets the "person_id" field.
func (_c *ImageCreate) SetPersonID(v core.ID) *ImageCreate {
	_c.mutation.SetPersonID(v)
	return _c
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_c *ImageCreate) SetNillablePersonID(v *core.ID) *ImageCreate {
	if v != nil {
		_c.SetPersonID(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *ImageCreate) SetKind(v string) *ImageCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetIndex sets the "index" field.
func (_c *ImageCreate) SetIndex(v int) *ImageCreate {
	_c.mutation.SetIndex(v)
	return _c
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_c *ImageCreate) SetNillableIndex(v *int) *ImageCreate {
	if v != nil {
		_c.SetIndex(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *ImageCreate) SetPath(v string) *ImageCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *ImageCreate) SetNillablePath(v *string) *ImageCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetRemoteURL sets the "remote_url" field.
func (_c *ImageCreate) SetRemoteURL(v string) *ImageCreate {
	_c.mutation.SetRemoteURL(v)
	return _c
}

// SetNillableRemoteURL sets the "remote_url" field if the given value is not nil.
func (_c *ImageCreate) SetNillableRemoteURL(v *string) *ImageCreate {
	if v != nil {
		_c.SetRemoteURL(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *ImageCreate) SetWidth(v int) *ImageCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *ImageCreate) SetNillableWidth(v *int) *ImageCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *ImageCreate) SetHeight(v int) *ImageCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *ImageCreate) SetNillableHeight(v *int) *ImageCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetBlurhash sets the "blurhash" field.
func (_c *ImageCreate) SetBlurhash(v string) *ImageCreate {
	_c.mutation.SetBlurhash(v)
	return _c
}

// SetNillableBlurhash sets the "blurhash" field if the given value is not nil.
func (_c *ImageCreate) SetNillableBlurhash(v *string) *ImageCreate {
	if v != nil {
		_c.SetBlurhash(*v)
	}
	return _c
}

// SetThumbhash sets the "thumbhash" field.
func (_c *ImageCreate) SetThumbhash(v []byte) *ImageCreate {
	_c.mutation.SetThumbhash(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ImageCreate) SetID(v core.ID) *ImageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ImageCreate) SetNillableID(v *core.ID) *ImageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetItem sets the "item" edge to the Item entity.
func (_c *ImageCreate) SetItem(v *Item) *ImageCreate {
	return _c.SetItemID(v.ID)
}

// SetPerson sets the "person" edge to the Person entity.
func (_c *ImageCreate) SetPerson(v *Person) *ImageCreate {
	return _c.SetPersonID(v.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (_c *ImageCreate) Mutation() *ImageMutation {
	return _c.mutation
}

// Save creates the Image in the database.
func (_c *ImageCreate) Save(ctx context.Context) (*Image, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageCreate) SaveX(ctx context.Context) *Image {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageCreate) defaults() {
	if _, ok := _c.mutation.Index(); !ok {
		v := image.DefaultIndex
		_c.mutation.SetIndex(v)
	}
	if _, ok := _c.mutation.Path(); !ok {
		v := image.DefaultPath
		_c.mutation.SetPath(v)
	}
	if _, ok := _c.mutation.RemoteURL(); !ok {
		v := image.DefaultRemoteURL
		_c.mutation.SetRemoteURL(v)
	}
	if _, ok := _c.mutation.Width(); !ok {
		v := image.DefaultWidth
		_c.mutation.SetWidth(v)
	}
	if _, ok := _c.mutation.Height(); !ok {
		v := image.DefaultHeight
		_c.mutation.SetHeight(v)
	}
	if _, ok := _c.mutation.Blurhash(); !ok {
		v := image.DefaultBlurhash
		_c.mutation.SetBlurhash(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := image.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Image.kind"`)}
	}
	if _, ok := _c.mutation.Index(); !ok {
		return &ValidationError{Name: "index", err: errors.New(`ent: missing required field "Image.index"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Image.path"`)}
	}
	if _, ok := _c.mutation.RemoteURL(); !ok {
		return &ValidationError{Name: "remote_url", err: errors.New(`ent: missing required field "Image.remote_url"`)}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "Image.width"`)}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "Image.height"`)}
	}
	if _, ok := _c.mutation.Blurhash(); !ok {
		return &ValidationError{Name: "blurhash", err: errors.New(`ent: missing required field "Image.blurhash"`)}
	}
	return nil
}

func (_c *ImageCreate) sqlSave(ctx context.Context) (*Image, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*core.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageCreate) createSpec() (*Image, *sqlgraph.CreateSpec) {
	var (
		_node = &Image{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(image.Table, sqlgraph.NewFieldSpec(image.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(image.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Index(); ok {
		_spec.SetField(image.FieldIndex, field.TypeInt, value)
		_node.Index = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(image.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.RemoteURL(); ok {
		_spec.SetField(image.FieldRemoteURL, field.TypeString, value)
		_node.RemoteURL = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(image.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(image.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Blurhash(); ok {
		_spec.SetField(image.FieldBlurhash, field.TypeString, value)
		_node.Blurhash = value
	}
	if value, ok := _c.mutation.Thumbhash(); ok {
		_spec.SetField(image.FieldThumbhash, field.TypeBytes, value)
		_node.Thumbhash = value
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.ItemTable,
			Columns: []string{image.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.PersonTable,
			Columns: []string{image.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PersonID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Image.Create().
//		SetItemID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageCreate) OnConflict(opts ...sql.ConflictOption) *ImageUpsertOne {
	_c.conflict = opts
	return &ImageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Image.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageCreate) OnConflictColumns(columns ...string) *ImageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageUpsertOne{
		create: _c,
	}
}

type (
	// ImageUpsertOne is the builder for "upsert"-ing
	//  one Image node.
	ImageUpsertOne struct {
		create *ImageCreate
	}

	// ImageUpsert is the "OnConflict" setter.
	ImageUpsert struct {
		*sql.UpdateSet
	}
)

// SetItemID sets the "item_id" field.
func (u *ImageUpsert) SetItemID(v core.ID) *ImageUpsert {
	u.Set(image.FieldItemID, v)
	return u
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ImageUpsert) UpdateItemID() *ImageUpsert {
	u.SetExcluded(image.FieldItemID)
	return u
}

// ClearItemID clears the value of the "item_id" field.
func (u *ImageUpsert) ClearItemID() *ImageUpsert {
	u.SetNull(image.FieldItemID)
	return u
}

// SetPersonID sets the "person_id" field.
func (u *ImageUpsert) SetPersonID(v core.ID) *ImageUpsert {
	u.Set(image.FieldPersonID, v)
	return u
}

// UpdatePersonID sets the "person_id" field to the value that was provided on create.
func (u *ImageUpsert) UpdatePersonID() *ImageUpsert {
	u.SetExcluded(image.FieldPersonID)
	return u
}

// ClearPersonID clears the value of the "person_id" field.
func (u *ImageUpsert) ClearPersonID() *ImageUpsert {
	u.SetNull(image.FieldPersonID)
	return u
}

// SetKind sets the "kind" field.
func (u *ImageUpsert) SetKind(v string) *ImageUpsert {
	u.Set(image.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ImageUpsert) UpdateKind() *ImageUpsert {
	u.SetExcluded(image.FieldKind)
	return u
}

// SetIndex sets the "index" field.
func (u *ImageUpsert) SetIndex(v int) *ImageUpsert {
	u.Set(image.FieldIndex, v)
	return u
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *ImageUpsert) UpdateIndex() *ImageUpsert {
	u.SetExcluded(image.FieldIndex)
	return u
}

// AddIndex adds v to the "index" field.
func (u *ImageUpsert) AddIndex(v int) *ImageUpsert {
	u.Add(image.FieldIndex, v)
	return u
}

// SetPath sets the "path" field.
func (u *ImageUpsert) SetPath(v string) *ImageUpsert {
	u.Set(image.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ImageUpsert) UpdatePath() *ImageUpsert {
	u.SetExcluded(image.FieldPath)
	return u
}

// SetRemoteURL sets the "remote_url" field.
func (u *ImageUpsert) SetRemoteURL(v string) *ImageUpsert {
	u.Set(image.FieldRemoteURL, v)
	return u
}

// UpdateRemoteURL sets the "remote_url" field to the value that was provided on create.
func (u *ImageUpsert) UpdateRemoteURL() *ImageUpsert {
	u.SetExcluded(image.FieldRemoteURL)
	return u
}

// SetWidth sets the "width" field.
func (u *ImageUpsert) SetWidth(v int) *ImageUpsert {
	u.Set(image.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageUpsert) UpdateWidth() *ImageUpsert {
	u.SetExcluded(image.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *ImageUpsert) AddWidth(v int) *ImageUpsert {
	u.Add(image.FieldWidth, v)
	return u
}

// SetHeight sets the "height" field.
func (u *ImageUpsert) SetHeight(v int) *ImageUpsert {
	u.Set(image.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageUpsert) UpdateHeight() *ImageUpsert {
	u.SetExcluded(image.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *ImageUpsert) AddHeight(v int) *ImageUpsert {
	u.Add(image.FieldHeight, v)
	return u
}

// SetBlurhash sets the "blurhash" field.
func (u *ImageUpsert) SetBlurhash(v string) *ImageUpsert {
	u.Set(image.FieldBlurhash, v)
	return u
}

// UpdateBlurhash sets the "blurhash" field to the value that was provided on create.
func (u *ImageUpsert) UpdateBlurhash() *ImageUpsert {
	u.SetExcluded(image.FieldBlurhash)
	return u
}

// SetThumbhash sets the "thumbhash" field.
func (u *ImageUpsert) SetThumbhash(v []byte) *ImageUpsert {
	u.Set(image.FieldThumbhash, v)
	return u
}

// UpdateThumbhash sets the "thumbhash" field to the value that was provided on create.
func (u *ImageUpsert) UpdateThumbhash() *ImageUpsert {
	u.SetExcluded(image.FieldThumbhash)
	return u
}

// ClearThumbhash clears the value of the "thumbhash" field.
func (u *ImageUpsert) ClearThumbhash() *ImageUpsert {
	u.SetNull(image.FieldThumbhash)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Image.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(image.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImageUpsertOne) UpdateNewValues() *ImageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(image.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Image.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageUpsertOne) Ignore() *ImageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageUpsertOne) DoNothing() *ImageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageCreate.OnConflict
// documentation for more info.
func (u *ImageUpsertOne) Update(set func(*ImageUpsert)) *ImageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *ImageUpsertOne) SetItemID(v core.ID) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdateItemID() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateItemID()
	})
}

// ClearItemID clears the value of the "item_id" field.
func (u *ImageUpsertOne) ClearItemID() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.ClearItemID()
	})
}

// SetPersonID sets the "person_id" field.
func (u *ImageUpsertOne) SetPersonID(v core.ID) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetPersonID(v)
	})
}

// UpdatePersonID sets the "person_id" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdatePersonID() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdatePersonID()
	})
}

// ClearPersonID clears the value of the "person_id" field.
func (u *ImageUpsertOne) ClearPersonID() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.ClearPersonID()
	})
}

// SetKind sets the "kind" field.
func (u *ImageUpsertOne) SetKind(v string) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdateKind() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateKind()
	})
}

// SetIndex sets the "index" field.
func (u *ImageUpsertOne) SetIndex(v int) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *ImageUpsertOne) AddIndex(v int) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdateIndex() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateIndex()
	})
}

// SetPath sets the "path" field.
func (u *ImageUpsertOne) SetPath(v string) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdatePath() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdatePath()
	})
}

// SetRemoteURL sets the "remote_url" field.
func (u *ImageUpsertOne) SetRemoteURL(v string) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetRemoteURL(v)
	})
}

// UpdateRemoteURL sets the "remote_url" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdateRemoteURL() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateRemoteURL()
	})
}

// SetWidth sets the "width" field.
func (u *ImageUpsertOne) SetWidth(v int) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageUpsertOne) AddWidth(v int) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdateWidth() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageUpsertOne) SetHeight(v int) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageUpsertOne) AddHeight(v int) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdateHeight() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateHeight()
	})
}

// SetBlurhash sets the "blurhash" field.
func (u *ImageUpsertOne) SetBlurhash(v string) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetBlurhash(v)
	})
}

// UpdateBlurhash sets the "blurhash" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdateBlurhash() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateBlurhash()
	})
}

// SetThumbhash sets the "thumbhash" field.
func (u *ImageUpsertOne) SetThumbhash(v []byte) *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.SetThumbhash(v)
	})
}

// UpdateThumbhash sets the "thumbhash" field to the value that was provided on create.
func (u *ImageUpsertOne) UpdateThumbhash() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateThumbhash()
	})
}

// ClearThumbhash clears the value of the "thumbhash" field.
func (u *ImageUpsertOne) ClearThumbhash() *ImageUpsertOne {
	return u.Update(func(s *ImageUpsert) {
		s.ClearThumbhash()
	})
}

// Exec executes the query.
func (u *ImageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageUpsertOne) ID(ctx context.Context) (id core.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ImageUpsertOne.ID is not supported by MySQL driver. Use ImageUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageUpsertOne) IDX(ctx context.Context) core.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageCreateBulk is the builder for creating many Image entities in bulk.
type ImageCreateBulk struct {
	config
	err      error
	builders []*ImageCreate
	conflict []sql.ConflictOption
}

// Save creates the Image entities in the database.
func (_c *ImageCreateBulk) Save(ctx context.Context) ([]*Image, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Image, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageCreateBulk) SaveX(ctx context.Context) []*Image {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Image.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageUpsertBulk {
	_c.conflict = opts
	return &ImageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Image.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageCreateBulk) OnConflictColumns(columns ...string) *ImageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageUpsertBulk{
		create: _c,
	}
}

// ImageUpsertBulk is the builder for "upsert"-ing
// a bulk of Image nodes.
type ImageUpsertBulk struct {
	create *ImageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Image.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(image.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImageUpsertBulk) UpdateNewValues() *ImageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(image.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Image.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageUpsertBulk) Ignore() *ImageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageUpsertBulk) DoNothing() *ImageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageCreateBulk.OnConflict
// documentation for more info.
func (u *ImageUpsertBulk) Update(set func(*ImageUpsert)) *ImageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *ImageUpsertBulk) SetItemID(v core.ID) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdateItemID() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateItemID()
	})
}

// ClearItemID clears the value of the "item_id" field.
func (u *ImageUpsertBulk) ClearItemID() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.ClearItemID()
	})
}

// SetPersonID sets the "person_id" field.
func (u *ImageUpsertBulk) SetPersonID(v core.ID) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetPersonID(v)
	})
}

// UpdatePersonID sets the "person_id" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdatePersonID() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdatePersonID()
	})
}

// ClearPersonID clears the value of the "person_id" field.
func (u *ImageUpsertBulk) ClearPersonID() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.ClearPersonID()
	})
}

// SetKind sets the "kind" field.
func (u *ImageUpsertBulk) SetKind(v string) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdateKind() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateKind()
	})
}

// SetIndex sets the "index" field.
func (u *ImageUpsertBulk) SetIndex(v int) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *ImageUpsertBulk) AddIndex(v int) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdateIndex() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateIndex()
	})
}

// SetPath sets the "path" field.
func (u *ImageUpsertBulk) SetPath(v string) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdatePath() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdatePath()
	})
}

// SetRemoteURL sets the "remote_url" field.
func (u *ImageUpsertBulk) SetRemoteURL(v string) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetRemoteURL(v)
	})
}

// UpdateRemoteURL sets the "remote_url" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdateRemoteURL() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateRemoteURL()
	})
}

// SetWidth sets the "width" field.
func (u *ImageUpsertBulk) SetWidth(v int) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageUpsertBulk) AddWidth(v int) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdateWidth() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageUpsertBulk) SetHeight(v int) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageUpsertBulk) AddHeight(v int) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdateHeight() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateHeight()
	})
}

// SetBlurhash sets the "blurhash" field.
func (u *ImageUpsertBulk) SetBlurhash(v string) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetBlurhash(v)
	})
}

// UpdateBlurhash sets the "blurhash" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdateBlurhash() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateBlurhash()
	})
}

// SetThumbhash sets the "thumbhash" field.
func (u *ImageUpsertBulk) SetThumbhash(v []byte) *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.SetThumbhash(v)
	})
}

// UpdateThumbhash sets the "thumbhash" field to the value that was provided on create.
func (u *ImageUpsertBulk) UpdateThumbhash() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.UpdateThumbhash()
	})
}

// ClearThumbhash clears the value of the "thumbhash" field.
func (u *ImageUpsertBulk) ClearThumbhash() *ImageUpsertBulk {
	return u.Update(func(s *ImageUpsert) {
		s.ClearThumbhash()
	})
}

// Exec executes the query.
func (u *ImageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
