// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/store/internal/ent/itemvalue"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
)

// ItemValueDelete is the builder for deleting a ItemValue entity.
type ItemValueDelete struct {
	config
	hooks    []Hook
	mutation *ItemValueMutation
}

// Where appends a list predicates to the ItemValueDelete builder.
func (_d *ItemValueDelete) Where(ps ...predicate.ItemValue) *ItemValueDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ItemValueDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ItemValueDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ItemValueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(itemvalue.Table, sqlgraph.NewFieldSpec(itemvalue.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ItemValueDeleteOne is the builder for deleting a single ItemValue entity.
type ItemValueDeleteOne struct {
	_d *ItemValueDelete
}

// Where appends a list predicates to the ItemValueDelete builder.
func (_d *ItemValueDeleteOne) Where(ps ...predicate.ItemValue) *ItemValueDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ItemValueDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{itemvalue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ItemValueDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
