// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/item"
	"github.com/mavioai/mavio/libs/store/internal/ent/itemlink"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
)

// ItemLinkUpdate is the builder for updating ItemLink entities.
type ItemLinkUpdate struct {
	config
	hooks     []Hook
	mutation  *ItemLinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ItemLinkUpdate builder.
func (_u *ItemLinkUpdate) Where(ps ...predicate.ItemLink) *ItemLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContainerID sets the "container_id" field.
func (_u *ItemLinkUpdate) SetContainerID(v core.ID) *ItemLinkUpdate {
	_u.mutation.SetContainerID(v)
	return _u
}

// SetNillableContainerID sets the "container_id" field if the given value is not nil.
func (_u *ItemLinkUpdate) SetNillableContainerID(v *core.ID) *ItemLinkUpdate {
	if v != nil {
		_u.SetContainerID(*v)
	}
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *ItemLinkUpdate) SetItemID(v core.ID) *ItemLinkUpdate {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *ItemLinkUpdate) SetNillableItemID(v *core.ID) *ItemLinkUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetOrd sets the "ord" field.
func (_u *ItemLinkUpdate) SetOrd(v int) *ItemLinkUpdate {
	_u.mutation.ResetOrd()
	_u.mutation.SetOrd(v)
	return _u
}

// SetNillableOrd sets the "ord" field if the given value is not nil.
func (_u *ItemLinkUpdate) SetNillableOrd(v *int) *ItemLinkUpdate {
	if v != nil {
		_u.SetOrd(*v)
	}
	return _u
}

// AddOrd adds value to the "ord" field.
func (_u *ItemLinkUpdate) AddOrd(v int) *ItemLinkUpdate {
	_u.mutation.AddOrd(v)
	return _u
}

// SetContainer sets the "container" edge to the Item entity.
func (_u *ItemLinkUpdate) SetContainer(v *Item) *ItemLinkUpdate {
	return _u.SetContainerID(v.ID)
}

// SetItem sets the "item" edge to the Item entity.
func (_u *ItemLinkUpdate) SetItem(v *Item) *ItemLinkUpdate {
	return _u.SetItemID(v.ID)
}

// Mutation returns the ItemLinkMutation object of the builder.
func (_u *ItemLinkUpdate) Mutation() *ItemLinkMutation {
	return _u.mutation
}

// ClearContainer clears the "container" edge to the Item entity.
func (_u *ItemLinkUpdate) ClearContainer() *ItemLinkUpdate {
	_u.mutation.ClearContainer()
	return _u
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *ItemLinkUpdate) ClearItem() *ItemLinkUpdate {
	_u.mutation.ClearItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ItemLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ItemLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemLinkUpdate) check() error {
	if _u.mutation.ContainerCleared() && len(_u.mutation.ContainerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ItemLink.container"`)
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ItemLink.item"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ItemLinkUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ItemLinkUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ItemLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemlink.Table, itemlink.Columns, sqlgraph.NewFieldSpec(itemlink.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ord(); ok {
		_spec.SetField(itemlink.FieldOrd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrd(); ok {
		_spec.AddField(itemlink.FieldOrd, field.TypeInt, value)
	}
	if _u.mutation.ContainerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ContainerTable,
			Columns: []string{itemlink.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContainerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ContainerTable,
			Columns: []string{itemlink.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ItemTable,
			Columns: []string{itemlink.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ItemTable,
			Columns: []string{itemlink.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ItemLinkUpdateOne is the builder for updating a single ItemLink entity.
type ItemLinkUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ItemLinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetContainerID sets the "container_id" field.
func (_u *ItemLinkUpdateOne) SetContainerID(v core.ID) *ItemLinkUpdateOne {
	_u.mutation.SetContainerID(v)
	return _u
}

// SetNillableContainerID sets the "container_id" field if the given value is not nil.
func (_u *ItemLinkUpdateOne) SetNillableContainerID(v *core.ID) *ItemLinkUpdateOne {
	if v != nil {
		_u.SetContainerID(*v)
	}
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *ItemLinkUpdateOne) SetItemID(v core.ID) *ItemLinkUpdateOne {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *ItemLinkUpdateOne) SetNillableItemID(v *core.ID) *ItemLinkUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetOrd sets the "ord" field.
func (_u *ItemLinkUpdateOne) SetOrd(v int) *ItemLinkUpdateOne {
	_u.mutation.ResetOrd()
	_u.mutation.SetOrd(v)
	return _u
}

// SetNillableOrd sets the "ord" field if the given value is not nil.
func (_u *ItemLinkUpdateOne) SetNillableOrd(v *int) *ItemLinkUpdateOne {
	if v != nil {
		_u.SetOrd(*v)
	}
	return _u
}

// AddOrd adds value to the "ord" field.
func (_u *ItemLinkUpdateOne) AddOrd(v int) *ItemLinkUpdateOne {
	_u.mutation.AddOrd(v)
	return _u
}

// SetContainer sets the "container" edge to the Item entity.
func (_u *ItemLinkUpdateOne) SetContainer(v *Item) *ItemLinkUpdateOne {
	return _u.SetContainerID(v.ID)
}

// SetItem sets the "item" edge to the Item entity.
func (_u *ItemLinkUpdateOne) SetItem(v *Item) *ItemLinkUpdateOne {
	return _u.SetItemID(v.ID)
}

// Mutation returns the ItemLinkMutation object of the builder.
func (_u *ItemLinkUpdateOne) Mutation() *ItemLinkMutation {
	return _u.mutation
}

// ClearContainer clears the "container" edge to the Item entity.
func (_u *ItemLinkUpdateOne) ClearContainer() *ItemLinkUpdateOne {
	_u.mutation.ClearContainer()
	return _u
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *ItemLinkUpdateOne) ClearItem() *ItemLinkUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// Where appends a list predicates to the ItemLinkUpdate builder.
func (_u *ItemLinkUpdateOne) Where(ps ...predicate.ItemLink) *ItemLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ItemLinkUpdateOne) Select(field string, fields ...string) *ItemLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ItemLink entity.
func (_u *ItemLinkUpdateOne) Save(ctx context.Context) (*ItemLink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemLinkUpdateOne) SaveX(ctx context.Context) *ItemLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ItemLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemLinkUpdateOne) check() error {
	if _u.mutation.ContainerCleared() && len(_u.mutation.ContainerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ItemLink.container"`)
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ItemLink.item"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ItemLinkUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ItemLinkUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ItemLinkUpdateOne) sqlSave(ctx context.Context) (_node *ItemLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemlink.Table, itemlink.Columns, sqlgraph.NewFieldSpec(itemlink.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ItemLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, itemlink.FieldID)
		for _, f := range fields {
			if !itemlink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != itemlink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ord(); ok {
		_spec.SetField(itemlink.FieldOrd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrd(); ok {
		_spec.AddField(itemlink.FieldOrd, field.TypeInt, value)
	}
	if _u.mutation.ContainerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ContainerTable,
			Columns: []string{itemlink.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContainerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ContainerTable,
			Columns: []string{itemlink.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ItemTable,
			Columns: []string{itemlink.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ItemTable,
			Columns: []string{itemlink.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ItemLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
