// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/item"
	"github.com/mavioai/mavio/libs/store/internal/ent/library"
)

// Item is the model entity for the Item schema.
type Item struct {
	config `json:"-"`
	// ID of the ent.
	ID core.ID `json:"id,omitempty"`
	// LibraryID holds the value of the "library_id" field.
	LibraryID core.ID `json:"library_id,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID *core.ID `json:"parent_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SortName holds the value of the "sort_name" field.
	SortName string `json:"sort_name,omitempty"`
	// SortKey holds the value of the "sort_key" field.
	SortKey string `json:"sort_key,omitempty"`
	// OriginalTitle holds the value of the "original_title" field.
	OriginalTitle string `json:"original_title,omitempty"`
	// SearchKey holds the value of the "search_key" field.
	SearchKey string `json:"search_key,omitempty"`
	// OriginalKey holds the value of the "original_key" field.
	OriginalKey string `json:"original_key,omitempty"`
	// Overview holds the value of the "overview" field.
	Overview string `json:"overview,omitempty"`
	// Tagline holds the value of the "tagline" field.
	Tagline string `json:"tagline,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// IndexNumber holds the value of the "index_number" field.
	IndexNumber *int `json:"index_number,omitempty"`
	// ParentIndexNumber holds the value of the "parent_index_number" field.
	ParentIndexNumber *int `json:"parent_index_number,omitempty"`
	// IndexNumberEnd holds the value of the "index_number_end" field.
	IndexNumberEnd *int `json:"index_number_end,omitempty"`
	// ProductionYear holds the value of the "production_year" field.
	ProductionYear int `json:"production_year,omitempty"`
	// PremiereDate holds the value of the "premiere_date" field.
	PremiereDate *time.Time `json:"premiere_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate *time.Time `json:"end_date,omitempty"`
	// Runtime holds the value of the "runtime" field.
	Runtime time.Duration `json:"runtime,omitempty"`
	// OfficialRating holds the value of the "official_rating" field.
	OfficialRating string `json:"official_rating,omitempty"`
	// CustomRating holds the value of the "custom_rating" field.
	CustomRating string `json:"custom_rating,omitempty"`
	// ParentalRating holds the value of the "parental_rating" field.
	ParentalRating int `json:"parental_rating,omitempty"`
	// CommunityRating holds the value of the "community_rating" field.
	CommunityRating float64 `json:"community_rating,omitempty"`
	// CriticRating holds the value of the "critic_rating" field.
	CriticRating float64 `json:"critic_rating,omitempty"`
	// ExternalIds holds the value of the "external_ids" field.
	ExternalIds map[string]string `json:"external_ids,omitempty"`
	// ProductionLocations holds the value of the "production_locations" field.
	ProductionLocations []string `json:"production_locations,omitempty"`
	// RemoteTrailers holds the value of the "remote_trailers" field.
	RemoteTrailers []string `json:"remote_trailers,omitempty"`
	// CollectionName holds the value of the "collection_name" field.
	CollectionName string `json:"collection_name,omitempty"`
	// AspectRatio holds the value of the "aspect_ratio" field.
	AspectRatio string `json:"aspect_ratio,omitempty"`
	// Video3dFormat holds the value of the "video_3d_format" field.
	Video3dFormat string `json:"video_3d_format,omitempty"`
	// Album holds the value of the "album" field.
	Album string `json:"album,omitempty"`
	// SeriesStatus holds the value of the "series_status" field.
	SeriesStatus string `json:"series_status,omitempty"`
	// AirDays holds the value of the "air_days" field.
	AirDays []int `json:"air_days,omitempty"`
	// AirTime holds the value of the "air_time" field.
	AirTime string `json:"air_time,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder string `json:"display_order,omitempty"`
	// AirsBeforeSeasonNumber holds the value of the "airs_before_season_number" field.
	AirsBeforeSeasonNumber *int `json:"airs_before_season_number,omitempty"`
	// AirsAfterSeasonNumber holds the value of the "airs_after_season_number" field.
	AirsAfterSeasonNumber *int `json:"airs_after_season_number,omitempty"`
	// AirsBeforeEpisodeNumber holds the value of the "airs_before_episode_number" field.
	AirsBeforeEpisodeNumber *int `json:"airs_before_episode_number,omitempty"`
	// MetadataLanguage holds the value of the "metadata_language" field.
	MetadataLanguage string `json:"metadata_language,omitempty"`
	// MetadataCountry holds the value of the "metadata_country" field.
	MetadataCountry string `json:"metadata_country,omitempty"`
	// Locked holds the value of the "locked" field.
	Locked bool `json:"locked,omitempty"`
	// LockedFields holds the value of the "locked_fields" field.
	LockedFields []string `json:"locked_fields,omitempty"`
	// Extra holds the value of the "extra" field.
	Extra string `json:"extra,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID *core.ID `json:"owner_id,omitempty"`
	// DateAdded holds the value of the "date_added" field.
	DateAdded time.Time `json:"date_added,omitempty"`
	// FileModified holds the value of the "file_modified" field.
	FileModified *time.Time `json:"file_modified,omitempty"`
	// MetadataRefreshedAt holds the value of the "metadata_refreshed_at" field.
	MetadataRefreshedAt *time.Time `json:"metadata_refreshed_at,omitempty"`
	// ScanGeneration holds the value of the "scan_generation" field.
	ScanGeneration int64 `json:"scan_generation,omitempty"`
	// MissingSince holds the value of the "missing_since" field.
	MissingSince *time.Time `json:"missing_since,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ItemQuery when eager-loading is set.
	Edges        ItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ItemEdges holds the relations/edges for other nodes in the graph.
type ItemEdges struct {
	// Library holds the value of the library edge.
	Library *Library `json:"library,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *Item `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Item `json:"children,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *Item `json:"owner,omitempty"`
	// Extras holds the value of the extras edge.
	Extras []*Item `json:"extras,omitempty"`
	// Values holds the value of the values edge.
	Values []*ItemValue `json:"values,omitempty"`
	// MediaSources holds the value of the media_sources edge.
	MediaSources []*MediaSource `json:"media_sources,omitempty"`
	// Images holds the value of the images edge.
	Images []*Image `json:"images,omitempty"`
	// Credits holds the value of the credits edge.
	Credits []*Credit `json:"credits,omitempty"`
	// UserData holds the value of the user_data edge.
	UserData []*UserData `json:"user_data,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [10]bool
}

// LibraryOrErr returns the Library value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEdges) LibraryOrErr() (*Library, error) {
	if e.Library != nil {
		return e.Library, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: library.Label}
	}
	return nil, &NotLoadedError{edge: "library"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEdges) ParentOrErr() (*Item, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: item.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) ChildrenOrErr() ([]*Item, error) {
	if e.loadedTypes[2] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEdges) OwnerOrErr() (*Item, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: item.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// ExtrasOrErr returns the Extras value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) ExtrasOrErr() ([]*Item, error) {
	if e.loadedTypes[4] {
		return e.Extras, nil
	}
	return nil, &NotLoadedError{edge: "extras"}
}

// ValuesOrErr returns the Values value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) ValuesOrErr() ([]*ItemValue, error) {
	if e.loadedTypes[5] {
		return e.Values, nil
	}
	return nil, &NotLoadedError{edge: "values"}
}

// MediaSourcesOrErr returns the MediaSources value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) MediaSourcesOrErr() ([]*MediaSource, error) {
	if e.loadedTypes[6] {
		return e.MediaSources, nil
	}
	return nil, &NotLoadedError{edge: "media_sources"}
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) ImagesOrErr() ([]*Image, error) {
	if e.loadedTypes[7] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// CreditsOrErr returns the Credits value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) CreditsOrErr() ([]*Credit, error) {
	if e.loadedTypes[8] {
		return e.Credits, nil
	}
	return nil, &NotLoadedError{edge: "credits"}
}

// UserDataOrErr returns the UserData value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) UserDataOrErr() ([]*UserData, error) {
	if e.loadedTypes[9] {
		return e.UserData, nil
	}
	return nil, &NotLoadedError{edge: "user_data"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Item) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case item.FieldParentID, item.FieldOwnerID:
			values[i] = &sql.NullScanner{S: new(core.ID)}
		case item.FieldExternalIds, item.FieldProductionLocations, item.FieldRemoteTrailers, item.FieldAirDays, item.FieldLockedFields:
			values[i] = new([]byte)
		case item.FieldID, item.FieldLibraryID:
			values[i] = new(core.ID)
		case item.FieldLocked:
			values[i] = new(sql.NullBool)
		case item.FieldCommunityRating, item.FieldCriticRating:
			values[i] = new(sql.NullFloat64)
		case item.FieldIndexNumber, item.FieldParentIndexNumber, item.FieldIndexNumberEnd, item.FieldProductionYear, item.FieldRuntime, item.FieldParentalRating, item.FieldAirsBeforeSeasonNumber, item.FieldAirsAfterSeasonNumber, item.FieldAirsBeforeEpisodeNumber, item.FieldScanGeneration:
			values[i] = new(sql.NullInt64)
		case item.FieldKind, item.FieldName, item.FieldSortName, item.FieldSortKey, item.FieldOriginalTitle, item.FieldSearchKey, item.FieldOriginalKey, item.FieldOverview, item.FieldTagline, item.FieldPath, item.FieldOfficialRating, item.FieldCustomRating, item.FieldCollectionName, item.FieldAspectRatio, item.FieldVideo3dFormat, item.FieldAlbum, item.FieldSeriesStatus, item.FieldAirTime, item.FieldDisplayOrder, item.FieldMetadataLanguage, item.FieldMetadataCountry, item.FieldExtra:
			values[i] = new(sql.NullString)
		case item.FieldPremiereDate, item.FieldEndDate, item.FieldDateAdded, item.FieldFileModified, item.FieldMetadataRefreshedAt, item.FieldMissingSince:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Item fields.
func (_m *Item) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case item.FieldID:
			if value, ok := values[i].(*core.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case item.FieldLibraryID:
			if value, ok := values[i].(*core.ID); !ok {
				return fmt.Errorf("unexpected type %T for field library_id", values[i])
			} else if value != nil {
				_m.LibraryID = *value
			}
		case item.FieldParentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(core.ID)
				*_m.ParentID = *value.S.(*core.ID)
			}
		case item.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case item.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case item.FieldSortName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sort_name", values[i])
			} else if value.Valid {
				_m.SortName = value.String
			}
		case item.FieldSortKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sort_key", values[i])
			} else if value.Valid {
				_m.SortKey = value.String
			}
		case item.FieldOriginalTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_title", values[i])
			} else if value.Valid {
				_m.OriginalTitle = value.String
			}
		case item.FieldSearchKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field search_key", values[i])
			} else if value.Valid {
				_m.SearchKey = value.String
			}
		case item.FieldOriginalKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_key", values[i])
			} else if value.Valid {
				_m.OriginalKey = value.String
			}
		case item.FieldOverview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overview", values[i])
			} else if value.Valid {
				_m.Overview = value.String
			}
		case item.FieldTagline:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tagline", values[i])
			} else if value.Valid {
				_m.Tagline = value.String
			}
		case item.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case item.FieldIndexNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field index_number", values[i])
			} else if value.Valid {
				_m.IndexNumber = new(int)
				*_m.IndexNumber = int(value.Int64)
			}
		case item.FieldParentIndexNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_index_number", values[i])
			} else if value.Valid {
				_m.ParentIndexNumber = new(int)
				*_m.ParentIndexNumber = int(value.Int64)
			}
		case item.FieldIndexNumberEnd:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field index_number_end", values[i])
			} else if value.Valid {
				_m.IndexNumberEnd = new(int)
				*_m.IndexNumberEnd = int(value.Int64)
			}
		case item.FieldProductionYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field production_year", values[i])
			} else if value.Valid {
				_m.ProductionYear = int(value.Int64)
			}
		case item.FieldPremiereDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field premiere_date", values[i])
			} else if value.Valid {
				_m.PremiereDate = new(time.Time)
				*_m.PremiereDate = value.Time
			}
		case item.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = new(time.Time)
				*_m.EndDate = value.Time
			}
		case item.FieldRuntime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field runtime", values[i])
			} else if value.Valid {
				_m.Runtime = time.Duration(value.Int64)
			}
		case item.FieldOfficialRating:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field official_rating", values[i])
			} else if value.Valid {
				_m.OfficialRating = value.String
			}
		case item.FieldCustomRating:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_rating", values[i])
			} else if value.Valid {
				_m.CustomRating = value.String
			}
		case item.FieldParentalRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parental_rating", values[i])
			} else if value.Valid {
				_m.ParentalRating = int(value.Int64)
			}
		case item.FieldCommunityRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field community_rating", values[i])
			} else if value.Valid {
				_m.CommunityRating = value.Float64
			}
		case item.FieldCriticRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field critic_rating", values[i])
			} else if value.Valid {
				_m.CriticRating = value.Float64
			}
		case item.FieldExternalIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field external_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExternalIds); err != nil {
					return fmt.Errorf("unmarshal field external_ids: %w", err)
				}
			}
		case item.FieldProductionLocations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field production_locations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProductionLocations); err != nil {
					return fmt.Errorf("unmarshal field production_locations: %w", err)
				}
			}
		case item.FieldRemoteTrailers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field remote_trailers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RemoteTrailers); err != nil {
					return fmt.Errorf("unmarshal field remote_trailers: %w", err)
				}
			}
		case item.FieldCollectionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collection_name", values[i])
			} else if value.Valid {
				_m.CollectionName = value.String
			}
		case item.FieldAspectRatio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aspect_ratio", values[i])
			} else if value.Valid {
				_m.AspectRatio = value.String
			}
		case item.FieldVideo3dFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_3d_format", values[i])
			} else if value.Valid {
				_m.Video3dFormat = value.String
			}
		case item.FieldAlbum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field album", values[i])
			} else if value.Valid {
				_m.Album = value.String
			}
		case item.FieldSeriesStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field series_status", values[i])
			} else if value.Valid {
				_m.SeriesStatus = value.String
			}
		case item.FieldAirDays:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field air_days", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AirDays); err != nil {
					return fmt.Errorf("unmarshal field air_days: %w", err)
				}
			}
		case item.FieldAirTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field air_time", values[i])
			} else if value.Valid {
				_m.AirTime = value.String
			}
		case item.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = value.String
			}
		case item.FieldAirsBeforeSeasonNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field airs_before_season_number", values[i])
			} else if value.Valid {
				_m.AirsBeforeSeasonNumber = new(int)
				*_m.AirsBeforeSeasonNumber = int(value.Int64)
			}
		case item.FieldAirsAfterSeasonNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field airs_after_season_number", values[i])
			} else if value.Valid {
				_m.AirsAfterSeasonNumber = new(int)
				*_m.AirsAfterSeasonNumber = int(value.Int64)
			}
		case item.FieldAirsBeforeEpisodeNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field airs_before_episode_number", values[i])
			} else if value.Valid {
				_m.AirsBeforeEpisodeNumber = new(int)
				*_m.AirsBeforeEpisodeNumber = int(value.Int64)
			}
		case item.FieldMetadataLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_language", values[i])
			} else if value.Valid {
				_m.MetadataLanguage = value.String
			}
		case item.FieldMetadataCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_country", values[i])
			} else if value.Valid {
				_m.MetadataCountry = value.String
			}
		case item.FieldLocked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field locked", values[i])
			} else if value.Valid {
				_m.Locked = value.Bool
			}
		case item.FieldLockedFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field locked_fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LockedFields); err != nil {
					return fmt.Errorf("unmarshal field locked_fields: %w", err)
				}
			}
		case item.FieldExtra:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra", values[i])
			} else if value.Valid {
				_m.Extra = value.String
			}
		case item.FieldOwnerID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = new(core.ID)
				*_m.OwnerID = *value.S.(*core.ID)
			}
		case item.FieldDateAdded:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_added", values[i])
			} else if value.Valid {
				_m.DateAdded = value.Time
			}
		case item.FieldFileModified:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field file_modified", values[i])
			} else if value.Valid {
				_m.FileModified = new(time.Time)
				*_m.FileModified = value.Time
			}
		case item.FieldMetadataRefreshedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_refreshed_at", values[i])
			} else if value.Valid {
				_m.MetadataRefreshedAt = new(time.Time)
				*_m.MetadataRefreshedAt = value.Time
			}
		case item.FieldScanGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field scan_generation", values[i])
			} else if value.Valid {
				_m.ScanGeneration = value.Int64
			}
		case item.FieldMissingSince:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field missing_since", values[i])
			} else if value.Valid {
				_m.MissingSince = new(time.Time)
				*_m.MissingSince = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Item.
// This includes values selected through modifiers, order, etc.
func (_m *Item) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLibrary queries the "library" edge of the Item entity.
func (_m *Item) QueryLibrary() *LibraryQuery {
	return NewItemClient(_m.config).QueryLibrary(_m)
}

// QueryParent queries the "parent" edge of the Item entity.
func (_m *Item) QueryParent() *ItemQuery {
	return NewItemClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Item entity.
func (_m *Item) QueryChildren() *ItemQuery {
	return NewItemClient(_m.config).QueryChildren(_m)
}

// QueryOwner queries the "owner" edge of the Item entity.
func (_m *Item) QueryOwner() *ItemQuery {
	return NewItemClient(_m.config).QueryOwner(_m)
}

// QueryExtras queries the "extras" edge of the Item entity.
func (_m *Item) QueryExtras() *ItemQuery {
	return NewItemClient(_m.config).QueryExtras(_m)
}

// QueryValues queries the "values" edge of the Item entity.
func (_m *Item) QueryValues() *ItemValueQuery {
	return NewItemClient(_m.config).QueryValues(_m)
}

// QueryMediaSources queries the "media_sources" edge of the Item entity.
func (_m *Item) QueryMediaSources() *MediaSourceQuery {
	return NewItemClient(_m.config).QueryMediaSources(_m)
}

// QueryImages queries the "images" edge of the Item entity.
func (_m *Item) QueryImages() *ImageQuery {
	return NewItemClient(_m.config).QueryImages(_m)
}

// QueryCredits queries the "credits" edge of the Item entity.
func (_m *Item) QueryCredits() *CreditQuery {
	return NewItemClient(_m.config).QueryCredits(_m)
}

// QueryUserData queries the "user_data" edge of the Item entity.
func (_m *Item) QueryUserData() *UserDataQuery {
	return NewItemClient(_m.config).QueryUserData(_m)
}

// Update returns a builder for updating this Item.
// Note that you need to call Item.Unwrap() before calling this method if this Item
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Item) Update() *ItemUpdateOne {
	return NewItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Item entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Item) Unwrap() *Item {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Item is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Item) String() string {
	var builder strings.Builder
	builder.WriteString("Item(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("library_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LibraryID))
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("sort_name=")
	builder.WriteString(_m.SortName)
	builder.WriteString(", ")
	builder.WriteString("sort_key=")
	builder.WriteString(_m.SortKey)
	builder.WriteString(", ")
	builder.WriteString("original_title=")
	builder.WriteString(_m.OriginalTitle)
	builder.WriteString(", ")
	builder.WriteString("search_key=")
	builder.WriteString(_m.SearchKey)
	builder.WriteString(", ")
	builder.WriteString("original_key=")
	builder.WriteString(_m.OriginalKey)
	builder.WriteString(", ")
	builder.WriteString("overview=")
	builder.WriteString(_m.Overview)
	builder.WriteString(", ")
	builder.WriteString("tagline=")
	builder.WriteString(_m.Tagline)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	if v := _m.IndexNumber; v != nil {
		builder.WriteString("index_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ParentIndexNumber; v != nil {
		builder.WriteString("parent_index_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IndexNumberEnd; v != nil {
		builder.WriteString("index_number_end=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("production_year=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductionYear))
	builder.WriteString(", ")
	if v := _m.PremiereDate; v != nil {
		builder.WriteString("premiere_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndDate; v != nil {
		builder.WriteString("end_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("runtime=")
	builder.WriteString(fmt.Sprintf("%v", _m.Runtime))
	builder.WriteString(", ")
	builder.WriteString("official_rating=")
	builder.WriteString(_m.OfficialRating)
	builder.WriteString(", ")
	builder.WriteString("custom_rating=")
	builder.WriteString(_m.CustomRating)
	builder.WriteString(", ")
	builder.WriteString("parental_rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentalRating))
	builder.WriteString(", ")
	builder.WriteString("community_rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommunityRating))
	builder.WriteString(", ")
	builder.WriteString("critic_rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.CriticRating))
	builder.WriteString(", ")
	builder.WriteString("external_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExternalIds))
	builder.WriteString(", ")
	builder.WriteString("production_locations=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductionLocations))
	builder.WriteString(", ")
	builder.WriteString("remote_trailers=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemoteTrailers))
	builder.WriteString(", ")
	builder.WriteString("collection_name=")
	builder.WriteString(_m.CollectionName)
	builder.WriteString(", ")
	builder.WriteString("aspect_ratio=")
	builder.WriteString(_m.AspectRatio)
	builder.WriteString(", ")
	builder.WriteString("video_3d_format=")
	builder.WriteString(_m.Video3dFormat)
	builder.WriteString(", ")
	builder.WriteString("album=")
	builder.WriteString(_m.Album)
	builder.WriteString(", ")
	builder.WriteString("series_status=")
	builder.WriteString(_m.SeriesStatus)
	builder.WriteString(", ")
	builder.WriteString("air_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.AirDays))
	builder.WriteString(", ")
	builder.WriteString("air_time=")
	builder.WriteString(_m.AirTime)
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(_m.DisplayOrder)
	builder.WriteString(", ")
	if v := _m.AirsBeforeSeasonNumber; v != nil {
		builder.WriteString("airs_before_season_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AirsAfterSeasonNumber; v != nil {
		builder.WriteString("airs_after_season_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AirsBeforeEpisodeNumber; v != nil {
		builder.WriteString("airs_before_episode_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata_language=")
	builder.WriteString(_m.MetadataLanguage)
	builder.WriteString(", ")
	builder.WriteString("metadata_country=")
	builder.WriteString(_m.MetadataCountry)
	builder.WriteString(", ")
	builder.WriteString("locked=")
	builder.WriteString(fmt.Sprintf("%v", _m.Locked))
	builder.WriteString(", ")
	builder.WriteString("locked_fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.LockedFields))
	builder.WriteString(", ")
	builder.WriteString("extra=")
	builder.WriteString(_m.Extra)
	builder.WriteString(", ")
	if v := _m.OwnerID; v != nil {
		builder.WriteString("owner_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("date_added=")
	builder.WriteString(_m.DateAdded.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FileModified; v != nil {
		builder.WriteString("file_modified=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.MetadataRefreshedAt; v != nil {
		builder.WriteString("metadata_refreshed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("scan_generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScanGeneration))
	builder.WriteString(", ")
	if v := _m.MissingSince; v != nil {
		builder.WriteString("missing_since=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Items is a parsable slice of Item.
type Items []*Item
