// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/item"
	"github.com/mavioai/mavio/libs/store/internal/ent/itemlink"
)

// ItemLinkCreate is the builder for creating a ItemLink entity.
type ItemLinkCreate struct {
	config
	mutation *ItemLinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetContainerID sets the "container_id" field.
func (_c *ItemLinkCreate) SetContainerID(v core.ID) *ItemLinkCreate {
	_c.mutation.SetContainerID(v)
	return _c
}

// SetItemID sets the "item_id" field.
func (_c *ItemLinkCreate) SetItemID(v core.ID) *ItemLinkCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetOrd sets the "ord" field.
func (_c *ItemLinkCreate) SetOrd(v int) *ItemLinkCreate {
	_c.mutation.SetOrd(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ItemLinkCreate) SetID(v core.ID) *ItemLinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ItemLinkCreate) SetNillableID(v *core.ID) *ItemLinkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetContainer sets the "container" edge to the Item entity.
func (_c *ItemLinkCreate) SetContainer(v *Item) *ItemLinkCreate {
	return _c.SetContainerID(v.ID)
}

// SetItem sets the "item" edge to the Item entity.
func (_c *ItemLinkCreate) SetItem(v *Item) *ItemLinkCreate {
	return _c.SetItemID(v.ID)
}

// Mutation returns the ItemLinkMutation object of the builder.
func (_c *ItemLinkCreate) Mutation() *ItemLinkMutation {
	return _c.mutation
}

// Save creates the ItemLink in the database.
func (_c *ItemLinkCreate) Save(ctx context.Context) (*ItemLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemLinkCreate) SaveX(ctx context.Context) *ItemLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemLinkCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := itemlink.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemLinkCreate) check() error {
	if _, ok := _c.mutation.ContainerID(); !ok {
		return &ValidationError{Name: "container_id", err: errors.New(`ent: missing required field "ItemLink.container_id"`)}
	}
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "ItemLink.item_id"`)}
	}
	if _, ok := _c.mutation.Ord(); !ok {
		return &ValidationError{Name: "ord", err: errors.New(`ent: missing required field "ItemLink.ord"`)}
	}
	if len(_c.mutation.ContainerIDs()) == 0 {
		return &ValidationError{Name: "container", err: errors.New(`ent: missing required edge "ItemLink.container"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "ItemLink.item"`)}
	}
	return nil
}

func (_c *ItemLinkCreate) sqlSave(ctx context.Context) (*ItemLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*core.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemLinkCreate) createSpec() (*ItemLink, *sqlgraph.CreateSpec) {
	var (
		_node = &ItemLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(itemlink.Table, sqlgraph.NewFieldSpec(itemlink.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Ord(); ok {
		_spec.SetField(itemlink.FieldOrd, field.TypeInt, value)
		_node.Ord = value
	}
	if nodes := _c.mutation.ContainerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ContainerTable,
			Columns: []string{itemlink.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContainerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemlink.ItemTable,
			Columns: []string{itemlink.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemLink.Create().
//		SetContainerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemLinkUpsert) {
//			SetContainerID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemLinkCreate) OnConflict(opts ...sql.ConflictOption) *ItemLinkUpsertOne {
	_c.conflict = opts
	return &ItemLinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemLinkCreate) OnConflictColumns(columns ...string) *ItemLinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemLinkUpsertOne{
		create: _c,
	}
}

type (
	// ItemLinkUpsertOne is the builder for "upsert"-ing
	//  one ItemLink node.
	ItemLinkUpsertOne struct {
		create *ItemLinkCreate
	}

	// ItemLinkUpsert is the "OnConflict" setter.
	ItemLinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetContainerID sets the "container_id" field.
func (u *ItemLinkUpsert) SetContainerID(v core.ID) *ItemLinkUpsert {
	u.Set(itemlink.FieldContainerID, v)
	return u
}

// UpdateContainerID sets the "container_id" field to the value that was provided on create.
func (u *ItemLinkUpsert) UpdateContainerID() *ItemLinkUpsert {
	u.SetExcluded(itemlink.FieldContainerID)
	return u
}

// SetItemID sets the "item_id" field.
func (u *ItemLinkUpsert) SetItemID(v core.ID) *ItemLinkUpsert {
	u.Set(itemlink.FieldItemID, v)
	return u
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemLinkUpsert) UpdateItemID() *ItemLinkUpsert {
	u.SetExcluded(itemlink.FieldItemID)
	return u
}

// SetOrd sets the "ord" field.
func (u *ItemLinkUpsert) SetOrd(v int) *ItemLinkUpsert {
	u.Set(itemlink.FieldOrd, v)
	return u
}

// UpdateOrd sets the "ord" field to the value that was provided on create.
func (u *ItemLinkUpsert) UpdateOrd() *ItemLinkUpsert {
	u.SetExcluded(itemlink.FieldOrd)
	return u
}

// AddOrd adds v to the "ord" field.
func (u *ItemLinkUpsert) AddOrd(v int) *ItemLinkUpsert {
	u.Add(itemlink.FieldOrd, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ItemLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(itemlink.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemLinkUpsertOne) UpdateNewValues() *ItemLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(itemlink.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemLink.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ItemLinkUpsertOne) Ignore() *ItemLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemLinkUpsertOne) DoNothing() *ItemLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemLinkCreate.OnConflict
// documentation for more info.
func (u *ItemLinkUpsertOne) Update(set func(*ItemLinkUpsert)) *ItemLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetContainerID sets the "container_id" field.
func (u *ItemLinkUpsertOne) SetContainerID(v core.ID) *ItemLinkUpsertOne {
	return u.Update(func(s *ItemLinkUpsert) {
		s.SetContainerID(v)
	})
}

// UpdateContainerID sets the "container_id" field to the value that was provided on create.
func (u *ItemLinkUpsertOne) UpdateContainerID() *ItemLinkUpsertOne {
	return u.Update(func(s *ItemLinkUpsert) {
		s.UpdateContainerID()
	})
}

// SetItemID sets the "item_id" field.
func (u *ItemLinkUpsertOne) SetItemID(v core.ID) *ItemLinkUpsertOne {
	return u.Update(func(s *ItemLinkUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemLinkUpsertOne) UpdateItemID() *ItemLinkUpsertOne {
	return u.Update(func(s *ItemLinkUpsert) {
		s.UpdateItemID()
	})
}

// SetOrd sets the "ord" field.
func (u *ItemLinkUpsertOne) SetOrd(v int) *ItemLinkUpsertOne {
	return u.Update(func(s *ItemLinkUpsert) {
		s.SetOrd(v)
	})
}

// AddOrd adds v to the "ord" field.
func (u *ItemLinkUpsertOne) AddOrd(v int) *ItemLinkUpsertOne {
	return u.Update(func(s *ItemLinkUpsert) {
		s.AddOrd(v)
	})
}

// UpdateOrd sets the "ord" field to the value that was provided on create.
func (u *ItemLinkUpsertOne) UpdateOrd() *ItemLinkUpsertOne {
	return u.Update(func(s *ItemLinkUpsert) {
		s.UpdateOrd()
	})
}

// Exec executes the query.
func (u *ItemLinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemLinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemLinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ItemLinkUpsertOne) ID(ctx context.Context) (id core.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ItemLinkUpsertOne.ID is not supported by MySQL driver. Use ItemLinkUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ItemLinkUpsertOne) IDX(ctx context.Context) core.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ItemLinkCreateBulk is the builder for creating many ItemLink entities in bulk.
type ItemLinkCreateBulk struct {
	config
	err      error
	builders []*ItemLinkCreate
	conflict []sql.ConflictOption
}

// Save creates the ItemLink entities in the database.
func (_c *ItemLinkCreateBulk) Save(ctx context.Context) ([]*ItemLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ItemLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemLinkCreateBulk) SaveX(ctx context.Context) []*ItemLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemLink.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemLinkUpsert) {
//			SetContainerID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemLinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *ItemLinkUpsertBulk {
	_c.conflict = opts
	return &ItemLinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemLinkCreateBulk) OnConflictColumns(columns ...string) *ItemLinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemLinkUpsertBulk{
		create: _c,
	}
}

// ItemLinkUpsertBulk is the builder for "upsert"-ing
// a bulk of ItemLink nodes.
type ItemLinkUpsertBulk struct {
	create *ItemLinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ItemLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(itemlink.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemLinkUpsertBulk) UpdateNewValues() *ItemLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(itemlink.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemLink.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ItemLinkUpsertBulk) Ignore() *ItemLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemLinkUpsertBulk) DoNothing() *ItemLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemLinkCreateBulk.OnConflict
// documentation for more info.
func (u *ItemLinkUpsertBulk) Update(set func(*ItemLinkUpsert)) *ItemLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetContainerID sets the "container_id" field.
func (u *ItemLinkUpsertBulk) SetContainerID(v core.ID) *ItemLinkUpsertBulk {
	return u.Update(func(s *ItemLinkUpsert) {
		s.SetContainerID(v)
	})
}

// UpdateContainerID sets the "container_id" field to the value that was provided on create.
func (u *ItemLinkUpsertBulk) UpdateContainerID() *ItemLinkUpsertBulk {
	return u.Update(func(s *ItemLinkUpsert) {
		s.UpdateContainerID()
	})
}

// SetItemID sets the "item_id" field.
func (u *ItemLinkUpsertBulk) SetItemID(v core.ID) *ItemLinkUpsertBulk {
	return u.Update(func(s *ItemLinkUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemLinkUpsertBulk) UpdateItemID() *ItemLinkUpsertBulk {
	return u.Update(func(s *ItemLinkUpsert) {
		s.UpdateItemID()
	})
}

// SetOrd sets the "ord" field.
func (u *ItemLinkUpsertBulk) SetOrd(v int) *ItemLinkUpsertBulk {
	return u.Update(func(s *ItemLinkUpsert) {
		s.SetOrd(v)
	})
}

// AddOrd adds v to the "ord" field.
func (u *ItemLinkUpsertBulk) AddOrd(v int) *ItemLinkUpsertBulk {
	return u.Update(func(s *ItemLinkUpsert) {
		s.AddOrd(v)
	})
}

// UpdateOrd sets the "ord" field to the value that was provided on create.
func (u *ItemLinkUpsertBulk) UpdateOrd() *ItemLinkUpsertBulk {
	return u.Update(func(s *ItemLinkUpsert) {
		s.UpdateOrd()
	})
}

// Exec executes the query.
func (u *ItemLinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ItemLinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemLinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemLinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
