// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/folderstate"
	"github.com/mavioai/mavio/libs/store/internal/ent/item"
	"github.com/mavioai/mavio/libs/store/internal/ent/library"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
)

// LibraryUpdate is the builder for updating Library entities.
type LibraryUpdate struct {
	config
	hooks     []Hook
	mutation  *LibraryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LibraryUpdate builder.
func (_u *LibraryUpdate) Where(ps ...predicate.Library) *LibraryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *LibraryUpdate) SetName(v string) *LibraryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableName(v *string) *LibraryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *LibraryUpdate) SetKind(v string) *LibraryUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableKind(v *string) *LibraryUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPaths sets the "paths" field.
func (_u *LibraryUpdate) SetPaths(v []string) *LibraryUpdate {
	_u.mutation.SetPaths(v)
	return _u
}

// AppendPaths appends value to the "paths" field.
func (_u *LibraryUpdate) AppendPaths(v []string) *LibraryUpdate {
	_u.mutation.AppendPaths(v)
	return _u
}

// SetScanInterval sets the "scan_interval" field.
func (_u *LibraryUpdate) SetScanInterval(v time.Duration) *LibraryUpdate {
	_u.mutation.ResetScanInterval()
	_u.mutation.SetScanInterval(v)
	return _u
}

// SetNillableScanInterval sets the "scan_interval" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableScanInterval(v *time.Duration) *LibraryUpdate {
	if v != nil {
		_u.SetScanInterval(*v)
	}
	return _u
}

// AddScanInterval adds value to the "scan_interval" field.
func (_u *LibraryUpdate) AddScanInterval(v time.Duration) *LibraryUpdate {
	_u.mutation.AddScanInterval(v)
	return _u
}

// SetPreferredLanguage sets the "preferred_language" field.
func (_u *LibraryUpdate) SetPreferredLanguage(v string) *LibraryUpdate {
	_u.mutation.SetPreferredLanguage(v)
	return _u
}

// SetNillablePreferredLanguage sets the "preferred_language" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillablePreferredLanguage(v *string) *LibraryUpdate {
	if v != nil {
		_u.SetPreferredLanguage(*v)
	}
	return _u
}

// SetMetadataCountry sets the "metadata_country" field.
func (_u *LibraryUpdate) SetMetadataCountry(v string) *LibraryUpdate {
	_u.mutation.SetMetadataCountry(v)
	return _u
}

// SetNillableMetadataCountry sets the "metadata_country" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableMetadataCountry(v *string) *LibraryUpdate {
	if v != nil {
		_u.SetMetadataCountry(*v)
	}
	return _u
}

// SetScanGeneration sets the "scan_generation" field.
func (_u *LibraryUpdate) SetScanGeneration(v int64) *LibraryUpdate {
	_u.mutation.ResetScanGeneration()
	_u.mutation.SetScanGeneration(v)
	return _u
}

// SetNillableScanGeneration sets the "scan_generation" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableScanGeneration(v *int64) *LibraryUpdate {
	if v != nil {
		_u.SetScanGeneration(*v)
	}
	return _u
}

// AddScanGeneration adds value to the "scan_generation" field.
func (_u *LibraryUpdate) AddScanGeneration(v int64) *LibraryUpdate {
	_u.mutation.AddScanGeneration(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibraryUpdate) SetUpdatedAt(v time.Time) *LibraryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_u *LibraryUpdate) AddItemIDs(ids ...core.ID) *LibraryUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the Item entity.
func (_u *LibraryUpdate) AddItems(v ...*Item) *LibraryUpdate {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddFolderStateIDs adds the "folder_states" edge to the FolderState entity by IDs.
func (_u *LibraryUpdate) AddFolderStateIDs(ids ...core.ID) *LibraryUpdate {
	_u.mutation.AddFolderStateIDs(ids...)
	return _u
}

// AddFolderStates adds the "folder_states" edges to the FolderState entity.
func (_u *LibraryUpdate) AddFolderStates(v ...*FolderState) *LibraryUpdate {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFolderStateIDs(ids...)
}

// Mutation returns the LibraryMutation object of the builder.
func (_u *LibraryUpdate) Mutation() *LibraryMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the Item entity.
func (_u *LibraryUpdate) ClearItems() *LibraryUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (_u *LibraryUpdate) RemoveItemIDs(ids ...core.ID) *LibraryUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to Item entities.
func (_u *LibraryUpdate) RemoveItems(v ...*Item) *LibraryUpdate {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearFolderStates clears all "folder_states" edges to the FolderState entity.
func (_u *LibraryUpdate) ClearFolderStates() *LibraryUpdate {
	_u.mutation.ClearFolderStates()
	return _u
}

// RemoveFolderStateIDs removes the "folder_states" edge to FolderState entities by IDs.
func (_u *LibraryUpdate) RemoveFolderStateIDs(ids ...core.ID) *LibraryUpdate {
	_u.mutation.RemoveFolderStateIDs(ids...)
	return _u
}

// RemoveFolderStates removes "folder_states" edges to FolderState entities.
func (_u *LibraryUpdate) RemoveFolderStates(v ...*FolderState) *LibraryUpdate {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFolderStateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LibraryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibraryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LibraryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibraryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibraryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := library.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibraryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := library.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Library.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LibraryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LibraryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LibraryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(library.Table, library.Columns, sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(library.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(library.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Paths(); ok {
		_spec.SetField(library.FieldPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, library.FieldPaths, value)
		})
	}
	if value, ok := _u.mutation.ScanInterval(); ok {
		_spec.SetField(library.FieldScanInterval, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScanInterval(); ok {
		_spec.AddField(library.FieldScanInterval, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PreferredLanguage(); ok {
		_spec.SetField(library.FieldPreferredLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataCountry(); ok {
		_spec.SetField(library.FieldMetadataCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScanGeneration(); ok {
		_spec.SetField(library.FieldScanGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScanGeneration(); ok {
		_spec.AddField(library.FieldScanGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(library.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FolderStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.FolderStatesTable,
			Columns: []string{library.FolderStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folderstate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFolderStatesIDs(); len(nodes) > 0 && !_u.mutation.FolderStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.FolderStatesTable,
			Columns: []string{library.FolderStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folderstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.FolderStatesTable,
			Columns: []string{library.FolderStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folderstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{library.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LibraryUpdateOne is the builder for updating a single Library entity.
type LibraryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LibraryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *LibraryUpdateOne) SetName(v string) *LibraryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableName(v *string) *LibraryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *LibraryUpdateOne) SetKind(v string) *LibraryUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableKind(v *string) *LibraryUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPaths sets the "paths" field.
func (_u *LibraryUpdateOne) SetPaths(v []string) *LibraryUpdateOne {
	_u.mutation.SetPaths(v)
	return _u
}

// AppendPaths appends value to the "paths" field.
func (_u *LibraryUpdateOne) AppendPaths(v []string) *LibraryUpdateOne {
	_u.mutation.AppendPaths(v)
	return _u
}

// SetScanInterval sets the "scan_interval" field.
func (_u *LibraryUpdateOne) SetScanInterval(v time.Duration) *LibraryUpdateOne {
	_u.mutation.ResetScanInterval()
	_u.mutation.SetScanInterval(v)
	return _u
}

// SetNillableScanInterval sets the "scan_interval" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableScanInterval(v *time.Duration) *LibraryUpdateOne {
	if v != nil {
		_u.SetScanInterval(*v)
	}
	return _u
}

// AddScanInterval adds value to the "scan_interval" field.
func (_u *LibraryUpdateOne) AddScanInterval(v time.Duration) *LibraryUpdateOne {
	_u.mutation.AddScanInterval(v)
	return _u
}

// SetPreferredLanguage sets the "preferred_language" field.
func (_u *LibraryUpdateOne) SetPreferredLanguage(v string) *LibraryUpdateOne {
	_u.mutation.SetPreferredLanguage(v)
	return _u
}

// SetNillablePreferredLanguage sets the "preferred_language" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillablePreferredLanguage(v *string) *LibraryUpdateOne {
	if v != nil {
		_u.SetPreferredLanguage(*v)
	}
	return _u
}

// SetMetadataCountry sets the "metadata_country" field.
func (_u *LibraryUpdateOne) SetMetadataCountry(v string) *LibraryUpdateOne {
	_u.mutation.SetMetadataCountry(v)
	return _u
}

// SetNillableMetadataCountry sets the "metadata_country" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableMetadataCountry(v *string) *LibraryUpdateOne {
	if v != nil {
		_u.SetMetadataCountry(*v)
	}
	return _u
}

// SetScanGeneration sets the "scan_generation" field.
func (_u *LibraryUpdateOne) SetScanGeneration(v int64) *LibraryUpdateOne {
	_u.mutation.ResetScanGeneration()
	_u.mutation.SetScanGeneration(v)
	return _u
}

// SetNillableScanGeneration sets the "scan_generation" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableScanGeneration(v *int64) *LibraryUpdateOne {
	if v != nil {
		_u.SetScanGeneration(*v)
	}
	return _u
}

// AddScanGeneration adds value to the "scan_generation" field.
func (_u *LibraryUpdateOne) AddScanGeneration(v int64) *LibraryUpdateOne {
	_u.mutation.AddScanGeneration(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibraryUpdateOne) SetUpdatedAt(v time.Time) *LibraryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_u *LibraryUpdateOne) AddItemIDs(ids ...core.ID) *LibraryUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the Item entity.
func (_u *LibraryUpdateOne) AddItems(v ...*Item) *LibraryUpdateOne {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddFolderStateIDs adds the "folder_states" edge to the FolderState entity by IDs.
func (_u *LibraryUpdateOne) AddFolderStateIDs(ids ...core.ID) *LibraryUpdateOne {
	_u.mutation.AddFolderStateIDs(ids...)
	return _u
}

// AddFolderStates adds the "folder_states" edges to the FolderState entity.
func (_u *LibraryUpdateOne) AddFolderStates(v ...*FolderState) *LibraryUpdateOne {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFolderStateIDs(ids...)
}

// Mutation returns the LibraryMutation object of the builder.
func (_u *LibraryUpdateOne) Mutation() *LibraryMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the Item entity.
func (_u *LibraryUpdateOne) ClearItems() *LibraryUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (_u *LibraryUpdateOne) RemoveItemIDs(ids ...core.ID) *LibraryUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to Item entities.
func (_u *LibraryUpdateOne) RemoveItems(v ...*Item) *LibraryUpdateOne {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearFolderStates clears all "folder_states" edges to the FolderState entity.
func (_u *LibraryUpdateOne) ClearFolderStates() *LibraryUpdateOne {
	_u.mutation.ClearFolderStates()
	return _u
}

// RemoveFolderStateIDs removes the "folder_states" edge to FolderState entities by IDs.
func (_u *LibraryUpdateOne) RemoveFolderStateIDs(ids ...core.ID) *LibraryUpdateOne {
	_u.mutation.RemoveFolderStateIDs(ids...)
	return _u
}

// RemoveFolderStates removes "folder_states" edges to FolderState entities.
func (_u *LibraryUpdateOne) RemoveFolderStates(v ...*FolderState) *LibraryUpdateOne {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFolderStateIDs(ids...)
}

// Where appends a list predicates to the LibraryUpdate builder.
func (_u *LibraryUpdateOne) Where(ps ...predicate.Library) *LibraryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LibraryUpdateOne) Select(field string, fields ...string) *LibraryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Library entity.
func (_u *LibraryUpdateOne) Save(ctx context.Context) (*Library, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibraryUpdateOne) SaveX(ctx context.Context) *Library {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LibraryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibraryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibraryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := library.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibraryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := library.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Library.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LibraryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LibraryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LibraryUpdateOne) sqlSave(ctx context.Context) (_node *Library, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(library.Table, library.Columns, sqlgraph.NewFieldSpec(library.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Library.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, library.FieldID)
		for _, f := range fields {
			if !library.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != library.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(library.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(library.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Paths(); ok {
		_spec.SetField(library.FieldPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, library.FieldPaths, value)
		})
	}
	if value, ok := _u.mutation.ScanInterval(); ok {
		_spec.SetField(library.FieldScanInterval, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScanInterval(); ok {
		_spec.AddField(library.FieldScanInterval, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PreferredLanguage(); ok {
		_spec.SetField(library.FieldPreferredLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataCountry(); ok {
		_spec.SetField(library.FieldMetadataCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScanGeneration(); ok {
		_spec.SetField(library.FieldScanGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScanGeneration(); ok {
		_spec.AddField(library.FieldScanGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(library.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.ItemsTable,
			Columns: []string{library.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FolderStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.FolderStatesTable,
			Columns: []string{library.FolderStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folderstate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFolderStatesIDs(); len(nodes) > 0 && !_u.mutation.FolderStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.FolderStatesTable,
			Columns: []string{library.FolderStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folderstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   library.FolderStatesTable,
			Columns: []string{library.FolderStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folderstate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Library{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{library.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
