// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/store/internal/ent/mediasource"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
)

// MediaSourceDelete is the builder for deleting a MediaSource entity.
type MediaSourceDelete struct {
	config
	hooks    []Hook
	mutation *MediaSourceMutation
}

// Where appends a list predicates to the MediaSourceDelete builder.
func (_d *MediaSourceDelete) Where(ps ...predicate.MediaSource) *MediaSourceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MediaSourceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaSourceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MediaSourceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mediasource.Table, sqlgraph.NewFieldSpec(mediasource.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MediaSourceDeleteOne is the builder for deleting a single MediaSource entity.
type MediaSourceDeleteOne struct {
	_d *MediaSourceDelete
}

// Where appends a list predicates to the MediaSourceDelete builder.
func (_d *MediaSourceDeleteOne) Where(ps ...predicate.MediaSource) *MediaSourceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MediaSourceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediasource.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaSourceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
