// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/pluginconfig"
)

// PluginConfig is the model entity for the PluginConfig schema.
type PluginConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID core.ID `json:"id,omitempty"`
	// PluginID holds the value of the "plugin_id" field.
	PluginID string `json:"plugin_id,omitempty"`
	// Config holds the value of the "config" field.
	Config string `json:"-"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PluginConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pluginconfig.FieldID:
			values[i] = new(core.ID)
		case pluginconfig.FieldPluginID, pluginconfig.FieldConfig:
			values[i] = new(sql.NullString)
		case pluginconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PluginConfig fields.
func (_m *PluginConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pluginconfig.FieldID:
			if value, ok := values[i].(*core.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pluginconfig.FieldPluginID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_id", values[i])
			} else if value.Valid {
				_m.PluginID = value.String
			}
		case pluginconfig.FieldConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value.Valid {
				_m.Config = value.String
			}
		case pluginconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PluginConfig.
// This includes values selected through modifiers, order, etc.
func (_m *PluginConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PluginConfig.
// Note that you need to call PluginConfig.Unwrap() before calling this method if this PluginConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PluginConfig) Update() *PluginConfigUpdateOne {
	return NewPluginConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PluginConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PluginConfig) Unwrap() *PluginConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PluginConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PluginConfig) String() string {
	var builder strings.Builder
	builder.WriteString("PluginConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plugin_id=")
	builder.WriteString(_m.PluginID)
	builder.WriteString(", ")
	builder.WriteString("config=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PluginConfigs is a parsable slice of PluginConfig.
type PluginConfigs []*PluginConfig
