// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/pluginconfig"
)

// PluginConfigCreate is the builder for creating a PluginConfig entity.
type PluginConfigCreate struct {
	config
	mutation *PluginConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPluginID sets the "plugin_id" field.
func (_c *PluginConfigCreate) SetPluginID(v string) *PluginConfigCreate {
	_c.mutation.SetPluginID(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *PluginConfigCreate) SetConfig(v string) *PluginConfigCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PluginConfigCreate) SetUpdatedAt(v time.Time) *PluginConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PluginConfigCreate) SetNillableUpdatedAt(v *time.Time) *PluginConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PluginConfigCreate) SetID(v core.ID) *PluginConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PluginConfigCreate) SetNillableID(v *core.ID) *PluginConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PluginConfigMutation object of the builder.
func (_c *PluginConfigCreate) Mutation() *PluginConfigMutation {
	return _c.mutation
}

// Save creates the PluginConfig in the database.
func (_c *PluginConfigCreate) Save(ctx context.Context) (*PluginConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginConfigCreate) SaveX(ctx context.Context) *PluginConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginConfigCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pluginconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pluginconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginConfigCreate) check() error {
	if _, ok := _c.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "PluginConfig.plugin_id"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "PluginConfig.config"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PluginConfig.updated_at"`)}
	}
	return nil
}

func (_c *PluginConfigCreate) sqlSave(ctx context.Context) (*PluginConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*core.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginConfigCreate) createSpec() (*PluginConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pluginconfig.Table, sqlgraph.NewFieldSpec(pluginconfig.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PluginID(); ok {
		_spec.SetField(pluginconfig.FieldPluginID, field.TypeString, value)
		_node.PluginID = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(pluginconfig.FieldConfig, field.TypeString, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PluginConfig.Create().
//		SetPluginID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginConfigUpsert) {
//			SetPluginID(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginConfigCreate) OnConflict(opts ...sql.ConflictOption) *PluginConfigUpsertOne {
	_c.conflict = opts
	return &PluginConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PluginConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginConfigCreate) OnConflictColumns(columns ...string) *PluginConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginConfigUpsertOne{
		create: _c,
	}
}

type (
	// PluginConfigUpsertOne is the builder for "upsert"-ing
	//  one PluginConfig node.
	PluginConfigUpsertOne struct {
		create *PluginConfigCreate
	}

	// PluginConfigUpsert is the "OnConflict" setter.
	PluginConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetConfig sets the "config" field.
func (u *PluginConfigUpsert) SetConfig(v string) *PluginConfigUpsert {
	u.Set(pluginconfig.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *PluginConfigUpsert) UpdateConfig() *PluginConfigUpsert {
	u.SetExcluded(pluginconfig.FieldConfig)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginConfigUpsert) SetUpdatedAt(v time.Time) *PluginConfigUpsert {
	u.Set(pluginconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginConfigUpsert) UpdateUpdatedAt() *PluginConfigUpsert {
	u.SetExcluded(pluginconfig.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PluginConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pluginconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PluginConfigUpsertOne) UpdateNewValues() *PluginConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(pluginconfig.FieldID)
		}
		if _, exists := u.create.mutation.PluginID(); exists {
			s.SetIgnore(pluginconfig.FieldPluginID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PluginConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PluginConfigUpsertOne) Ignore() *PluginConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginConfigUpsertOne) DoNothing() *PluginConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginConfigCreate.OnConflict
// documentation for more info.
func (u *PluginConfigUpsertOne) Update(set func(*PluginConfigUpsert)) *PluginConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetConfig sets the "config" field.
func (u *PluginConfigUpsertOne) SetConfig(v string) *PluginConfigUpsertOne {
	return u.Update(func(s *PluginConfigUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *PluginConfigUpsertOne) UpdateConfig() *PluginConfigUpsertOne {
	return u.Update(func(s *PluginConfigUpsert) {
		s.UpdateConfig()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginConfigUpsertOne) SetUpdatedAt(v time.Time) *PluginConfigUpsertOne {
	return u.Update(func(s *PluginConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginConfigUpsertOne) UpdateUpdatedAt() *PluginConfigUpsertOne {
	return u.Update(func(s *PluginConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PluginConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PluginConfigUpsertOne) ID(ctx context.Context) (id core.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PluginConfigUpsertOne.ID is not supported by MySQL driver. Use PluginConfigUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PluginConfigUpsertOne) IDX(ctx context.Context) core.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PluginConfigCreateBulk is the builder for creating many PluginConfig entities in bulk.
type PluginConfigCreateBulk struct {
	config
	err      error
	builders []*PluginConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the PluginConfig entities in the database.
func (_c *PluginConfigCreateBulk) Save(ctx context.Context) ([]*PluginConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PluginConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginConfigCreateBulk) SaveX(ctx context.Context) []*PluginConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PluginConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginConfigUpsert) {
//			SetPluginID(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *PluginConfigUpsertBulk {
	_c.conflict = opts
	return &PluginConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PluginConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginConfigCreateBulk) OnConflictColumns(columns ...string) *PluginConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginConfigUpsertBulk{
		create: _c,
	}
}

// PluginConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of PluginConfig nodes.
type PluginConfigUpsertBulk struct {
	create *PluginConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PluginConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pluginconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PluginConfigUpsertBulk) UpdateNewValues() *PluginConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(pluginconfig.FieldID)
			}
			if _, exists := b.mutation.PluginID(); exists {
				s.SetIgnore(pluginconfig.FieldPluginID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PluginConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PluginConfigUpsertBulk) Ignore() *PluginConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginConfigUpsertBulk) DoNothing() *PluginConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginConfigCreateBulk.OnConflict
// documentation for more info.
func (u *PluginConfigUpsertBulk) Update(set func(*PluginConfigUpsert)) *PluginConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetConfig sets the "config" field.
func (u *PluginConfigUpsertBulk) SetConfig(v string) *PluginConfigUpsertBulk {
	return u.Update(func(s *PluginConfigUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *PluginConfigUpsertBulk) UpdateConfig() *PluginConfigUpsertBulk {
	return u.Update(func(s *PluginConfigUpsert) {
		s.UpdateConfig()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginConfigUpsertBulk) SetUpdatedAt(v time.Time) *PluginConfigUpsertBulk {
	return u.Update(func(s *PluginConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginConfigUpsertBulk) UpdateUpdatedAt() *PluginConfigUpsertBulk {
	return u.Update(func(s *PluginConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PluginConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PluginConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
