// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/credit"
	"github.com/mavioai/mavio/libs/store/internal/ent/image"
	"github.com/mavioai/mavio/libs/store/internal/ent/item"
	"github.com/mavioai/mavio/libs/store/internal/ent/itemvalue"
	"github.com/mavioai/mavio/libs/store/internal/ent/job"
	"github.com/mavioai/mavio/libs/store/internal/ent/library"
	"github.com/mavioai/mavio/libs/store/internal/ent/mediasource"
	"github.com/mavioai/mavio/libs/store/internal/ent/person"
	"github.com/mavioai/mavio/libs/store/internal/ent/schema"
	"github.com/mavioai/mavio/libs/store/internal/ent/user"
	"github.com/mavioai/mavio/libs/store/internal/ent/userdata"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	creditFields := schema.Credit{}.Fields()
	_ = creditFields
	// creditDescRole is the schema descriptor for role field.
	creditDescRole := creditFields[3].Descriptor()
	// credit.DefaultRole holds the default value on creation for the role field.
	credit.DefaultRole = creditDescRole.Default.(string)
	// creditDescOrd is the schema descriptor for ord field.
	creditDescOrd := creditFields[4].Descriptor()
	// credit.DefaultOrd holds the default value on creation for the ord field.
	credit.DefaultOrd = creditDescOrd.Default.(int)
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescIndex is the schema descriptor for index field.
	imageDescIndex := imageFields[4].Descriptor()
	// image.DefaultIndex holds the default value on creation for the index field.
	image.DefaultIndex = imageDescIndex.Default.(int)
	// imageDescPath is the schema descriptor for path field.
	imageDescPath := imageFields[5].Descriptor()
	// image.DefaultPath holds the default value on creation for the path field.
	image.DefaultPath = imageDescPath.Default.(string)
	// imageDescRemoteURL is the schema descriptor for remote_url field.
	imageDescRemoteURL := imageFields[6].Descriptor()
	// image.DefaultRemoteURL holds the default value on creation for the remote_url field.
	image.DefaultRemoteURL = imageDescRemoteURL.Default.(string)
	// imageDescWidth is the schema descriptor for width field.
	imageDescWidth := imageFields[7].Descriptor()
	// image.DefaultWidth holds the default value on creation for the width field.
	image.DefaultWidth = imageDescWidth.Default.(int)
	// imageDescHeight is the schema descriptor for height field.
	imageDescHeight := imageFields[8].Descriptor()
	// image.DefaultHeight holds the default value on creation for the height field.
	image.DefaultHeight = imageDescHeight.Default.(int)
	// imageDescBlurhash is the schema descriptor for blurhash field.
	imageDescBlurhash := imageFields[9].Descriptor()
	// image.DefaultBlurhash holds the default value on creation for the blurhash field.
	image.DefaultBlurhash = imageDescBlurhash.Default.(string)
	// imageDescID is the schema descriptor for id field.
	imageDescID := imageFields[0].Descriptor()
	// image.DefaultID holds the default value on creation for the id field.
	image.DefaultID = imageDescID.Default.(func() core.ID)
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescOriginalTitle is the schema descriptor for original_title field.
	itemDescOriginalTitle := itemFields[7].Descriptor()
	// item.DefaultOriginalTitle holds the default value on creation for the original_title field.
	item.DefaultOriginalTitle = itemDescOriginalTitle.Default.(string)
	// itemDescSearchKey is the schema descriptor for search_key field.
	itemDescSearchKey := itemFields[8].Descriptor()
	// item.DefaultSearchKey holds the default value on creation for the search_key field.
	item.DefaultSearchKey = itemDescSearchKey.Default.(string)
	// itemDescOriginalKey is the schema descriptor for original_key field.
	itemDescOriginalKey := itemFields[9].Descriptor()
	// item.DefaultOriginalKey holds the default value on creation for the original_key field.
	item.DefaultOriginalKey = itemDescOriginalKey.Default.(string)
	// itemDescOverview is the schema descriptor for overview field.
	itemDescOverview := itemFields[10].Descriptor()
	// item.DefaultOverview holds the default value on creation for the overview field.
	item.DefaultOverview = itemDescOverview.Default.(string)
	// itemDescTagline is the schema descriptor for tagline field.
	itemDescTagline := itemFields[11].Descriptor()
	// item.DefaultTagline holds the default value on creation for the tagline field.
	item.DefaultTagline = itemDescTagline.Default.(string)
	// itemDescPath is the schema descriptor for path field.
	itemDescPath := itemFields[12].Descriptor()
	// item.DefaultPath holds the default value on creation for the path field.
	item.DefaultPath = itemDescPath.Default.(string)
	// itemDescProductionYear is the schema descriptor for production_year field.
	itemDescProductionYear := itemFields[16].Descriptor()
	// item.DefaultProductionYear holds the default value on creation for the production_year field.
	item.DefaultProductionYear = itemDescProductionYear.Default.(int)
	// itemDescRuntime is the schema descriptor for runtime field.
	itemDescRuntime := itemFields[19].Descriptor()
	// item.DefaultRuntime holds the default value on creation for the runtime field.
	item.DefaultRuntime = time.Duration(itemDescRuntime.Default.(int64))
	// itemDescOfficialRating is the schema descriptor for official_rating field.
	itemDescOfficialRating := itemFields[20].Descriptor()
	// item.DefaultOfficialRating holds the default value on creation for the official_rating field.
	item.DefaultOfficialRating = itemDescOfficialRating.Default.(string)
	// itemDescParentalRating is the schema descriptor for parental_rating field.
	itemDescParentalRating := itemFields[21].Descriptor()
	// item.DefaultParentalRating holds the default value on creation for the parental_rating field.
	item.DefaultParentalRating = itemDescParentalRating.Default.(int)
	// itemDescCommunityRating is the schema descriptor for community_rating field.
	itemDescCommunityRating := itemFields[22].Descriptor()
	// item.DefaultCommunityRating holds the default value on creation for the community_rating field.
	item.DefaultCommunityRating = itemDescCommunityRating.Default.(float64)
	// itemDescCriticRating is the schema descriptor for critic_rating field.
	itemDescCriticRating := itemFields[23].Descriptor()
	// item.DefaultCriticRating holds the default value on creation for the critic_rating field.
	item.DefaultCriticRating = itemDescCriticRating.Default.(float64)
	// itemDescSeriesStatus is the schema descriptor for series_status field.
	itemDescSeriesStatus := itemFields[25].Descriptor()
	// item.DefaultSeriesStatus holds the default value on creation for the series_status field.
	item.DefaultSeriesStatus = itemDescSeriesStatus.Default.(string)
	// itemDescExtra is the schema descriptor for extra field.
	itemDescExtra := itemFields[26].Descriptor()
	// item.DefaultExtra holds the default value on creation for the extra field.
	item.DefaultExtra = itemDescExtra.Default.(string)
	// itemDescID is the schema descriptor for id field.
	itemDescID := itemFields[0].Descriptor()
	// item.DefaultID holds the default value on creation for the id field.
	item.DefaultID = itemDescID.Default.(func() core.ID)
	itemvalueFields := schema.ItemValue{}.Fields()
	_ = itemvalueFields
	// itemvalueDescValueKey is the schema descriptor for value_key field.
	itemvalueDescValueKey := itemvalueFields[3].Descriptor()
	// itemvalue.DefaultValueKey holds the default value on creation for the value_key field.
	itemvalue.DefaultValueKey = itemvalueDescValueKey.Default.(string)
	// itemvalueDescSortKey is the schema descriptor for sort_key field.
	itemvalueDescSortKey := itemvalueFields[4].Descriptor()
	// itemvalue.DefaultSortKey holds the default value on creation for the sort_key field.
	itemvalue.DefaultSortKey = itemvalueDescSortKey.Default.(string)
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescUniqueKey is the schema descriptor for unique_key field.
	jobDescUniqueKey := jobFields[3].Descriptor()
	// job.DefaultUniqueKey holds the default value on creation for the unique_key field.
	job.DefaultUniqueKey = jobDescUniqueKey.Default.(string)
	// jobDescPriority is the schema descriptor for priority field.
	jobDescPriority := jobFields[5].Descriptor()
	// job.DefaultPriority holds the default value on creation for the priority field.
	job.DefaultPriority = jobDescPriority.Default.(int)
	// jobDescAttempts is the schema descriptor for attempts field.
	jobDescAttempts := jobFields[6].Descriptor()
	// job.DefaultAttempts holds the default value on creation for the attempts field.
	job.DefaultAttempts = jobDescAttempts.Default.(int)
	// jobDescLeaseOwner is the schema descriptor for lease_owner field.
	jobDescLeaseOwner := jobFields[9].Descriptor()
	// job.DefaultLeaseOwner holds the default value on creation for the lease_owner field.
	job.DefaultLeaseOwner = jobDescLeaseOwner.Default.(string)
	// jobDescLastError is the schema descriptor for last_error field.
	jobDescLastError := jobFields[11].Descriptor()
	// job.DefaultLastError holds the default value on creation for the last_error field.
	job.DefaultLastError = jobDescLastError.Default.(string)
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobFields[12].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() time.Time)
	// jobDescID is the schema descriptor for id field.
	jobDescID := jobFields[0].Descriptor()
	// job.DefaultID holds the default value on creation for the id field.
	job.DefaultID = jobDescID.Default.(func() core.ID)
	libraryFields := schema.Library{}.Fields()
	_ = libraryFields
	// libraryDescName is the schema descriptor for name field.
	libraryDescName := libraryFields[1].Descriptor()
	// library.NameValidator is a validator for the "name" field. It is called by the builders before save.
	library.NameValidator = libraryDescName.Validators[0].(func(string) error)
	// libraryDescScanInterval is the schema descriptor for scan_interval field.
	libraryDescScanInterval := libraryFields[4].Descriptor()
	// library.DefaultScanInterval holds the default value on creation for the scan_interval field.
	library.DefaultScanInterval = time.Duration(libraryDescScanInterval.Default.(int64))
	// libraryDescPreferredLanguage is the schema descriptor for preferred_language field.
	libraryDescPreferredLanguage := libraryFields[5].Descriptor()
	// library.DefaultPreferredLanguage holds the default value on creation for the preferred_language field.
	library.DefaultPreferredLanguage = libraryDescPreferredLanguage.Default.(string)
	// libraryDescMetadataCountry is the schema descriptor for metadata_country field.
	libraryDescMetadataCountry := libraryFields[6].Descriptor()
	// library.DefaultMetadataCountry holds the default value on creation for the metadata_country field.
	library.DefaultMetadataCountry = libraryDescMetadataCountry.Default.(string)
	// libraryDescCreatedAt is the schema descriptor for created_at field.
	libraryDescCreatedAt := libraryFields[7].Descriptor()
	// library.DefaultCreatedAt holds the default value on creation for the created_at field.
	library.DefaultCreatedAt = libraryDescCreatedAt.Default.(func() time.Time)
	// libraryDescUpdatedAt is the schema descriptor for updated_at field.
	libraryDescUpdatedAt := libraryFields[8].Descriptor()
	// library.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	library.DefaultUpdatedAt = libraryDescUpdatedAt.Default.(func() time.Time)
	// library.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	library.UpdateDefaultUpdatedAt = libraryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// libraryDescID is the schema descriptor for id field.
	libraryDescID := libraryFields[0].Descriptor()
	// library.DefaultID holds the default value on creation for the id field.
	library.DefaultID = libraryDescID.Default.(func() core.ID)
	mediasourceFields := schema.MediaSource{}.Fields()
	_ = mediasourceFields
	// mediasourceDescName is the schema descriptor for name field.
	mediasourceDescName := mediasourceFields[4].Descriptor()
	// mediasource.DefaultName holds the default value on creation for the name field.
	mediasource.DefaultName = mediasourceDescName.Default.(string)
	// mediasourceDescContainer is the schema descriptor for container field.
	mediasourceDescContainer := mediasourceFields[5].Descriptor()
	// mediasource.DefaultContainer holds the default value on creation for the container field.
	mediasource.DefaultContainer = mediasourceDescContainer.Default.(string)
	// mediasourceDescSize is the schema descriptor for size field.
	mediasourceDescSize := mediasourceFields[6].Descriptor()
	// mediasource.DefaultSize holds the default value on creation for the size field.
	mediasource.DefaultSize = mediasourceDescSize.Default.(int64)
	// mediasourceDescDuration is the schema descriptor for duration field.
	mediasourceDescDuration := mediasourceFields[7].Descriptor()
	// mediasource.DefaultDuration holds the default value on creation for the duration field.
	mediasource.DefaultDuration = time.Duration(mediasourceDescDuration.Default.(int64))
	// mediasourceDescBitrate is the schema descriptor for bitrate field.
	mediasourceDescBitrate := mediasourceFields[8].Descriptor()
	// mediasource.DefaultBitrate holds the default value on creation for the bitrate field.
	mediasource.DefaultBitrate = mediasourceDescBitrate.Default.(int64)
	// mediasourceDescID is the schema descriptor for id field.
	mediasourceDescID := mediasourceFields[0].Descriptor()
	// mediasource.DefaultID holds the default value on creation for the id field.
	mediasource.DefaultID = mediasourceDescID.Default.(func() core.ID)
	personFields := schema.Person{}.Fields()
	_ = personFields
	// personDescName is the schema descriptor for name field.
	personDescName := personFields[1].Descriptor()
	// person.NameValidator is a validator for the "name" field. It is called by the builders before save.
	person.NameValidator = personDescName.Validators[0].(func(string) error)
	// personDescSortName is the schema descriptor for sort_name field.
	personDescSortName := personFields[3].Descriptor()
	// person.DefaultSortName holds the default value on creation for the sort_name field.
	person.DefaultSortName = personDescSortName.Default.(string)
	// personDescSearchKey is the schema descriptor for search_key field.
	personDescSearchKey := personFields[4].Descriptor()
	// person.DefaultSearchKey holds the default value on creation for the search_key field.
	person.DefaultSearchKey = personDescSearchKey.Default.(string)
	// personDescSortKey is the schema descriptor for sort_key field.
	personDescSortKey := personFields[5].Descriptor()
	// person.DefaultSortKey holds the default value on creation for the sort_key field.
	person.DefaultSortKey = personDescSortKey.Default.(string)
	// personDescOverview is the schema descriptor for overview field.
	personDescOverview := personFields[6].Descriptor()
	// person.DefaultOverview holds the default value on creation for the overview field.
	person.DefaultOverview = personDescOverview.Default.(string)
	// personDescBirthPlace is the schema descriptor for birth_place field.
	personDescBirthPlace := personFields[9].Descriptor()
	// person.DefaultBirthPlace holds the default value on creation for the birth_place field.
	person.DefaultBirthPlace = personDescBirthPlace.Default.(string)
	// personDescID is the schema descriptor for id field.
	personDescID := personFields[0].Descriptor()
	// person.DefaultID holds the default value on creation for the id field.
	person.DefaultID = personDescID.Default.(func() core.ID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.DefaultPasswordHash holds the default value on creation for the password_hash field.
	user.DefaultPasswordHash = userDescPasswordHash.Default.(string)
	// userDescAuthProvider is the schema descriptor for auth_provider field.
	userDescAuthProvider := userFields[4].Descriptor()
	// user.DefaultAuthProvider holds the default value on creation for the auth_provider field.
	user.DefaultAuthProvider = userDescAuthProvider.Default.(string)
	// userDescAdmin is the schema descriptor for admin field.
	userDescAdmin := userFields[5].Descriptor()
	// user.DefaultAdmin holds the default value on creation for the admin field.
	user.DefaultAdmin = userDescAdmin.Default.(bool)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[6].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() core.ID)
	userdataFields := schema.UserData{}.Fields()
	_ = userdataFields
	// userdataDescPlayed is the schema descriptor for played field.
	userdataDescPlayed := userdataFields[2].Descriptor()
	// userdata.DefaultPlayed holds the default value on creation for the played field.
	userdata.DefaultPlayed = userdataDescPlayed.Default.(bool)
	// userdataDescPlayCount is the schema descriptor for play_count field.
	userdataDescPlayCount := userdataFields[3].Descriptor()
	// userdata.DefaultPlayCount holds the default value on creation for the play_count field.
	userdata.DefaultPlayCount = userdataDescPlayCount.Default.(int)
	// userdataDescPosition is the schema descriptor for position field.
	userdataDescPosition := userdataFields[4].Descriptor()
	// userdata.DefaultPosition holds the default value on creation for the position field.
	userdata.DefaultPosition = time.Duration(userdataDescPosition.Default.(int64))
	// userdataDescFavorite is the schema descriptor for favorite field.
	userdataDescFavorite := userdataFields[7].Descriptor()
	// userdata.DefaultFavorite holds the default value on creation for the favorite field.
	userdata.DefaultFavorite = userdataDescFavorite.Default.(bool)
	// userdataDescUpdatedAt is the schema descriptor for updated_at field.
	userdataDescUpdatedAt := userdataFields[10].Descriptor()
	// userdata.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userdata.DefaultUpdatedAt = userdataDescUpdatedAt.Default.(func() time.Time)
	// userdata.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userdata.UpdateDefaultUpdatedAt = userdataDescUpdatedAt.UpdateDefault.(func() time.Time)
}
