// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
	"github.com/mavioai/mavio/libs/store/internal/ent/user"
	"github.com/mavioai/mavio/libs/store/internal/ent/userdata"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks     []Hook
	mutation  *UserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameKey sets the "name_key" field.
func (_u *UserUpdate) SetNameKey(v string) *UserUpdate {
	_u.mutation.SetNameKey(v)
	return _u
}

// SetNillableNameKey sets the "name_key" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNameKey(v *string) *UserUpdate {
	if v != nil {
		_u.SetNameKey(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetAuthProvider sets the "auth_provider" field.
func (_u *UserUpdate) SetAuthProvider(v string) *UserUpdate {
	_u.mutation.SetAuthProvider(v)
	return _u
}

// SetNillableAuthProvider sets the "auth_provider" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAuthProvider(v *string) *UserUpdate {
	if v != nil {
		_u.SetAuthProvider(*v)
	}
	return _u
}

// SetAdmin sets the "admin" field.
func (_u *UserUpdate) SetAdmin(v bool) *UserUpdate {
	_u.mutation.SetAdmin(v)
	return _u
}

// SetNillableAdmin sets the "admin" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAdmin(v *bool) *UserUpdate {
	if v != nil {
		_u.SetAdmin(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *UserUpdate) SetDisabled(v bool) *UserUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDisabled(v *bool) *UserUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetPolicy sets the "policy" field.
func (_u *UserUpdate) SetPolicy(v core.UserPolicy) *UserUpdate {
	_u.mutation.SetPolicy(v)
	return _u
}

// SetNillablePolicy sets the "policy" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePolicy(v *core.UserPolicy) *UserUpdate {
	if v != nil {
		_u.SetPolicy(*v)
	}
	return _u
}

// SetPreferences sets the "preferences" field.
func (_u *UserUpdate) SetPreferences(v core.UserPreferences) *UserUpdate {
	_u.mutation.SetPreferences(v)
	return _u
}

// SetNillablePreferences sets the "preferences" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePreferences(v *core.UserPreferences) *UserUpdate {
	if v != nil {
		_u.SetPreferences(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdate) SetLastLoginAt(v time.Time) *UserUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastLoginAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *UserUpdate) ClearLastLoginAt() *UserUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// AddUserDatumIDs adds the "user_data" edge to the UserData entity by IDs.
func (_u *UserUpdate) AddUserDatumIDs(ids ...int) *UserUpdate {
	_u.mutation.AddUserDatumIDs(ids...)
	return _u
}

// AddUserData adds the "user_data" edges to the UserData entity.
func (_u *UserUpdate) AddUserData(v ...*UserData) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserDatumIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearUserData clears all "user_data" edges to the UserData entity.
func (_u *UserUpdate) ClearUserData() *UserUpdate {
	_u.mutation.ClearUserData()
	return _u
}

// RemoveUserDatumIDs removes the "user_data" edge to UserData entities by IDs.
func (_u *UserUpdate) RemoveUserDatumIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveUserDatumIDs(ids...)
	return _u
}

// RemoveUserData removes "user_data" edges to UserData entities.
func (_u *UserUpdate) RemoveUserData(v ...*UserData) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserDatumIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameKey(); ok {
		_spec.SetField(user.FieldNameKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthProvider(); ok {
		_spec.SetField(user.FieldAuthProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Admin(); ok {
		_spec.SetField(user.FieldAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(user.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Policy(); ok {
		_spec.SetField(user.FieldPolicy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Preferences(); ok {
		_spec.SetField(user.FieldPreferences, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(user.FieldLastLoginAt, field.TypeTime)
	}
	if _u.mutation.UserDataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDataTable,
			Columns: []string{user.UserDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdata.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserDataIDs(); len(nodes) > 0 && !_u.mutation.UserDataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDataTable,
			Columns: []string{user.UserDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserDataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDataTable,
			Columns: []string{user.UserDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameKey sets the "name_key" field.
func (_u *UserUpdateOne) SetNameKey(v string) *UserUpdateOne {
	_u.mutation.SetNameKey(v)
	return _u
}

// SetNillableNameKey sets the "name_key" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNameKey(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetNameKey(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetAuthProvider sets the "auth_provider" field.
func (_u *UserUpdateOne) SetAuthProvider(v string) *UserUpdateOne {
	_u.mutation.SetAuthProvider(v)
	return _u
}

// SetNillableAuthProvider sets the "auth_provider" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAuthProvider(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAuthProvider(*v)
	}
	return _u
}

// SetAdmin sets the "admin" field.
func (_u *UserUpdateOne) SetAdmin(v bool) *UserUpdateOne {
	_u.mutation.SetAdmin(v)
	return _u
}

// SetNillableAdmin sets the "admin" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAdmin(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetAdmin(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *UserUpdateOne) SetDisabled(v bool) *UserUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDisabled(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetPolicy sets the "policy" field.
func (_u *UserUpdateOne) SetPolicy(v core.UserPolicy) *UserUpdateOne {
	_u.mutation.SetPolicy(v)
	return _u
}

// SetNillablePolicy sets the "policy" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePolicy(v *core.UserPolicy) *UserUpdateOne {
	if v != nil {
		_u.SetPolicy(*v)
	}
	return _u
}

// SetPreferences sets the "preferences" field.
func (_u *UserUpdateOne) SetPreferences(v core.UserPreferences) *UserUpdateOne {
	_u.mutation.SetPreferences(v)
	return _u
}

// SetNillablePreferences sets the "preferences" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePreferences(v *core.UserPreferences) *UserUpdateOne {
	if v != nil {
		_u.SetPreferences(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdateOne) SetLastLoginAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastLoginAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *UserUpdateOne) ClearLastLoginAt() *UserUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// AddUserDatumIDs adds the "user_data" edge to the UserData entity by IDs.
func (_u *UserUpdateOne) AddUserDatumIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddUserDatumIDs(ids...)
	return _u
}

// AddUserData adds the "user_data" edges to the UserData entity.
func (_u *UserUpdateOne) AddUserData(v ...*UserData) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserDatumIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearUserData clears all "user_data" edges to the UserData entity.
func (_u *UserUpdateOne) ClearUserData() *UserUpdateOne {
	_u.mutation.ClearUserData()
	return _u
}

// RemoveUserDatumIDs removes the "user_data" edge to UserData entities by IDs.
func (_u *UserUpdateOne) RemoveUserDatumIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveUserDatumIDs(ids...)
	return _u
}

// RemoveUserData removes "user_data" edges to UserData entities.
func (_u *UserUpdateOne) RemoveUserData(v ...*UserData) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserDatumIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameKey(); ok {
		_spec.SetField(user.FieldNameKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthProvider(); ok {
		_spec.SetField(user.FieldAuthProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Admin(); ok {
		_spec.SetField(user.FieldAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(user.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Policy(); ok {
		_spec.SetField(user.FieldPolicy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Preferences(); ok {
		_spec.SetField(user.FieldPreferences, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(user.FieldLastLoginAt, field.TypeTime)
	}
	if _u.mutation.UserDataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDataTable,
			Columns: []string{user.UserDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdata.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserDataIDs(); len(nodes) > 0 && !_u.mutation.UserDataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDataTable,
			Columns: []string{user.UserDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserDataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDataTable,
			Columns: []string{user.UserDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
