// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/authsession"
	"github.com/mavioai/mavio/libs/store/internal/ent/item"
	"github.com/mavioai/mavio/libs/store/internal/ent/user"
	"github.com/mavioai/mavio/libs/store/internal/ent/userdata"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNameKey sets the "name_key" field.
func (_c *UserCreate) SetNameKey(v string) *UserCreate {
	_c.mutation.SetNameKey(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *UserCreate) SetPasswordHash(v string) *UserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_c *UserCreate) SetNillablePasswordHash(v *string) *UserCreate {
	if v != nil {
		_c.SetPasswordHash(*v)
	}
	return _c
}

// SetAuthProvider sets the "auth_provider" field.
func (_c *UserCreate) SetAuthProvider(v string) *UserCreate {
	_c.mutation.SetAuthProvider(v)
	return _c
}

// SetNillableAuthProvider sets the "auth_provider" field if the given value is not nil.
func (_c *UserCreate) SetNillableAuthProvider(v *string) *UserCreate {
	if v != nil {
		_c.SetAuthProvider(*v)
	}
	return _c
}

// SetAdmin sets the "admin" field.
func (_c *UserCreate) SetAdmin(v bool) *UserCreate {
	_c.mutation.SetAdmin(v)
	return _c
}

// SetNillableAdmin sets the "admin" field if the given value is not nil.
func (_c *UserCreate) SetNillableAdmin(v *bool) *UserCreate {
	if v != nil {
		_c.SetAdmin(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *UserCreate) SetDisabled(v bool) *UserCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *UserCreate) SetNillableDisabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetPolicy sets the "policy" field.
func (_c *UserCreate) SetPolicy(v core.UserPolicy) *UserCreate {
	_c.mutation.SetPolicy(v)
	return _c
}

// SetPreferences sets the "preferences" field.
func (_c *UserCreate) SetPreferences(v core.UserPreferences) *UserCreate {
	_c.mutation.SetPreferences(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetLastLoginAt sets the "last_login_at" field.
func (_c *UserCreate) SetLastLoginAt(v time.Time) *UserCreate {
	_c.mutation.SetLastLoginAt(v)
	return _c
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableLastLoginAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetLastLoginAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v core.ID) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserCreate) SetNillableID(v *core.ID) *UserCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddUserDatumIDs adds the "user_data" edge to the UserData entity by IDs.
func (_c *UserCreate) AddUserDatumIDs(ids ...int) *UserCreate {
	_c.mutation.AddUserDatumIDs(ids...)
	return _c
}

// AddUserData adds the "user_data" edges to the UserData entity.
func (_c *UserCreate) AddUserData(v ...*UserData) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserDatumIDs(ids...)
}

// AddAuthSessionIDs adds the "auth_sessions" edge to the AuthSession entity by IDs.
func (_c *UserCreate) AddAuthSessionIDs(ids ...core.ID) *UserCreate {
	_c.mutation.AddAuthSessionIDs(ids...)
	return _c
}

// AddAuthSessions adds the "auth_sessions" edges to the AuthSession entity.
func (_c *UserCreate) AddAuthSessions(v ...*AuthSession) *UserCreate {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuthSessionIDs(ids...)
}

// AddPlaylistIDs adds the "playlists" edge to the Item entity by IDs.
func (_c *UserCreate) AddPlaylistIDs(ids ...core.ID) *UserCreate {
	_c.mutation.AddPlaylistIDs(ids...)
	return _c
}

// AddPlaylists adds the "playlists" edges to the Item entity.
func (_c *UserCreate) AddPlaylists(v ...*Item) *UserCreate {
	ids := make([]core.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPlaylistIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.PasswordHash(); !ok {
		v := user.DefaultPasswordHash
		_c.mutation.SetPasswordHash(v)
	}
	if _, ok := _c.mutation.AuthProvider(); !ok {
		v := user.DefaultAuthProvider
		_c.mutation.SetAuthProvider(v)
	}
	if _, ok := _c.mutation.Admin(); !ok {
		v := user.DefaultAdmin
		_c.mutation.SetAdmin(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := user.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := user.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameKey(); !ok {
		return &ValidationError{Name: "name_key", err: errors.New(`ent: missing required field "User.name_key"`)}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "User.password_hash"`)}
	}
	if _, ok := _c.mutation.AuthProvider(); !ok {
		return &ValidationError{Name: "auth_provider", err: errors.New(`ent: missing required field "User.auth_provider"`)}
	}
	if _, ok := _c.mutation.Admin(); !ok {
		return &ValidationError{Name: "admin", err: errors.New(`ent: missing required field "User.admin"`)}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "User.disabled"`)}
	}
	if _, ok := _c.mutation.Policy(); !ok {
		return &ValidationError{Name: "policy", err: errors.New(`ent: missing required field "User.policy"`)}
	}
	if _, ok := _c.mutation.Preferences(); !ok {
		return &ValidationError{Name: "preferences", err: errors.New(`ent: missing required field "User.preferences"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*core.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NameKey(); ok {
		_spec.SetField(user.FieldNameKey, field.TypeString, value)
		_node.NameKey = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.AuthProvider(); ok {
		_spec.SetField(user.FieldAuthProvider, field.TypeString, value)
		_node.AuthProvider = value
	}
	if value, ok := _c.mutation.Admin(); ok {
		_spec.SetField(user.FieldAdmin, field.TypeBool, value)
		_node.Admin = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(user.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.Policy(); ok {
		_spec.SetField(user.FieldPolicy, field.TypeJSON, value)
		_node.Policy = value
	}
	if value, ok := _c.mutation.Preferences(); ok {
		_spec.SetField(user.FieldPreferences, field.TypeJSON, value)
		_node.Preferences = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = &value
	}
	if nodes := _c.mutation.UserDataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDataTable,
			Columns: []string{user.UserDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuthSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AuthSessionsTable,
			Columns: []string{user.AuthSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlaylistsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PlaylistsTable,
			Columns: []string{user.PlaylistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreate) OnConflict(opts ...sql.ConflictOption) *UserUpsertOne {
	_c.conflict = opts
	return &UserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreate) OnConflictColumns(columns ...string) *UserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertOne{
		create: _c,
	}
}

type (
	// UserUpsertOne is the builder for "upsert"-ing
	//  one User node.
	UserUpsertOne struct {
		create *UserCreate
	}

	// UserUpsert is the "OnConflict" setter.
	UserUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *UserUpsert) SetName(v string) *UserUpsert {
	u.Set(user.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUpsert) UpdateName() *UserUpsert {
	u.SetExcluded(user.FieldName)
	return u
}

// SetNameKey sets the "name_key" field.
func (u *UserUpsert) SetNameKey(v string) *UserUpsert {
	u.Set(user.FieldNameKey, v)
	return u
}

// UpdateNameKey sets the "name_key" field to the value that was provided on create.
func (u *UserUpsert) UpdateNameKey() *UserUpsert {
	u.SetExcluded(user.FieldNameKey)
	return u
}

// SetPasswordHash sets the "password_hash" field.
func (u *UserUpsert) SetPasswordHash(v string) *UserUpsert {
	u.Set(user.FieldPasswordHash, v)
	return u
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *UserUpsert) UpdatePasswordHash() *UserUpsert {
	u.SetExcluded(user.FieldPasswordHash)
	return u
}

// SetAuthProvider sets the "auth_provider" field.
func (u *UserUpsert) SetAuthProvider(v string) *UserUpsert {
	u.Set(user.FieldAuthProvider, v)
	return u
}

// UpdateAuthProvider sets the "auth_provider" field to the value that was provided on create.
func (u *UserUpsert) UpdateAuthProvider() *UserUpsert {
	u.SetExcluded(user.FieldAuthProvider)
	return u
}

// SetAdmin sets the "admin" field.
func (u *UserUpsert) SetAdmin(v bool) *UserUpsert {
	u.Set(user.FieldAdmin, v)
	return u
}

// UpdateAdmin sets the "admin" field to the value that was provided on create.
func (u *UserUpsert) UpdateAdmin() *UserUpsert {
	u.SetExcluded(user.FieldAdmin)
	return u
}

// SetDisabled sets the "disabled" field.
func (u *UserUpsert) SetDisabled(v bool) *UserUpsert {
	u.Set(user.FieldDisabled, v)
	return u
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *UserUpsert) UpdateDisabled() *UserUpsert {
	u.SetExcluded(user.FieldDisabled)
	return u
}

// SetPolicy sets the "policy" field.
func (u *UserUpsert) SetPolicy(v core.UserPolicy) *UserUpsert {
	u.Set(user.FieldPolicy, v)
	return u
}

// UpdatePolicy sets the "policy" field to the value that was provided on create.
func (u *UserUpsert) UpdatePolicy() *UserUpsert {
	u.SetExcluded(user.FieldPolicy)
	return u
}

// SetPreferences sets the "preferences" field.
func (u *UserUpsert) SetPreferences(v core.UserPreferences) *UserUpsert {
	u.Set(user.FieldPreferences, v)
	return u
}

// UpdatePreferences sets the "preferences" field to the value that was provided on create.
func (u *UserUpsert) UpdatePreferences() *UserUpsert {
	u.SetExcluded(user.FieldPreferences)
	return u
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *UserUpsert) SetLastLoginAt(v time.Time) *UserUpsert {
	u.Set(user.FieldLastLoginAt, v)
	return u
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateLastLoginAt() *UserUpsert {
	u.SetExcluded(user.FieldLastLoginAt)
	return u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *UserUpsert) ClearLastLoginAt() *UserUpsert {
	u.SetNull(user.FieldLastLoginAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(user.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserUpsertOne) UpdateNewValues() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(user.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(user.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserUpsertOne) Ignore() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertOne) DoNothing() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreate.OnConflict
// documentation for more info.
func (u *UserUpsertOne) Update(set func(*UserUpsert)) *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *UserUpsertOne) SetName(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateName() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateName()
	})
}

// SetNameKey sets the "name_key" field.
func (u *UserUpsertOne) SetNameKey(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetNameKey(v)
	})
}

// UpdateNameKey sets the "name_key" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateNameKey() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateNameKey()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *UserUpsertOne) SetPasswordHash(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *UserUpsertOne) UpdatePasswordHash() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetAuthProvider sets the "auth_provider" field.
func (u *UserUpsertOne) SetAuthProvider(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAuthProvider(v)
	})
}

// UpdateAuthProvider sets the "auth_provider" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAuthProvider() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAuthProvider()
	})
}

// SetAdmin sets the "admin" field.
func (u *UserUpsertOne) SetAdmin(v bool) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAdmin(v)
	})
}

// UpdateAdmin sets the "admin" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAdmin() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAdmin()
	})
}

// SetDisabled sets the "disabled" field.
func (u *UserUpsertOne) SetDisabled(v bool) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateDisabled() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDisabled()
	})
}

// SetPolicy sets the "policy" field.
func (u *UserUpsertOne) SetPolicy(v core.UserPolicy) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetPolicy(v)
	})
}

// UpdatePolicy sets the "policy" field to the value that was provided on create.
func (u *UserUpsertOne) UpdatePolicy() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePolicy()
	})
}

// SetPreferences sets the "preferences" field.
func (u *UserUpsertOne) SetPreferences(v core.UserPreferences) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetPreferences(v)
	})
}

// UpdatePreferences sets the "preferences" field to the value that was provided on create.
func (u *UserUpsertOne) UpdatePreferences() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePreferences()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *UserUpsertOne) SetLastLoginAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateLastLoginAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *UserUpsertOne) ClearLastLoginAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearLastLoginAt()
	})
}

// Exec executes the query.
func (u *UserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserUpsertOne) ID(ctx context.Context) (id core.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UserUpsertOne.ID is not supported by MySQL driver. Use UserUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserUpsertOne) IDX(ctx context.Context) core.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
	conflict []sql.ConflictOption
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserUpsertBulk {
	_c.conflict = opts
	return &UserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreateBulk) OnConflictColumns(columns ...string) *UserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertBulk{
		create: _c,
	}
}

// UserUpsertBulk is the builder for "upsert"-ing
// a bulk of User nodes.
type UserUpsertBulk struct {
	create *UserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(user.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserUpsertBulk) UpdateNewValues() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(user.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(user.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserUpsertBulk) Ignore() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertBulk) DoNothing() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreateBulk.OnConflict
// documentation for more info.
func (u *UserUpsertBulk) Update(set func(*UserUpsert)) *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *UserUpsertBulk) SetName(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateName() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateName()
	})
}

// SetNameKey sets the "name_key" field.
func (u *UserUpsertBulk) SetNameKey(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetNameKey(v)
	})
}

// UpdateNameKey sets the "name_key" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateNameKey() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateNameKey()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *UserUpsertBulk) SetPasswordHash(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdatePasswordHash() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetAuthProvider sets the "auth_provider" field.
func (u *UserUpsertBulk) SetAuthProvider(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAuthProvider(v)
	})
}

// UpdateAuthProvider sets the "auth_provider" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAuthProvider() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAuthProvider()
	})
}

// SetAdmin sets the "admin" field.
func (u *UserUpsertBulk) SetAdmin(v bool) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAdmin(v)
	})
}

// UpdateAdmin sets the "admin" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAdmin() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAdmin()
	})
}

// SetDisabled sets the "disabled" field.
func (u *UserUpsertBulk) SetDisabled(v bool) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateDisabled() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDisabled()
	})
}

// SetPolicy sets the "policy" field.
func (u *UserUpsertBulk) SetPolicy(v core.UserPolicy) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetPolicy(v)
	})
}

// UpdatePolicy sets the "policy" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdatePolicy() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePolicy()
	})
}

// SetPreferences sets the "preferences" field.
func (u *UserUpsertBulk) SetPreferences(v core.UserPreferences) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetPreferences(v)
	})
}

// UpdatePreferences sets the "preferences" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdatePreferences() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePreferences()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *UserUpsertBulk) SetLastLoginAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateLastLoginAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *UserUpsertBulk) ClearLastLoginAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearLastLoginAt()
	})
}

// Exec executes the query.
func (u *UserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
