// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mavioai/mavio/libs/core"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNameKey holds the string denoting the name_key field in the database.
	FieldNameKey = "name_key"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldAuthProvider holds the string denoting the auth_provider field in the database.
	FieldAuthProvider = "auth_provider"
	// FieldAdmin holds the string denoting the admin field in the database.
	FieldAdmin = "admin"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldPolicy holds the string denoting the policy field in the database.
	FieldPolicy = "policy"
	// FieldPreferences holds the string denoting the preferences field in the database.
	FieldPreferences = "preferences"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// EdgeUserData holds the string denoting the user_data edge name in mutations.
	EdgeUserData = "user_data"
	// EdgeAuthSessions holds the string denoting the auth_sessions edge name in mutations.
	EdgeAuthSessions = "auth_sessions"
	// EdgePlaylists holds the string denoting the playlists edge name in mutations.
	EdgePlaylists = "playlists"
	// EdgeDisplayPreferences holds the string denoting the display_preferences edge name in mutations.
	EdgeDisplayPreferences = "display_preferences"
	// Table holds the table name of the user in the database.
	Table = "users"
	// UserDataTable is the table that holds the user_data relation/edge.
	UserDataTable = "user_data"
	// UserDataInverseTable is the table name for the UserData entity.
	// It exists in this package in order to avoid circular dependency with the "userdata" package.
	UserDataInverseTable = "user_data"
	// UserDataColumn is the table column denoting the user_data relation/edge.
	UserDataColumn = "user_id"
	// AuthSessionsTable is the table that holds the auth_sessions relation/edge.
	AuthSessionsTable = "auth_sessions"
	// AuthSessionsInverseTable is the table name for the AuthSession entity.
	// It exists in this package in order to avoid circular dependency with the "authsession" package.
	AuthSessionsInverseTable = "auth_sessions"
	// AuthSessionsColumn is the table column denoting the auth_sessions relation/edge.
	AuthSessionsColumn = "user_id"
	// PlaylistsTable is the table that holds the playlists relation/edge.
	PlaylistsTable = "items"
	// PlaylistsInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	PlaylistsInverseTable = "items"
	// PlaylistsColumn is the table column denoting the playlists relation/edge.
	PlaylistsColumn = "user_id"
	// DisplayPreferencesTable is the table that holds the display_preferences relation/edge.
	DisplayPreferencesTable = "display_preferences"
	// DisplayPreferencesInverseTable is the table name for the DisplayPreferences entity.
	// It exists in this package in order to avoid circular dependency with the "displaypreferences" package.
	DisplayPreferencesInverseTable = "display_preferences"
	// DisplayPreferencesColumn is the table column denoting the display_preferences relation/edge.
	DisplayPreferencesColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldNameKey,
	FieldPasswordHash,
	FieldAuthProvider,
	FieldAdmin,
	FieldDisabled,
	FieldPolicy,
	FieldPreferences,
	FieldCreatedAt,
	FieldLastLoginAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPasswordHash holds the default value on creation for the "password_hash" field.
	DefaultPasswordHash string
	// DefaultAuthProvider holds the default value on creation for the "auth_provider" field.
	DefaultAuthProvider string
	// DefaultAdmin holds the default value on creation for the "admin" field.
	DefaultAdmin bool
	// DefaultDisabled holds the default value on creation for the "disabled" field.
	DefaultDisabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() core.ID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNameKey orders the results by the name_key field.
func ByNameKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameKey, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByAuthProvider orders the results by the auth_provider field.
func ByAuthProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthProvider, opts...).ToFunc()
}

// ByAdmin orders the results by the admin field.
func ByAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdmin, opts...).ToFunc()
}

// ByDisabled orders the results by the disabled field.
func ByDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// ByUserDataCount orders the results by user_data count.
func ByUserDataCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserDataStep(), opts...)
	}
}

// ByUserData orders the results by user_data terms.
func ByUserData(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserDataStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuthSessionsCount orders the results by auth_sessions count.
func ByAuthSessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuthSessionsStep(), opts...)
	}
}

// ByAuthSessions orders the results by auth_sessions terms.
func ByAuthSessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPlaylistsCount orders the results by playlists count.
func ByPlaylistsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlaylistsStep(), opts...)
	}
}

// ByPlaylists orders the results by playlists terms.
func ByPlaylists(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlaylistsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDisplayPreferencesCount orders the results by display_preferences count.
func ByDisplayPreferencesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDisplayPreferencesStep(), opts...)
	}
}

// ByDisplayPreferences orders the results by display_preferences terms.
func ByDisplayPreferences(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDisplayPreferencesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserDataStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserDataInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserDataTable, UserDataColumn),
	)
}
func newAuthSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthSessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuthSessionsTable, AuthSessionsColumn),
	)
}
func newPlaylistsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlaylistsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PlaylistsTable, PlaylistsColumn),
	)
}
func newDisplayPreferencesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DisplayPreferencesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DisplayPreferencesTable, DisplayPreferencesColumn),
	)
}
