-- Create "jobs" table
CREATE TABLE "jobs" ("id" uuid NOT NULL, "kind" character varying NOT NULL, "payload" bytea NULL, "unique_key" character varying NOT NULL DEFAULT '', "state" character varying NOT NULL, "priority" bigint NOT NULL DEFAULT 0, "attempts" bigint NOT NULL DEFAULT 0, "max_attempts" bigint NOT NULL, "run_at" timestamptz NOT NULL, "lease_owner" character varying NOT NULL DEFAULT '', "lease_expires_at" timestamptz NULL, "last_error" text NOT NULL DEFAULT '', "created_at" timestamptz NOT NULL, "finished_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "job_state_kind_priority_run_at" to table: "jobs"
CREATE INDEX "job_state_kind_priority_run_at" ON "jobs" ("state", "kind", "priority", "run_at");
-- Create index "job_unique_key" to table: "jobs"
CREATE UNIQUE INDEX "job_unique_key" ON "jobs" ("unique_key") WHERE (((unique_key)::text <> ''::text) AND ((state)::text = ANY ((ARRAY['pending'::character varying, 'running'::character varying])::text[])));
-- Create "libraries" table
CREATE TABLE "libraries" ("id" uuid NOT NULL, "name" character varying NOT NULL, "kind" character varying NOT NULL, "paths" jsonb NOT NULL, "scan_interval" bigint NOT NULL DEFAULT 0, "preferred_language" character varying NOT NULL DEFAULT '', "metadata_country" character varying NOT NULL DEFAULT '', "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "items" table
CREATE TABLE "items" ("id" uuid NOT NULL, "kind" character varying NOT NULL, "name" character varying NOT NULL, "sort_name" character varying NOT NULL, "sort_key" character varying NOT NULL, "original_title" character varying NOT NULL DEFAULT '', "search_key" character varying NOT NULL DEFAULT '', "overview" text NOT NULL DEFAULT '', "tagline" character varying NOT NULL DEFAULT '', "path" character varying NOT NULL DEFAULT '', "index_number" bigint NULL, "parent_index_number" bigint NULL, "index_number_end" bigint NULL, "production_year" bigint NOT NULL DEFAULT 0, "premiere_date" timestamptz NULL, "end_date" timestamptz NULL, "runtime" bigint NOT NULL DEFAULT 0, "official_rating" character varying NOT NULL DEFAULT '', "parental_rating" bigint NOT NULL DEFAULT 0, "community_rating" double precision NOT NULL DEFAULT 0, "critic_rating" double precision NOT NULL DEFAULT 0, "external_ids" jsonb NULL, "series_status" character varying NOT NULL DEFAULT '', "extra" character varying NOT NULL DEFAULT '', "date_added" timestamptz NOT NULL, "file_modified" timestamptz NULL, "metadata_refreshed_at" timestamptz NULL, "parent_id" uuid NULL, "owner_id" uuid NULL, "library_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "items_items_children" FOREIGN KEY ("parent_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "items_items_extras" FOREIGN KEY ("owner_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "items_libraries_items" FOREIGN KEY ("library_id") REFERENCES "libraries" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "item_date_added" to table: "items"
CREATE INDEX "item_date_added" ON "items" ("date_added");
-- Create index "item_library_id_kind_sort_key" to table: "items"
CREATE INDEX "item_library_id_kind_sort_key" ON "items" ("library_id", "kind", "sort_key");
-- Create index "item_library_id_path" to table: "items"
CREATE UNIQUE INDEX "item_library_id_path" ON "items" ("library_id", "path") WHERE ((path)::text <> ''::text);
-- Create index "item_owner_id" to table: "items"
CREATE INDEX "item_owner_id" ON "items" ("owner_id");
-- Create index "item_parent_id_sort_key" to table: "items"
CREATE INDEX "item_parent_id_sort_key" ON "items" ("parent_id", "sort_key");
-- Create "people" table
CREATE TABLE "people" ("id" uuid NOT NULL, "name" character varying NOT NULL, "name_key" character varying NOT NULL, "sort_name" character varying NOT NULL DEFAULT '', "overview" text NOT NULL DEFAULT '', "birth_date" timestamptz NULL, "death_date" timestamptz NULL, "birth_place" character varying NOT NULL DEFAULT '', "external_ids" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "person_name_key" to table: "people"
CREATE INDEX "person_name_key" ON "people" ("name_key");
-- Create "credits" table
CREATE TABLE "credits" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "kind" character varying NOT NULL, "role" character varying NOT NULL DEFAULT '', "ord" bigint NOT NULL DEFAULT 0, "item_id" uuid NOT NULL, "person_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "credits_items_credits" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "credits_people_credits" FOREIGN KEY ("person_id") REFERENCES "people" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "credit_item_id_ord" to table: "credits"
CREATE INDEX "credit_item_id_ord" ON "credits" ("item_id", "ord");
-- Create index "credit_person_id" to table: "credits"
CREATE INDEX "credit_person_id" ON "credits" ("person_id");
-- Create "images" table
CREATE TABLE "images" ("id" uuid NOT NULL, "kind" character varying NOT NULL, "index" bigint NOT NULL DEFAULT 0, "path" character varying NOT NULL DEFAULT '', "remote_url" character varying NOT NULL DEFAULT '', "width" bigint NOT NULL DEFAULT 0, "height" bigint NOT NULL DEFAULT 0, "blurhash" character varying NOT NULL DEFAULT '', "thumbhash" bytea NULL, "item_id" uuid NULL, "person_id" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "images_items_images" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "images_people_images" FOREIGN KEY ("person_id") REFERENCES "people" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "image_item_id_kind_index" to table: "images"
CREATE INDEX "image_item_id_kind_index" ON "images" ("item_id", "kind", "index");
-- Create index "image_person_id_kind_index" to table: "images"
CREATE INDEX "image_person_id_kind_index" ON "images" ("person_id", "kind", "index");
-- Create "item_values" table
CREATE TABLE "item_values" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "kind" character varying NOT NULL, "value" character varying NOT NULL, "ord" bigint NOT NULL, "item_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "item_values_items_values" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "itemvalue_item_id_kind_ord" to table: "item_values"
CREATE UNIQUE INDEX "itemvalue_item_id_kind_ord" ON "item_values" ("item_id", "kind", "ord");
-- Create index "itemvalue_kind_value" to table: "item_values"
CREATE INDEX "itemvalue_kind_value" ON "item_values" ("kind", "value");
-- Create "media_sources" table
CREATE TABLE "media_sources" ("id" uuid NOT NULL, "ord" bigint NOT NULL, "path" character varying NOT NULL, "name" character varying NOT NULL DEFAULT '', "container" character varying NOT NULL DEFAULT '', "size" bigint NOT NULL DEFAULT 0, "duration" bigint NOT NULL DEFAULT 0, "bitrate" bigint NOT NULL DEFAULT 0, "streams" jsonb NULL, "chapters" jsonb NULL, "keyframes" jsonb NULL, "probed_at" timestamptz NULL, "item_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "media_sources_items_media_sources" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "mediasource_item_id_ord" to table: "media_sources"
CREATE UNIQUE INDEX "mediasource_item_id_ord" ON "media_sources" ("item_id", "ord");
-- Create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL, "name" character varying NOT NULL, "name_key" character varying NOT NULL, "password_hash" character varying NOT NULL DEFAULT '', "auth_provider" character varying NOT NULL DEFAULT '', "admin" boolean NOT NULL DEFAULT false, "disabled" boolean NOT NULL DEFAULT false, "policy" jsonb NOT NULL, "preferences" jsonb NOT NULL, "created_at" timestamptz NOT NULL, "last_login_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "users_name_key_key" to table: "users"
CREATE UNIQUE INDEX "users_name_key_key" ON "users" ("name_key");
-- Create "user_data" table
CREATE TABLE "user_data" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "played" boolean NOT NULL DEFAULT false, "play_count" bigint NOT NULL DEFAULT 0, "position" bigint NOT NULL DEFAULT 0, "audio_stream" bigint NULL, "subtitle_stream" bigint NULL, "favorite" boolean NOT NULL DEFAULT false, "rating" double precision NULL, "last_played_at" timestamptz NULL, "updated_at" timestamptz NOT NULL, "item_id" uuid NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "user_data_items_user_data" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "user_data_users_user_data" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "userdata_user_id_item_id" to table: "user_data"
CREATE UNIQUE INDEX "userdata_user_id_item_id" ON "user_data" ("user_id", "item_id");
