// Code generated by ent, DO NOT EDIT.

package itemvalue

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mavioai/mavio/libs/core"
	"github.com/mavioai/mavio/libs/store/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldLTE(FieldID, id))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v core.ID) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldItemID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldKind, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldValue, v))
}

// Ord applies equality check predicate on the "ord" field. It's identical to OrdEQ.
func Ord(v int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldOrd, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v core.ID) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v core.ID) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...core.ID) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...core.ID) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNotIn(FieldItemID, vs...))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldContainsFold(FieldKind, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldContainsFold(FieldValue, v))
}

// OrdEQ applies the EQ predicate on the "ord" field.
func OrdEQ(v int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldEQ(FieldOrd, v))
}

// OrdNEQ applies the NEQ predicate on the "ord" field.
func OrdNEQ(v int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNEQ(FieldOrd, v))
}

// OrdIn applies the In predicate on the "ord" field.
func OrdIn(vs ...int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldIn(FieldOrd, vs...))
}

// OrdNotIn applies the NotIn predicate on the "ord" field.
func OrdNotIn(vs ...int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldNotIn(FieldOrd, vs...))
}

// OrdGT applies the GT predicate on the "ord" field.
func OrdGT(v int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldGT(FieldOrd, v))
}

// OrdGTE applies the GTE predicate on the "ord" field.
func OrdGTE(v int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldGTE(FieldOrd, v))
}

// OrdLT applies the LT predicate on the "ord" field.
func OrdLT(v int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldLT(FieldOrd, v))
}

// OrdLTE applies the LTE predicate on the "ord" field.
func OrdLTE(v int) predicate.ItemValue {
	return predicate.ItemValue(sql.FieldLTE(FieldOrd, v))
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.ItemValue {
	return predicate.ItemValue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.Item) predicate.ItemValue {
	return predicate.ItemValue(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ItemValue) predicate.ItemValue {
	return predicate.ItemValue(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ItemValue) predicate.ItemValue {
	return predicate.ItemValue(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ItemValue) predicate.ItemValue {
	return predicate.ItemValue(sql.NotPredicates(p))
}
